In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [66]:
df1 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/real_estate_main.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/mumbai_flats.csv')

df1_copy = df1.copy()
df2_copy = df2.copy()

In [67]:
df1.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat in Kandivali West, Mumbai",Amity Global Business School (1.5 Km) [Univers...,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat in Vile Parle, Mumbai",Vile Parle Railway Station (0.8 km) [Railway S...,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat in Andheri East, Mumbai",JB Nagar Metro Station (4 mins) [Metro Station...,Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat in Chembur, Mumbai",St Gregorios Primary School (1.1 Km) [School] ...,"21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat in Govandi, Mumbai",National Highway 48 (1.9 Km) [Highway] | Chemb...,Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [68]:
df2.head()

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...
1,1 BHK Flat,19.0 L,"Ananta Vardhman Nagar, Tembhode, Palghar, Mumbai",630 sq.ft,₹3.02 K/sq.ft,3 Year Old,Ready to move,Middleof 4 floors,Unfurnished,NaN,Ananta Vardhman Nagar,No ChargeAccess Zero Brokerage Properties,390 sq.ft,1,1,2,1 Open Parking,"1 BHK Flat for sale in Palghar, Mumbai - conta..."
2,1 BHK Flat,73.0 L,"JP North Barcelona, Kashimira, Mira Road East,...",580 sq.ft,₹12.59 K/sq.ft,1 Years Old,Ready to move,Lowerof 25 floors,Semi Furnished,NaN,JP North Barcelona,1.5 LacsAccess Zero Brokerage Properties,475 sq.ft,1,2,2,No Parking,1 BHK Flat for sale in Mumbai. This property i...
3,1 BHK Flat,1.1 Cr,"Chandak Nischay, Ambawadi, Dahisar East, Mumbai",410 sq.ft,₹26.83 K/sq.ft,1 Years Old,Ready to move,Higherof 35 floors,Semi Furnished,NaN,Chandak Nischay,1.1 LacsAccess Zero Brokerage Properties,368 sq.ft,1,2,1,2 Covered Parking,Check out this 1 BHK Flat for sale in Dahisar ...
4,3 BHK Flat,2.25 Cr,"Neelam Solstice Phase I, Nalanda Nagar, Ramaba...",1052 sq.ft,₹21.39 K/sq.ft,1 Years Old,Ready to move,Lowerof 26 floors,Semi Furnished,NaN,Neelam Solstice Phase I,2.1 LacsAccess Zero Brokerage Properties,915 sq.ft,3,2,3,1 Covered Parking,"Situated in ghatkopar east, central mumbai sub..."

In [69]:
df1['NearbyLocations'].isna().value_counts()

NearbyLocations
False    437
True      66
Name: count, dtype: int64

In [70]:
df1.drop(columns='NearbyLocations', inplace=True)

In [71]:
df1.sample(5)

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
357,Goregaon Vivan,"1, 2 BHK Flat in Goregaon West, Mumbai",Walking distance to Ram Mandir Station and upc...,https://www.99acres.com/goregaon-vivan-goregao...,Rs. 1.01 - 1.56 Cr,Pet Area | Lift | EV Charging
124,Godrej Sky Terraces,"3, 4 BHK Flat in Chembur, Mumbai",Bungalow-style living with large private decks...,https://www.99acres.com/godrej-sky-terraces-ch...,Rs. 6.68 - 10.37 Cr,Swimming Pool | Party Area | Rooftop Amenities
500,Samarpan Anuraj CHS,"1, 2 BHK Flat in Borivali East, Mumbai",Scenic views of Sanjay Gandhi National Park | ...,https://www.99acres.com/samarpan-anuraj-chs-bo...,Rs. 1.3 - 1.92 Cr,Pet Area | Park / Garden | Vaastu Compliant
427,Adityaraj Greens,"1, 2 BHK Flat in Powai, Mumbai",Essential infrastructure with lifts and car pa...,https://www.99acres.com/adityaraj-greens-powai...,Rs. 1.2 - 2.09 Cr,Park / Garden | Pet Area | Lift | Parking
477,Neel Sidhi Ashwin,"3 BHK Flat in Ghatkopar East, Mumbai",Video door phone security systems in every fla...,https://www.99acres.com/neel-sidhi-ashwin-ghat...,Rs. 3.67 - 3.97 Cr,Security | Gymnasium

In [72]:
df1.columns= df1.columns.str.strip().str.lower().str.replace(' ', '_')

In [73]:
df1['propertysubname'].isna().value_counts()

propertysubname
False    503
Name: count, dtype: int64

In [74]:
df1['propertysubname'] = df1['propertysubname'].str.split("in").str.get(0)

In [75]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [76]:
# Clean the list by stripping whitespace and removing empty strings
df1['bhk_list'] = df1['propertysubname'].str.replace(" BHK Flat","").str.strip().str.split(",")
display(df1[['propertysubname','bhk_list']].head())

     propertysubname     bhk_list
0  1, 2, 3 BHK Flat   [1,  2,  3]
1  2, 3, 4 BHK Flat   [2,  3,  4]
2     1, 2 BHK Flat       [1,  2]
3  2, 3, 4 BHK Flat   [2,  3,  4]
4     1, 2 BHK Flat       [1,  2]

In [77]:
df1['bhk_list'].value_counts()

bhk_list
[2,  3]                    125
[1,  2]                     86
[1,  2,  3]                 61
[2,  3,  4]                 53
[2]                         35
[3,  4]                     33
[1,  2,  3,  4]             19
[3]                         17
[3,  4,  5]                 15
[1]                         14
[4]                         11
[2,  3,  4,  5]             10
[4,  5]                      4
[2,  4]                      3
[3,  4,  5,  6]              3
[4,  6]                      2
[3,  4,  6]                  2
[1,  3]                      1
[2,  3,  4,  5,  6,  7]      1
[5]                          1
[2,  3,  4,  5,  6]          1
[5,  6,  7]                  1
[1,  2,  3,  4,  5]          1
[1,  3,  4]                  1
[3,  5]                      1
[1,  2,  4]                  1
[2,  3,  5]                  1
Name: count, dtype: int64

In [78]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]"
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]"
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]"
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]"
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]"

In [79]:
def isL(text):

  cleaned = text.replace("Rs. ","").strip().replace(" Cr","").split(" - ")

  if len(cleaned) == 1:
    cleaned.append(cleaned[0])

  if "L" in text:

    if "L" in cleaned[0]:
      cleaned[0] = cleaned[0].replace("L", "").strip()
      cleaned[0] = round(float(cleaned[0])/100,2)

    if "L" in cleaned[1]:
      # Fixed: update cleaned[1] here, not [0] again
      cleaned[1] = cleaned[1].replace("L", "").strip()
      cleaned[1] = round(float(cleaned[1])/100,2)

  # Minimal change: Ensure values are explicitly cast to float
  return [float(cleaned[0]), float(cleaned[1])]

df1[['min_price', 'max_price']] = df1['pricedetails'].apply(isL).tolist()

In [80]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]",1.49,2.21
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]",3.38,8.97
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]",0.83,1.39

In [81]:
new_data = []

for i in range(len(df1)):
  text = df1.loc[i, 'propertysubname']
  bhk_list = text.replace(" BHK Flat","").strip().split(", ")

  prices = list(np.linspace(
          df1.loc[i,'min_price'],
          df1.loc[i,'max_price'],
          len(bhk_list)
      ).round(2))

  for bhk, price in zip(bhk_list, prices):
    new_row = df1.loc[i].copy()
    new_row['propertysubname'] = str(bhk) + " BHK Flat"
    new_row['pricedetails'] = round(price, 2)
    new_data.append(new_row)

new_df = pd.DataFrame(new_data)
new_df

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,3 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,3.22,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,2 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,3.50,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
1,Romell Espalier,3 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,5.20,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
...,...,...,...,...,...,...,...,...,...
500,Samarpan Anuraj CHS,2 BHK Flat,Scenic views of Sanjay Gandhi National Park | ...,https://www.99acres.com/samarpan-anuraj-chs-bo...,1.92,Pet Area | Park / Garden | Vaastu Compliant,"[1, 2]",1.30,1.92
501,Balaji Heights,1 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,1.25,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
501,Balaji Heights,2 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,2.15,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
502,Truearth Vedaa,1 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,0.75,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25
502,Truearth Vedaa,2 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,1.25,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25

In [82]:
new_df.drop(columns=['bhk_list',	'min_price',	'max_price'], inplace=True)

In [83]:
# Exporting the processed dataframe to a CSV file
new_df.to_csv('cleaned_multiple_BHK_real_estate.csv', index=False)

In [86]:
new_df.sample(3)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
64,Paradigm Alaya,3 BHK Flat,"10-acre integrated township with residential, ...",https://www.99acres.com/paradigm-alaya-oshiwar...,2.74,Park / Garden | Rooftop Amenities
90,Lodha Corinthia,4 BHK Flat,4 acres of lush open greens with a 2-acre cent...,https://www.99acres.com/lodha-corinthia-kanjur...,6.54,Pet Area | Park / Garden
349,Raj Imperia,1 BHK Flat,"Rooftop amenities: Yoga Zone, Cabana, Walking ...",https://www.99acres.com/raj-imperia-malad-west...,1.32,Jogging Track | Yoga / Meditation | Rooftop Am...

In [87]:
new_df.iloc[50,2]

'28.32 k sq.m richly landscaped private park | 7 exclusive swimming pools are available | First Evander Holyfield gym of India'

In [93]:
import re
df1['location'] = df1_copy['PropertySubName'].apply(
    lambda x: re.search(r'in (.+?)(?:,\s*Mumbai)?$', x, re.IGNORECASE).group(1).strip()
    if re.search(r'in (.+?)(?:,\s*Mumbai)?$', x, re.IGNORECASE) else None
)

In [95]:
df1.head(1)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price,location
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22,Kandivali West

In [97]:
new_df.head(1)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...

In [104]:
new_df = new_df.merge(df1[['propertyname','location']],on='propertyname', how='left')

In [109]:
new_df['source'] = '99acres'

In [210]:
new_df['bedrooms'] = new_df['propertysubname'].str.split(" ").str.get(0)

In [212]:
new_df.head(2)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,location,source,bedrooms
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,1
1,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,2

In [213]:
new_df.to_csv('cleaned_multiple_BHK_real_estate.csv', index=False)

## Mumbai_Flats.CSV Cleaning

In [112]:
df2['source'] = 'kaggle'

In [137]:
df2['location'] = df2['address'].str.split(', ').str.get(-2)

In [139]:
df2.head(1)

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...,kaggle,Kanjurmarg West

In [153]:
def convert_price(text):

    text = str(text).strip()

    if "Cr" in text:
        return float(text.replace("Cr", "").strip())

    elif "L" in text:
        return round(
            float(text.replace("L", "").strip()) / 100,
            2
        )

    return float(text)

df2['price'] = df2['price'].apply(convert_price)

In [162]:
df2['price'].isna().value_counts()

price
False    9954
Name: count, dtype: int64

In [158]:
df2[df2['price'].isna()]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
8556,3.99 Cr - 10.15 Cr,NaN,"Western India Mills Compound, G D Ambekar Marg...","2, 3, 4, 5 BHK Apartments","Dec, 2025",Price on request,826 sq.ft. - 2104 sq.ft.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kaggle,Central Mumbai Suburbs

In [160]:
df2.drop(index=8556, inplace=True)

In [175]:
df2[~df2['buildup_area'].str.contains("sq.ft")]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
9902,Agricultural Land,0.65,"Manori, Mumbai",500 sq.mt,₹13 K/sq.mt,5 Year Old,Immediate,North-West facingFacing,NaN,NaN,No ChargeAccess Zero Brokerage Properties,65.0 L,50 mt,5 mt,4,No,-,Agricultural Land for Sale in Manori - Malad/K...,kaggle,Manori

In [169]:
df2[df2['buildup_area'].str.contains("5000")]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
3654,4 BHK Flat,45.0,"Indiabulls Blu Tower B, BDD Chawls Worli, Worl...",5000 sq.ft,₹90 K/sq.ft,1 Years Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Indiabulls Blu Tower B,30.0 LacsAccess Zero Brokerage Properties,3400 sq.ft,4,5,No Balcony,3 Covered Parking,A very lavish and spacious 4bhk for lease in a...,kaggle,Worli
3746,4 BHK Flat,45.0,"Bandra West, Mumbai",5000 sq.ft,₹90 K/sq.ft,5 Year Old,Ready to move,Middleof 17 floors,Unfurnished,NaN,45.0 Lacs(Negotiable)Access Zero Brokerage Pro...,45.0 Cr,4,4,3,3 days ago,2 Covered and 1 Open Parking,4 BHK Flat for sale in Mumbai. This property i...,kaggle,Bandra West
8325,3 BHK Villa,35.0,"Bandra West, Mumbai",5000 sq.ft,₹70 K/sq.ft,5 Year Old,Ready to move,Semi FurnishedFurnishing,NaN,NaN,35.0 LacsAccess Zero Brokerage Properties,35.0 Cr,3,3,No Balcony,18 days ago,2 Covered and 1 Open Parking,Available Residential cum commercial bungalow ...,kaggle,Bandra West
9500,10 BHK Independent House,30.0,"Swaraj Homes Chhaya Society, Chembur, Mumbai",15000 sq.ft,₹20 K/sq.ft,10 Year Old,Ready to move,North facingFacing,Unfurnished,NaN,Swaraj Homes Chhaya Society,30.0 LacsAccess Zero Brokerage Properties,14000 sq.ft,10,10,11,9 Open Parking,THIS IS A PRIVATE BUILDING WITH G+7 STOREY WEL...,kaggle,Chembur

In [199]:
df2.iloc[8076,3] = "20700 sq.ft"
df2.loc[9902,'buildup_area'] = "5382 sq.ft"

In [202]:
# 1. Filter the dataset to only include rows that contain 'BHK Flat'
df_flats = df2[df2['flat_type'].str.contains('BHK Flat', na=False)].copy()

# 2. Extract the leading digits, convert them to integer
df_flats['bhk_type'] = df_flats['flat_type'].str.extract(r'(\d+)').astype(int)

# 3. Ensure 'bedrooms' is numeric for a correct comparison
df_flats['bedrooms'] = pd.to_numeric(df_flats['bedrooms'], errors='coerce')

# 4. Find and print rows where flat_type number does not match bedrooms column
mismatch = df_flats[df_flats['bedrooms'] != df_flats['bhk_type']]

print(f"Total Mismatches found: {len(mismatch)}")
print(mismatch[['flat_type', 'bhk_type', 'bedrooms']].head(10))

Total Mismatches found: 1032
        flat_type  bhk_type  bedrooms
43   1.5 BHK Flat         1       2.0
50     1 BHK Flat         1       2.0
60     1 BHK Flat         1       2.0
70     1 BHK Flat         1       2.0
76     1 BHK Flat         1       2.0
85     3 BHK Flat         3       4.0
98     1 BHK Flat         1       2.0
109    3 BHK Flat         3       2.0
118    1 BHK Flat         1       2.0
141    1 BHK Flat         1       2.0

In [203]:
# 1.5 BHK will break if you cast bhk_type to int
print(df2['flat_type'].unique())  # check for 1.5, 2.5, 3.5 BHK etc.

['3 BHK Flat' '1 BHK Flat' '2 BHK Flat' '4 BHK Flat' '7 BHK Flat'
 '1.5 BHK Flat' '3 BHK Independent Builder Floor'
 '1 BHK Independent House' '5 BHK Independent Builder Floor' '6 BHK Flat'
 '3 BHK Villa' '5 BHK Flat' '4 BHK Independent House' '4 BHK Villa'
 '1 RK Flat' '2 BHK Independent House' '3 BHK Independent House'
 '5+ BHK Flat' '1 BHK Independent Builder Floor'
 '4 BHK Independent Builder Floor' '5 BHK Villa' '6 BHK Villa'
 '10 BHK Independent House' 'Agricultural Land' '1 RK Independent House']