In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df1 = pd.read_csv('/content/real_estate_finale_0000_backup.csv')
df2 = pd.read_csv('/content/mumbai_flats.csv')

In [4]:
df1.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat in Kandivali West, Mumbai",Amity Global Business School (1.5 Km) [Univers...,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat in Vile Parle, Mumbai",Vile Parle Railway Station (0.8 km) [Railway S...,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat in Andheri East, Mumbai",JB Nagar Metro Station (4 mins) [Metro Station...,Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat in Chembur, Mumbai",St Gregorios Primary School (1.1 Km) [School] ...,"21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat in Govandi, Mumbai",National Highway 48 (1.9 Km) [Highway] | Chemb...,Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [5]:
df2.head()

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...
1,1 BHK Flat,19.0 L,"Ananta Vardhman Nagar, Tembhode, Palghar, Mumbai",630 sq.ft,₹3.02 K/sq.ft,3 Year Old,Ready to move,Middleof 4 floors,Unfurnished,NaN,Ananta Vardhman Nagar,No ChargeAccess Zero Brokerage Properties,390 sq.ft,1,1,2,1 Open Parking,"1 BHK Flat for sale in Palghar, Mumbai - conta..."
2,1 BHK Flat,73.0 L,"JP North Barcelona, Kashimira, Mira Road East,...",580 sq.ft,₹12.59 K/sq.ft,1 Years Old,Ready to move,Lowerof 25 floors,Semi Furnished,NaN,JP North Barcelona,1.5 LacsAccess Zero Brokerage Properties,475 sq.ft,1,2,2,No Parking,1 BHK Flat for sale in Mumbai. This property i...
3,1 BHK Flat,1.1 Cr,"Chandak Nischay, Ambawadi, Dahisar East, Mumbai",410 sq.ft,₹26.83 K/sq.ft,1 Years Old,Ready to move,Higherof 35 floors,Semi Furnished,NaN,Chandak Nischay,1.1 LacsAccess Zero Brokerage Properties,368 sq.ft,1,2,1,2 Covered Parking,Check out this 1 BHK Flat for sale in Dahisar ...
4,3 BHK Flat,2.25 Cr,"Neelam Solstice Phase I, Nalanda Nagar, Ramaba...",1052 sq.ft,₹21.39 K/sq.ft,1 Years Old,Ready to move,Lowerof 26 floors,Semi Furnished,NaN,Neelam Solstice Phase I,2.1 LacsAccess Zero Brokerage Properties,915 sq.ft,3,2,3,1 Covered Parking,"Situated in ghatkopar east, central mumbai sub..."

In [7]:
df1['NearbyLocations'].isna().value_counts()

NearbyLocations
False    437
True      66
Name: count, dtype: int64

In [11]:
df1.drop(columns='NearbyLocations', inplace=True)

In [22]:
df1.sample(5)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
227,Suraj Aureva,"1, 2 BHK Flat in Prabhadevi, Mumbai",Designed by Hafeez Contractor featuring elegan...,https://www.99acres.com/suraj-aureva-prabhadev...,Rs. 2.48 - 4.31 Cr,Pet Area
191,Neelam Senroofs,"1, 2, 3 BHK Flat in Nahur, Bhandup West",Earthquake-resistant building | Double-heighte...,https://www.99acres.com/neelam-senroofs-nahur-...,Rs. 1.48 - 4.9 Cr,Pet Area | Security | Intercom | CCTV
451,Jivan Prakash 89 Buildcon,"2, 3 BHK Flat in Matunga West, Mumbai",Low-density living with only 6 apartments per ...,https://www.99acres.com/jivan-prakash-89-build...,Rs. 4.22 - 5.16 Cr,Lift
65,Birla Niyaara Phase 2,"4, 5 BHK Flat in Worli, Mumbai",India's first residential project pre-certifie...,https://www.99acres.com/birla-niyaara-phase-2-...,Rs. 33.62 - 47.6 Cr,Spa | Pet Area | Club House | Park / Garden
470,Sagar Soham Heights,"1, 2 BHK Flat in Sector 8 Charkop, Kandivali West",Unobstructed views of the Arabian Sea and Glob...,https://www.99acres.com/sagar-soham-heights-se...,Rs. 92.69 L - 1.48 Cr,Swimming Pool | Jacuzzi | Rooftop Amenities

In [16]:
df1.columns= df1.columns.str.strip().str.lower().str.replace(' ', '_')

In [20]:
df1['propertysubname'].isna().value_counts()

propertysubname
False    503
Name: count, dtype: int64

In [40]:
df1['propertysubname'] = df1['propertysubname'].str.split("in").str.get(0)

In [43]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area