In [166]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [167]:
df1 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/real_estate_main.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/mumbai_flats.csv')

df1_copy = df1.copy()
df2_copy = df2.copy()

In [168]:
df1.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat in Kandivali West, Mumbai",Amity Global Business School (1.5 Km) [Univers...,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat in Vile Parle, Mumbai",Vile Parle Railway Station (0.8 km) [Railway S...,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat in Andheri East, Mumbai",JB Nagar Metro Station (4 mins) [Metro Station...,Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat in Chembur, Mumbai",St Gregorios Primary School (1.1 Km) [School] ...,"21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat in Govandi, Mumbai",National Highway 48 (1.9 Km) [Highway] | Chemb...,Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [169]:
df2.head()

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...
1,1 BHK Flat,19.0 L,"Ananta Vardhman Nagar, Tembhode, Palghar, Mumbai",630 sq.ft,₹3.02 K/sq.ft,3 Year Old,Ready to move,Middleof 4 floors,Unfurnished,NaN,Ananta Vardhman Nagar,No ChargeAccess Zero Brokerage Properties,390 sq.ft,1,1,2,1 Open Parking,"1 BHK Flat for sale in Palghar, Mumbai - conta..."
2,1 BHK Flat,73.0 L,"JP North Barcelona, Kashimira, Mira Road East,...",580 sq.ft,₹12.59 K/sq.ft,1 Years Old,Ready to move,Lowerof 25 floors,Semi Furnished,NaN,JP North Barcelona,1.5 LacsAccess Zero Brokerage Properties,475 sq.ft,1,2,2,No Parking,1 BHK Flat for sale in Mumbai. This property i...
3,1 BHK Flat,1.1 Cr,"Chandak Nischay, Ambawadi, Dahisar East, Mumbai",410 sq.ft,₹26.83 K/sq.ft,1 Years Old,Ready to move,Higherof 35 floors,Semi Furnished,NaN,Chandak Nischay,1.1 LacsAccess Zero Brokerage Properties,368 sq.ft,1,2,1,2 Covered Parking,Check out this 1 BHK Flat for sale in Dahisar ...
4,3 BHK Flat,2.25 Cr,"Neelam Solstice Phase I, Nalanda Nagar, Ramaba...",1052 sq.ft,₹21.39 K/sq.ft,1 Years Old,Ready to move,Lowerof 26 floors,Semi Furnished,NaN,Neelam Solstice Phase I,2.1 LacsAccess Zero Brokerage Properties,915 sq.ft,3,2,3,1 Covered Parking,"Situated in ghatkopar east, central mumbai sub..."

In [170]:
df1['NearbyLocations'].isna().value_counts()

NearbyLocations
False    437
True      66
Name: count, dtype: int64

In [171]:
df1.drop(columns='NearbyLocations', inplace=True)

In [172]:
df1.sample(5)

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
246,Vascon Orchids,"2, 3 BHK Flat in Santacruz West, Mumbai",Exclusive rooftop yoga deck and open-air theat...,https://www.99acres.com/vascon-orchids-santacr...,Rs. 3.28 - 4.5 Cr,Pet Area | Yoga / Meditation | Rooftop Amenities
499,Ruparel Iris,"1, 2, 3 BHK Flat in Matunga West, Mumbai",Iconic 40-storeyed tower with a sports aerodyn...,https://www.99acres.com/ruparel-iris-matunga-w...,Rs. 3.25 - 10.01 Cr,Pet Area | Security
170,Platinum Oceanic,"2, 3 BHK Flat in Khar West, Mumbai",Private sun decks with panoramic Arabian Sea v...,https://www.99acres.com/platinum-oceanic-khar-...,Rs. 3.47 - 6.22 Cr,Pet Area | Swimming Pool | Party Area | Roofto...
198,Raghav Vista,"1 BHK Flat in Chembur, Mumbai",Fully equipped homes with branded appliances a...,https://www.99acres.com/raghav-vista-chembur-c...,Rs. 1.18 Cr,Pet Area | Yoga / Meditation | Rooftop Ameniti...
188,L&T Emerald Isle,"2, 3, 4 BHK Flat in Powai, Mumbai",9 mins drive to Indian Institute of Technology...,https://www.99acres.com/l-t-emerald-isle-powai...,Rs. 1.76 - 12.01 Cr,Pet Area

In [173]:
df1.columns= df1.columns.str.strip().str.lower().str.replace(' ', '_')

In [174]:
df1['propertysubname'].isna().value_counts()

propertysubname
False    503
Name: count, dtype: int64

In [175]:
df1['propertysubname'] = df1['propertysubname'].str.split("in").str.get(0)

In [176]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [177]:
# Clean the list by stripping whitespace and removing empty strings
df1['bhk_list'] = df1['propertysubname'].str.replace(" BHK Flat","").str.strip().str.split(",")
display(df1[['propertysubname','bhk_list']].head())

     propertysubname     bhk_list
0  1, 2, 3 BHK Flat   [1,  2,  3]
1  2, 3, 4 BHK Flat   [2,  3,  4]
2     1, 2 BHK Flat       [1,  2]
3  2, 3, 4 BHK Flat   [2,  3,  4]
4     1, 2 BHK Flat       [1,  2]

In [178]:
df1['bhk_list'].value_counts()

bhk_list
[2,  3]                    125
[1,  2]                     86
[1,  2,  3]                 61
[2,  3,  4]                 53
[2]                         35
[3,  4]                     33
[1,  2,  3,  4]             19
[3]                         17
[3,  4,  5]                 15
[1]                         14
[4]                         11
[2,  3,  4,  5]             10
[4,  5]                      4
[2,  4]                      3
[3,  4,  5,  6]              3
[4,  6]                      2
[3,  4,  6]                  2
[1,  3]                      1
[2,  3,  4,  5,  6,  7]      1
[5]                          1
[2,  3,  4,  5,  6]          1
[5,  6,  7]                  1
[1,  2,  3,  4,  5]          1
[1,  3,  4]                  1
[3,  5]                      1
[1,  2,  4]                  1
[2,  3,  5]                  1
Name: count, dtype: int64

In [179]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]"
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]"
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]"
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]"
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]"

In [180]:
def isL(text):

  cleaned = text.replace("Rs. ","").strip().replace(" Cr","").split(" - ")

  if len(cleaned) == 1:
    cleaned.append(cleaned[0])

  if "L" in text:

    if "L" in cleaned[0]:
      cleaned[0] = cleaned[0].replace("L", "").strip()
      cleaned[0] = round(float(cleaned[0])/100,2)

    if "L" in cleaned[1]:
      # Fixed: update cleaned[1] here, not [0] again
      cleaned[1] = cleaned[1].replace("L", "").strip()
      cleaned[1] = round(float(cleaned[1])/100,2)

  # Minimal change: Ensure values are explicitly cast to float
  return [float(cleaned[0]), float(cleaned[1])]

df1[['min_price', 'max_price']] = df1['pricedetails'].apply(isL).tolist()

In [181]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]",1.49,2.21
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]",3.38,8.97
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]",0.83,1.39

In [182]:
new_data = []

for i in range(len(df1)):
  text = df1.loc[i, 'propertysubname']
  bhk_list = text.replace(" BHK Flat","").strip().split(", ")

  prices = list(np.linspace(
          df1.loc[i,'min_price'],
          df1.loc[i,'max_price'],
          len(bhk_list)
      ).round(2))

  for bhk, price in zip(bhk_list, prices):
    new_row = df1.loc[i].copy()
    new_row['propertysubname'] = str(bhk) + " BHK Flat"
    new_row['pricedetails'] = round(price, 2)
    new_data.append(new_row)

new_df = pd.DataFrame(new_data)
new_df

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,3 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,3.22,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,2 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,3.50,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
1,Romell Espalier,3 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,5.20,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
...,...,...,...,...,...,...,...,...,...
500,Samarpan Anuraj CHS,2 BHK Flat,Scenic views of Sanjay Gandhi National Park | ...,https://www.99acres.com/samarpan-anuraj-chs-bo...,1.92,Pet Area | Park / Garden | Vaastu Compliant,"[1, 2]",1.30,1.92
501,Balaji Heights,1 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,1.25,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
501,Balaji Heights,2 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,2.15,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
502,Truearth Vedaa,1 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,0.75,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25
502,Truearth Vedaa,2 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,1.25,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25

In [183]:
new_df.drop(columns=['bhk_list',	'min_price',	'max_price'], inplace=True)

In [184]:
# Exporting the processed dataframe to a CSV file
new_df.to_csv('cleaned_multiple_BHK_real_estate.csv', index=False)

In [185]:
new_df.sample(3)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
474,Panom Parleshwar Aangan,3 BHK Flat,City's largest rooftop 120 ft above ground wit...,https://www.99acres.com/panom-parleshwar-aanga...,3.59,Pet Area | Rooftop Amenities | Miyawaki Forest...
375,CCI Rivali Park Skyleap,3 BHK Flat,Comprehensive fitness zone with gym and badmin...,https://www.99acres.com/cci-rivali-park-skylea...,3.84,Park / Garden | Pet Area | Gymnasium | Badmint...
58,Rustomjee Crown,3 BHK Flat,"Two towers rising to 68 storeys with 11'9"" cle...",https://www.99acres.com/rustomjee-crown-prabha...,11.83,Pet Area

In [186]:
new_df.iloc[50,2]

'28.32 k sq.m richly landscaped private park | 7 exclusive swimming pools are available | First Evander Holyfield gym of India'

In [187]:
import re
df1['location'] = df1_copy['PropertySubName'].apply(
    lambda x: re.search(r'in (.+?)(?:,\s*Mumbai)?$', x, re.IGNORECASE).group(1).strip()
    if re.search(r'in (.+?)(?:,\s*Mumbai)?$', x, re.IGNORECASE) else None
)

In [188]:
df1.head(1)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price,location
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22,Kandivali West

In [189]:
new_df.head(1)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...

In [190]:
new_df = new_df.merge(df1[['propertyname','location']],on='propertyname', how='left')

In [191]:
new_df['source'] = '99acres'

In [192]:
new_df['bedrooms'] = new_df['propertysubname'].str.split(" ").str.get(0)

In [193]:
new_df.head(2)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,location,source,bedrooms
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,1
1,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,2

In [194]:
new_df.to_csv('cleaned_multiple_BHK_real_estate.csv', index=False)

## Mumbai_Flats.CSV Cleaning

In [195]:
df2['source'] = 'kaggle'

In [196]:
df2['location'] = df2['address'].str.split(', ').str.get(-2)

In [197]:
df2.head(1)

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...,kaggle,Kanjurmarg West

In [198]:
def convert_price(text):

    text = str(text).strip()

    if "Cr" in text:
        return float(text.replace("Cr", "").strip())

    elif "L" in text:
        return round(
            float(text.replace("L", "").strip()) / 100,
            2
        )

    return float(text)

df2['price'] = df2['price'].apply(convert_price)

In [199]:
df2['price'].isna().value_counts()

price
False    9954
True        1
Name: count, dtype: int64

In [200]:
df2[df2['price'].isna()]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
8556,3.99 Cr - 10.15 Cr,NaN,"Western India Mills Compound, G D Ambekar Marg...","2, 3, 4, 5 BHK Apartments","Dec, 2025",Price on request,826 sq.ft. - 2104 sq.ft.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kaggle,Central Mumbai Suburbs

In [201]:
df2.drop(index=8556, inplace=True)

In [202]:
df2[~df2['buildup_area'].str.contains("sq.ft")]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
8076,3 BHK Independent House,8.20,"Hiranandani Maitri Park, Sahakar Nagar, Chembu...",2300 sq.yd,₹35.65 K/sq.yd,10 Year Old,Ready to move,South-West facingFacing,Fully Furnished,NaN,Hiranandani Maitri Park,8.2 Lacs(Negotiable)Access Zero Brokerage Prop...,2200 sq.yd,3,3,2,1 Covered and 1 Open Parking,Certainly! Here's an alternate description for...,kaggle,Chembur
9902,Agricultural Land,0.65,"Manori, Mumbai",500 sq.mt,₹13 K/sq.mt,5 Year Old,Immediate,North-West facingFacing,NaN,NaN,No ChargeAccess Zero Brokerage Properties,65.0 L,50 mt,5 mt,4,No,-,Agricultural Land for Sale in Manori - Malad/K...,kaggle,Manori

In [203]:
df2[df2['buildup_area'].str.contains("5000")]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
3654,4 BHK Flat,45.0,"Indiabulls Blu Tower B, BDD Chawls Worli, Worl...",5000 sq.ft,₹90 K/sq.ft,1 Years Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Indiabulls Blu Tower B,30.0 LacsAccess Zero Brokerage Properties,3400 sq.ft,4,5,No Balcony,3 Covered Parking,A very lavish and spacious 4bhk for lease in a...,kaggle,Worli
3746,4 BHK Flat,45.0,"Bandra West, Mumbai",5000 sq.ft,₹90 K/sq.ft,5 Year Old,Ready to move,Middleof 17 floors,Unfurnished,NaN,45.0 Lacs(Negotiable)Access Zero Brokerage Pro...,45.0 Cr,4,4,3,3 days ago,2 Covered and 1 Open Parking,4 BHK Flat for sale in Mumbai. This property i...,kaggle,Bandra West
8325,3 BHK Villa,35.0,"Bandra West, Mumbai",5000 sq.ft,₹70 K/sq.ft,5 Year Old,Ready to move,Semi FurnishedFurnishing,NaN,NaN,35.0 LacsAccess Zero Brokerage Properties,35.0 Cr,3,3,No Balcony,18 days ago,2 Covered and 1 Open Parking,Available Residential cum commercial bungalow ...,kaggle,Bandra West
9500,10 BHK Independent House,30.0,"Swaraj Homes Chhaya Society, Chembur, Mumbai",15000 sq.ft,₹20 K/sq.ft,10 Year Old,Ready to move,North facingFacing,Unfurnished,NaN,Swaraj Homes Chhaya Society,30.0 LacsAccess Zero Brokerage Properties,14000 sq.ft,10,10,11,9 Open Parking,THIS IS A PRIVATE BUILDING WITH G+7 STOREY WEL...,kaggle,Chembur

In [204]:
df2.iloc[8076,3] = "20700 sq.ft"
df2.loc[9902,'buildup_area'] = "5382 sq.ft"

In [205]:
# 1. Filter the dataset to only include rows that contain 'BHK Flat'
df_flats = df2[df2['flat_type'].str.contains('BHK Flat', na=False)].copy()

# 2. Extract the leading digits, convert them to integer
df_flats['bhk_type'] = df_flats['flat_type'].str.extract(r'(\d+)').astype(int)

# 3. Ensure 'bedrooms' is numeric for a correct comparison
df_flats['bedrooms'] = pd.to_numeric(df_flats['bedrooms'], errors='coerce')

# 4. Find and print rows where flat_type number does not match bedrooms column
mismatch = df_flats[df_flats['bedrooms'] != df_flats['bhk_type']]

print(f"Total Mismatches found: {len(mismatch)}")
print(mismatch[['flat_type', 'bhk_type', 'bedrooms']].head(10))

Total Mismatches found: 1032
        flat_type  bhk_type  bedrooms
43   1.5 BHK Flat         1       2.0
50     1 BHK Flat         1       2.0
60     1 BHK Flat         1       2.0
70     1 BHK Flat         1       2.0
76     1 BHK Flat         1       2.0
85     3 BHK Flat         3       4.0
98     1 BHK Flat         1       2.0
109    3 BHK Flat         3       2.0
118    1 BHK Flat         1       2.0
141    1 BHK Flat         1       2.0

In [206]:
print(df2['flat_type'].unique())

['3 BHK Flat' '1 BHK Flat' '2 BHK Flat' '4 BHK Flat' '7 BHK Flat'
 '1.5 BHK Flat' '3 BHK Independent Builder Floor'
 '1 BHK Independent House' '5 BHK Independent Builder Floor' '6 BHK Flat'
 '3 BHK Villa' '5 BHK Flat' '4 BHK Independent House' '4 BHK Villa'
 '1 RK Flat' '2 BHK Independent House' '3 BHK Independent House'
 '5+ BHK Flat' '1 BHK Independent Builder Floor'
 '4 BHK Independent Builder Floor' '5 BHK Villa' '6 BHK Villa'
 '10 BHK Independent House' 'Agricultural Land' '1 RK Independent House']

In [207]:
df2 = df2[df2['flat_type'].str.contains('Flat', na=False)].reset_index(drop=True)

In [208]:
def parse_sqft(val):
    if pd.isna(val):
        return np.nan

    val_str = str(val).replace('sq.ft', '').replace(',', '').strip()

    if '-' in val_str:
        parts = val_str.split('-')
        try:
            return (float(parts[0].strip()) + float(parts[1].strip())) / 2
        except ValueError:
            return np.nan

    try:
        val_float = float(val_str)
        return val_float if val_float >= 100 else np.nan
    except ValueError:
        return np.nan

df2['buildup_area_sqft'] = df2['buildup_area'].apply(parse_sqft)
df2['carpet_area_sqft']  = df2['carpet_area'].apply(parse_sqft)

In [209]:
df2['furnishing'] = df2['facing'].apply(
    lambda x: x if pd.notna(x) and 'urnished' in str(x) else np.nan
)
df2['furnishing'] = df2['furnishing'].fillna('Unknown')

In [210]:
df2['is_ready_to_move'] = df2['possesion_status'] == 'Ready to move'

In [211]:
def parse_age(val):
    val = str(val).strip()
    if val == 'Ready to move':
        return 0
    # BHK values that got misplaced — treat as NaN
    if 'BHK' in val:
        return np.nan
    first = val.split(' ')[0]
    try:
        return int(first)
    except ValueError:
        return np.nan

df2['age_of_property'] = df2['age_of_property'].apply(parse_age)

In [212]:
def parse_floor(val):
    if pd.isna(val): return np.nan
    val = str(val)
    if 'of' in val:
        position = val.split('of')[0].strip()
        if position in ('Higher', 'Middle', 'Lower'):
            return position
    return np.nan

df2['which_floor'] = df2['which_floor'].apply(parse_floor)

In [213]:
def parkingCount(text):
    if pd.isna(text) or str(text).strip() == '-':
        return 0

    text = str(text)

    if 'Covered' in text and 'Open' in text:
        num1 = int(text.split(' ')[0])
        num2 = int(text.split(' ')[-3])
        return num1 + num2

    elif 'Covered' in text or 'Open' in text:
        return int(text.split(' ')[0])

    return 0

df2['parking'] = df2['parking'].apply(parkingCount)

In [214]:
# fix bedrooms: drop misplaced values
df2['bedrooms'] = pd.to_numeric(df2['bedrooms'], errors='coerce')

In [215]:
# drop columns no longer needed
df2.drop(columns=[
    'address', 'buildup_area', 'carpet_area',
    'avg_price_sqft', 'facing', 'furnicing', 'brokrage',
    'about_property'
], inplace=True)

In [216]:
mask = df2['bathrooms'] == 'No Balcony'
df2.loc[mask, 'balcony'] = 'No Balcony'
df2.loc[mask, 'bathrooms'] = np.nan

In [217]:
mask = ~df2['possesion_status'].str.contains("Ready to move", na=False)
df2.loc[mask,'possesion_status'] = np.nan

In [218]:
df2['flat_type'] = df2['flat_type'].str.replace("1 RK Flat", "0.5 BHK Flat")

In [219]:
df2 = df2[['flat_type', 'price', 'age_of_property', 'possesion_status', 'which_floor', 'project_name', 'bedrooms', 'bathrooms', 'balcony', 'parking', 'source', 'location', 'buildup_area_sqft', 'carpet_area_sqft', 'is_ready_to_move', 'furnishing']]

In [220]:
df2.to_csv('cleaned_mumbai_flats_aftermath_final.csv', index=False)
df2.head(3)

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing
0,3 BHK Flat,3.95,3.0,Ready to move,Higher,Runwal Forest Tower 5 To 8,3.0,2,1,2,kaggle,Kanjurmarg West,1550.0,1130.0,True,Fully Furnished
1,1 BHK Flat,0.19,3.0,Ready to move,Middle,Ananta Vardhman Nagar,1.0,1,2,1,kaggle,Palghar,630.0,390.0,True,Unfurnished
2,1 BHK Flat,0.73,1.0,Ready to move,Lower,JP North Barcelona,1.0,2,2,0,kaggle,Mira Road East,580.0,475.0,True,Semi Furnished

In [221]:
df2.shape

(9894, 16)

In [222]:
list(df2.columns)

['flat_type',
 'price',
 'age_of_property',
 'possesion_status',
 'which_floor',
 'project_name',
 'bedrooms',
 'bathrooms',
 'balcony',
 'parking',
 'source',
 'location',
 'buildup_area_sqft',
 'carpet_area_sqft',
 'is_ready_to_move',
 'furnishing']

In [223]:
df2['price_per_sqft'] = df2['price']*10000000/df2['buildup_area_sqft']

In [224]:
df2['bathrooms'] = pd.to_numeric(df2['bathrooms'], errors='coerce')

df2['balcony'] = pd.to_numeric(df2['balcony'].replace('No Balcony', 0), errors='coerce').fillna(0)

print("Cleaned Bathrooms:", df2['bathrooms'].unique()[:10])
print("Cleaned Balcony:", df2['balcony'].unique()[:10])

Cleaned Bathrooms: [ 2.  1.  3.  5.  4. nan  6.  7.  8.]
Cleaned Balcony: [1. 2. 3. 0. 4. 5. 7. 6.]

In [225]:
furnish_score = {'Fully Furnished': 3, 'Semi Furnished': 2, 'Unfurnished': 1, 'Unknown': 0}

# Now calculate the score safely
df2['property_score'] = (
    df2['furnishing'].map(furnish_score).fillna(0) +
    (df2['price_per_sqft'] > df2['price_per_sqft'].quantile(0.75)).astype(int) * 2 +
    (df2['bathrooms'] >= 3).astype(int) +
    (df2['balcony'] >= 2).astype(int)
)

display(df2[['project_name', 'furnishing', 'price_per_sqft', 'bathrooms', 'balcony', 'property_score']].head())

,project_name,furnishing,price_per_sqft,bathrooms,balcony,property_score
0,Runwal Forest Tower 5 To 8,Fully Furnished,25483.870968,2.0,1.0,3
1,Ananta Vardhman Nagar,Unfurnished,3015.873016,1.0,2.0,2
2,JP North Barcelona,Semi Furnished,12586.206897,2.0,2.0,3
3,Chandak Nischay,Semi Furnished,26829.268293,2.0,1.0,2
4,Neelam Solstice Phase I,Semi Furnished,21387.832700,2.0,3.0,3

In [226]:
df2['bathrooms'].unique()

array([ 2.,  1.,  3.,  5.,  4., nan,  6.,  7.,  8.])

## Other work

In [227]:
df1.columns

Index(['propertyname', 'propertysubname', 'locationadvantages', 'link',
       'pricedetails', 'topfacilities', 'bhk_list', 'min_price', 'max_price',
       'location'],
      dtype='object')

In [228]:
df2.columns

Index(['flat_type', 'price', 'age_of_property', 'possesion_status',
       'which_floor', 'project_name', 'bedrooms', 'bathrooms', 'balcony',
       'parking', 'source', 'location', 'buildup_area_sqft',
       'carpet_area_sqft', 'is_ready_to_move', 'furnishing', 'price_per_sqft',
       'property_score'],
      dtype='object')

In [229]:
new_df.rename({'propertyname':'project_name'}, axis=1, inplace=True)

In [230]:
new_df.head()

,project_name,propertysubname,locationadvantages,link,pricedetails,topfacilities,location,source,bedrooms
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,1
1,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,2
2,ModiRealty Olive,3 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,3.22,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,3
3,Romell Espalier,2 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,3.50,Spa | Pet Area | Swimming Pool,Vile Parle,99acres,2
4,Romell Espalier,3 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,5.20,Spa | Pet Area | Swimming Pool,Vile Parle,99acres,3

### Step 1: Drop unnecessary columns from 99acres data

In [231]:
new_df.drop(columns=['link'], inplace=True, errors='ignore')
# Map propertysubname to flat_type so it merges correctly with df2
new_df.rename(columns={'pricedetails': 'price', 'propertysubname': 'flat_type'}, inplace=True)
display(new_df.head(2))

,project_name,flat_type,locationadvantages,price,topfacilities,location,source,bedrooms
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,1
1,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,2

### Step 2: Merge the two datasets

In [232]:
# Concatenate the two DataFrames
final_df = pd.concat([df2, new_df], ignore_index=True)

# Ensure bedrooms is numeric for the whole set
final_df['bedrooms'] = pd.to_numeric(final_df['bedrooms'], errors='coerce')

print(f"Final DataFrame Shape: {final_df.shape}")
display(final_df.sample(10))

Final DataFrame Shape: (11031, 20)

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing,price_per_sqft,property_score,locationadvantages,topfacilities
4206,2 BHK Flat,2.40,10.0,Ready to move,Middle,Sheth Vasant Valley,2.0,2.0,0.0,1.0,kaggle,Malad East,1300.0,800.0,True,Unfurnished,18461.538462,1.0,NaN,NaN
6021,1 BHK Flat,0.53,10.0,Ready to move,Lower,Mahada New Tower,1.0,1.0,0.0,2.0,kaggle,Malad West,450.0,305.0,True,Unknown,11777.777778,0.0,NaN,NaN
10851,1 BHK Flat,1.50,NaN,NaN,NaN,Kabra Residency Park,1.0,NaN,NaN,NaN,99acres,Sakinaka,NaN,NaN,NaN,NaN,NaN,NaN,Just a 5-minute walk to Saki Naka Metro Statio...,Park / Garden
10880,2 BHK Flat,1.69,NaN,NaN,NaN,RV Satre Elite,2.0,NaN,NaN,NaN,99acres,Mulund East,NaN,NaN,NaN,NaN,NaN,NaN,Iconic high-rise residential tower featuring G...,Spa | Pet Area
3680,4 BHK Flat,5.70,4.0,Ready to move,Middle,Heritage Pride,4.0,3.0,0.0,2.0,kaggle,Chembur,2000.0,NaN,True,Semi Furnished,28500.000000,3.0,NaN,NaN
10109,2 BHK Flat,2.93,NaN,NaN,NaN,Dosti Mezzo 22,2.0,NaN,NaN,NaN,99acres,Sion East,NaN,NaN,NaN,NaN,NaN,NaN,Expansive three-tier amenity zones across grou...,Pet Area | Rooftop Amenities | Podium Amenitie...
10381,2 BHK Flat,3.17,NaN,NaN,NaN,Runwal Beyond The Greens,2.0,NaN,NaN,NaN,99acres,Chembur,NaN,NaN,NaN,NaN,NaN,NaN,Choose among three distinct pools designed to ...,Park / Garden | Rooftop Amenities
10216,3 BHK Flat,4.03,NaN,NaN,NaN,Neelam Supremos,3.0,NaN,NaN,NaN,99acres,Mulund East,NaN,NaN,NaN,NaN,NaN,NaN,Exclusive Low-Density Project | EV Charging Av...,EV Charging
11029,1 BHK Flat,0.75,NaN,NaN,NaN,Truearth Vedaa,1.0,NaN,NaN,NaN,99acres,Vikhroli,NaN,NaN,NaN,NaN,NaN,NaN,"Prime Vikhroli location with seamless metro, r...",Pet Area | Yoga / Meditation | Gymnasium | Chi...
5431,5 BHK Flat,9.50,5.0,Ready to move,Middle,9.5 LacsAccess Zero Brokerage Properties,1.0,NaN,0.0,2.0,kaggle,Juhu,2400.0,NaN,True,Unknown,39583.333333,2.0,NaN,NaN

## Handling Missing values after merging

In [233]:
cols_to_impute = ['buildup_area_sqft', 'carpet_area_sqft', 'bathrooms', 'balcony', 'parking', 'age_of_property']

# Using 'bedrooms' as the grouping key for BHK-type
for col in cols_to_impute:
    final_df[col] = final_df.groupby('flat_type')[col].transform(
        lambda x: x.fillna(x.median())
    )

In [234]:
final_df['furnishing'] = final_df['furnishing'].fillna('Unknown')
final_df['which_floor'] = final_df['which_floor'].fillna('Unknown')
final_df['is_ready_to_move'] = final_df['is_ready_to_move'].fillna(True)  # assuming active 99acres listings are ready
final_df['possesion_status'] = final_df['possesion_status'].fillna('Ready to move')

/tmp/ipykernel_5025/4232924243.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df['is_ready_to_move'] = final_df['is_ready_to_move'].fillna(True)  # assuming active 99acres listings are ready

In [235]:
final_df['locationadvantages'] = final_df['locationadvantages'].fillna('')
final_df['topfacilities'] = final_df['topfacilities'].fillna('')

In [236]:
final_df['price_per_sqft'] = (final_df['price'] * 10000000) / final_df['buildup_area_sqft']

print("Imputation and Feature derivation complete.")
display(final_df.isnull().sum())
display(final_df.sample(5))

Imputation and Feature derivation complete.

flat_type                0
price                    0
age_of_property          0
possesion_status         0
which_floor              0
project_name             0
bedrooms                88
bathrooms                0
balcony                  0
parking                  0
source                   0
location                 0
buildup_area_sqft        0
carpet_area_sqft         0
is_ready_to_move         0
furnishing               0
price_per_sqft           0
property_score        1137
locationadvantages       0
topfacilities            0
dtype: int64

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing,price_per_sqft,property_score,locationadvantages,topfacilities
1640,1 BHK Flat,0.70,1.0,Ready to move,Middle,JP North Barcelona,1.0,2.0,3.0,0.0,kaggle,Mira Road East,600.0,395.0,True,Unfurnished,11666.666667,2.0,,
1893,1 BHK Flat,0.28,3.0,Ready to move,Lower,Bhoomi Acropolis 2,1.0,1.0,1.0,1.0,kaggle,Virar West,750.0,430.0,True,Semi Furnished,3733.333333,2.0,,
4118,3 BHK Flat,3.40,8.0,Ready to move,Lower,Rustomjee Elanza,3.0,3.0,3.0,2.0,kaggle,Malad West,1100.0,890.0,True,Semi Furnished,30909.090909,6.0,,
5699,1 BHK Flat,0.96,10.0,Ready to move,Lower,Lords,1.0,1.0,0.0,1.0,kaggle,Bhandup West,510.0,450.0,True,Unfurnished,18823.529412,1.0,,
2888,1 BHK Flat,1.02,30.0,Ready to move,Higher,Siddharth Nagar Complex,1.0,2.0,0.0,1.0,kaggle,Borivali East,585.0,435.0,True,Semi Furnished,17435.897436,2.0,,

In [237]:
# Recalculate property_score for the entire unified dataset
furnish_score = {'Fully Furnished': 3, 'Semi Furnished': 2, 'Unfurnished': 1, 'Unknown': 0}

# Consistent scoring logic: furnishing + high price/sqft + bathrooms + balcony
final_df['property_score'] = (
    final_df['furnishing'].map(furnish_score).fillna(0) +
    (final_df['price_per_sqft'] > final_df['price_per_sqft'].quantile(0.75)).astype(int) * 2 +
    (final_df['bathrooms'] >= 3).astype(int) +
    (final_df['balcony'] >= 2).astype(int)
)

print("Preprocessing Phase Complete. Final Null Summary:")
display(final_df.isnull().sum())
display(final_df[final_df['source'] == '99acres'].head())

Preprocessing Phase Complete. Final Null Summary:

flat_type              0
price                  0
age_of_property        0
possesion_status       0
which_floor            0
project_name           0
bedrooms              88
bathrooms              0
balcony                0
parking                0
source                 0
location               0
buildup_area_sqft      0
carpet_area_sqft       0
is_ready_to_move       0
furnishing             0
price_per_sqft         0
property_score         0
locationadvantages     0
topfacilities          0
dtype: int64

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing,price_per_sqft,property_score,locationadvantages,topfacilities
9894,1 BHK Flat,1.37,5.0,Ready to move,Unknown,ModiRealty Olive,1.0,2.0,0.0,1.0,99acres,Kandivali West,600.0,425.0,True,Unknown,22833.333333,0,5-minute walk to Valnai Metro and St. Anne Int...,Spa | Vaastu Compliant | Children's Play Area ...
9895,2 BHK Flat,2.30,5.0,Ready to move,Unknown,ModiRealty Olive,2.0,2.0,0.0,1.0,99acres,Kandivali West,900.0,690.0,True,Unknown,25555.555556,0,5-minute walk to Valnai Metro and St. Anne Int...,Spa | Vaastu Compliant | Children's Play Area ...
9896,3 BHK Flat,3.22,5.0,Ready to move,Unknown,ModiRealty Olive,3.0,3.0,0.0,2.0,99acres,Kandivali West,1400.0,1073.0,True,Unknown,23000.000000,1,5-minute walk to Valnai Metro and St. Anne Int...,Spa | Vaastu Compliant | Children's Play Area ...
9897,2 BHK Flat,3.50,5.0,Ready to move,Unknown,Romell Espalier,2.0,2.0,0.0,1.0,99acres,Vile Parle,900.0,690.0,True,Unknown,38888.888889,2,One of the tallest towers in Vile Parle East |...,Spa | Pet Area | Swimming Pool
9898,3 BHK Flat,5.20,5.0,Ready to move,Unknown,Romell Espalier,3.0,3.0,0.0,2.0,99acres,Vile Parle,1400.0,1073.0,True,Unknown,37142.857143,3,One of the tallest towers in Vile Parle East |...,Spa | Pet Area | Swimming Pool

In [238]:
final_df.sample(10)

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing,price_per_sqft,property_score,locationadvantages,topfacilities
4480,1 BHK Flat,0.95,25.0,Ready to move,Middle,"95,000Access Zero Brokerage Properties",1.0,2.0,0.0,1.0,kaggle,Powai,570.0,425.0,True,Unfurnished,16666.666667,1,,
5577,1 BHK Flat,0.96,18.0,Ready to move,Higher,HDIL Dheeraj Upvan 2,1.0,2.0,0.0,0.0,kaggle,Borivali East,595.0,428.0,True,Unfurnished,16134.453782,1,,
1521,1 BHK Flat,0.65,1.0,Ready to move,Higher,"65,000Access Zero Brokerage Properties",2.0,2.0,0.0,1.0,kaggle,Jogeshwari East,400.0,425.0,True,Unfurnished,16250.000000,1,,
6785,2 BHK Flat,2.00,5.0,Ready to move,Middle,Godrej Central,2.0,2.0,1.0,1.0,kaggle,Chembur,850.0,751.0,True,Unfurnished,23529.411765,1,,
1131,4 BHK Flat,3.30,1.0,Ready to move,Middle,Rizvi Cedar,4.0,3.0,0.0,1.0,kaggle,Malad East,1292.0,1192.0,True,Semi Furnished,25541.795666,3,,
6806,2 BHK Flat,0.52,1.0,Ready to move,Higher,Sunteck West World 2 Tivri Naigaon East,2.0,1.0,3.0,1.0,kaggle,Naigaon East,850.0,547.0,True,Unfurnished,6117.647059,2,,
3474,4 BHK Flat,13.00,10.0,Ready to move,Lower,Lakefront Solitaire,4.0,5.0,2.0,2.0,kaggle,Powai,3250.0,2250.0,True,Semi Furnished,40000.000000,6,,
8339,3 BHK Flat,7.00,1.0,Ready to move,Higher,Wadhwa Pristine,3.0,3.0,0.0,2.0,kaggle,Matunga West,1800.0,1243.0,True,Semi Furnished,38888.888889,5,,
1550,1 BHK Flat,0.45,1.0,Ready to move,Higher,Seven Eleven Apna Ghar,1.0,2.0,0.0,1.0,kaggle,Mira Road East,397.0,425.0,True,Unfurnished,11335.012594,1,,
10036,4 BHK Flat,15.95,5.0,Ready to move,Unknown,Piramal Mahalaxmi,4.0,4.0,0.0,2.0,99acres,Mahalaxmi,2200.0,1715.0,True,Unknown,72500.000000,3,"Expansive 74,000 sq. ft. open podium space for...",Spa | Pet Area | Podium Amenities

In [239]:
final_df[final_df['bedrooms'].isna()]

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing,price_per_sqft,property_score,locationadvantages,topfacilities
231,3 BHK Flat,4.50,4.0,Ready to move,Higher,4.5 LacsAccess Zero Brokerage Properties,NaN,3.0,0.0,1.0,kaggle,Vile Parle East,1200.0,1073.0,True,Unfurnished,37500.000000,4,,
349,1 BHK Flat,1.07,1.0,Ready to move,Lower,1.1 LacsAccess Zero Brokerage Properties,NaN,2.0,0.0,1.0,kaggle,Mulund West,520.0,425.0,True,Semi Furnished,20576.923077,2,,
760,2 BHK Flat,1.65,1.0,Ready to move,Middle,1.6 LacsAccess Zero Brokerage Properties,NaN,2.0,0.0,1.0,kaggle,Chembur,1222.0,690.0,True,Unfurnished,13502.454992,1,,
1021,4 BHK Flat,1.82,3.0,Ready to move,Higher,1.8 LacsAccess Zero Brokerage Properties,NaN,4.0,0.0,1.0,kaggle,Borivali East,1000.0,1715.0,True,Semi Furnished,18200.000000,3,,
1391,1 BHK Flat,1.07,1.0,Ready to move,Lower,1.1 LacsAccess Zero Brokerage Properties,NaN,2.0,0.0,1.0,kaggle,Mulund West,580.0,425.0,True,Semi Furnished,18448.275862,2,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9231,2 BHK Flat,1.40,1.0,Ready to move,Higher,No ChargeAccess Zero Brokerage Properties,NaN,2.0,0.0,1.0,kaggle,Mulund West,708.0,690.0,True,Semi Furnished,19774.011299,2,,
9254,3 BHK Flat,8.00,15.0,Ready to move,Lower,8.0 LacsAccess Zero Brokerage Properties,NaN,3.0,0.0,2.0,kaggle,Juhu,1700.0,1073.0,True,Unknown,47058.823529,3,,
9316,2 BHK Flat,4.50,15.0,Ready to move,Lower,4.5 LacsAccess Zero Brokerage Properties,NaN,2.0,0.0,2.0,kaggle,Juhu,800.0,690.0,True,Unknown,56250.000000,2,,
9787,1 BHK Flat,0.42,15.0,Ready to move,Lower,"80,000Access Zero Brokerage Properties",NaN,2.0,0.0,1.0,kaggle,Mira Road East,425.0,425.0,True,Semi Furnished,9882.352941,2,,
9888,3 BHK Flat,1.85,45.0,Ready to move,Higher,No ChargeAccess Zero Brokerage Properties,NaN,3.0,0.0,1.0,kaggle,Mulund West,1100.0,1073.0,True,Fully Furnished,16818.181818,4,,

In [240]:
import re

# Extract numeric value from flat_type for rows where bedrooms is NaN
mask = final_df['bedrooms'].isna()
final_df.loc[mask, 'bedrooms'] = final_df.loc[mask, 'flat_type'].str.extract(r'(\d+)').astype(float)[0]

# Final check for bedrooms null count
print(f"Missing values in bedrooms: {final_df['bedrooms'].isna().sum()}")

Missing values in bedrooms: 0

### Final Export
Exporting the fully cleaned and merged dataset to a final CSV file.

In [241]:
# Export the final unified dataframe
final_df.to_csv('final_cleaned_mumbai_real_estate_.csv', index=False)

print("Final dataset exported successfully as 'mumbai_real_estate_unified_cleaned.csv'")
print(f"Final record count: {len(final_df)}")

Final dataset exported successfully as 'mumbai_real_estate_unified_cleaned.csv'
Final record count: 11031