In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df1 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/real_estate_main.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/mumbai_flats.csv')

In [5]:
df1.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat in Kandivali West, Mumbai",Amity Global Business School (1.5 Km) [Univers...,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat in Vile Parle, Mumbai",Vile Parle Railway Station (0.8 km) [Railway S...,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat in Andheri East, Mumbai",JB Nagar Metro Station (4 mins) [Metro Station...,Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat in Chembur, Mumbai",St Gregorios Primary School (1.1 Km) [School] ...,"21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat in Govandi, Mumbai",National Highway 48 (1.9 Km) [Highway] | Chemb...,Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [6]:
df2.head()

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...
1,1 BHK Flat,19.0 L,"Ananta Vardhman Nagar, Tembhode, Palghar, Mumbai",630 sq.ft,₹3.02 K/sq.ft,3 Year Old,Ready to move,Middleof 4 floors,Unfurnished,NaN,Ananta Vardhman Nagar,No ChargeAccess Zero Brokerage Properties,390 sq.ft,1,1,2,1 Open Parking,"1 BHK Flat for sale in Palghar, Mumbai - conta..."
2,1 BHK Flat,73.0 L,"JP North Barcelona, Kashimira, Mira Road East,...",580 sq.ft,₹12.59 K/sq.ft,1 Years Old,Ready to move,Lowerof 25 floors,Semi Furnished,NaN,JP North Barcelona,1.5 LacsAccess Zero Brokerage Properties,475 sq.ft,1,2,2,No Parking,1 BHK Flat for sale in Mumbai. This property i...
3,1 BHK Flat,1.1 Cr,"Chandak Nischay, Ambawadi, Dahisar East, Mumbai",410 sq.ft,₹26.83 K/sq.ft,1 Years Old,Ready to move,Higherof 35 floors,Semi Furnished,NaN,Chandak Nischay,1.1 LacsAccess Zero Brokerage Properties,368 sq.ft,1,2,1,2 Covered Parking,Check out this 1 BHK Flat for sale in Dahisar ...
4,3 BHK Flat,2.25 Cr,"Neelam Solstice Phase I, Nalanda Nagar, Ramaba...",1052 sq.ft,₹21.39 K/sq.ft,1 Years Old,Ready to move,Lowerof 26 floors,Semi Furnished,NaN,Neelam Solstice Phase I,2.1 LacsAccess Zero Brokerage Properties,915 sq.ft,3,2,3,1 Covered Parking,"Situated in ghatkopar east, central mumbai sub..."

In [7]:
df1['NearbyLocations'].isna().value_counts()

NearbyLocations
False    437
True      66
Name: count, dtype: int64

In [8]:
df1.drop(columns='NearbyLocations', inplace=True)

In [9]:
df1.sample(5)

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
95,Runwal Auris,"3, 4 BHK Flat in Kanchpada, Malad West",6th-tallest tower in india | Connected to West...,https://www.99acres.com/runwal-auris-kanchpada...,Rs. 4.99 - 7.78 Cr,Spa | Park / Garden
179,Rustomjee Ashiana,"3, 4 BHK Flat in Juhu, Mumbai",Rustomjee Ashiana offers a plush living experi...,https://www.99acres.com/rustomjee-ashiana-juhu...,Rs. 10.37 - 15.25 Cr,Pet Area
154,Naman Habitat,"2, 3 BHK Flat in Andheri West, Mumbai",Exclusive low-density development with spaciou...,https://www.99acres.com/naman-habitat-andheri-...,Rs. 3.18 - 4.7 Cr,Pet Area | Spa | Vaastu Compliant
393,Lodha Woods,"2, 3, 4 BHK Flat in Kandivali East, Mumbai",Spread over ~5 acres of greens with global lif...,https://www.99acres.com/lodha-woods-kandivali-...,Rs. 2.04 - 4.38 Cr,Pet Area | Park / Garden | Spa
257,Priyam Residency,"1 BHK Flat in Malad West, Mumbai",Exclusive low-density living with only 4 units...,https://www.99acres.com/priyam-residency-malad...,Rs. 86.88 - 95.28 L,Park / Garden | Jogging Track

In [10]:
df1.columns= df1.columns.str.strip().str.lower().str.replace(' ', '_')

In [11]:
df1['propertysubname'].isna().value_counts()

propertysubname
False    503
Name: count, dtype: int64

In [12]:
df1['propertysubname'] = df1['propertysubname'].str.split("in").str.get(0)

In [13]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [43]:
# Clean the list by stripping whitespace and removing empty strings
df1['bhk_list'] = df1['propertysubname'].str.replace(" BHK Flat","").str.strip().str.split(",")
display(df1[['propertysubname','bhk_list']].head())

     propertysubname     bhk_list
0  1, 2, 3 BHK Flat   [1,  2,  3]
1  2, 3, 4 BHK Flat   [2,  3,  4]
2     1, 2 BHK Flat       [1,  2]
3  2, 3, 4 BHK Flat   [2,  3,  4]
4     1, 2 BHK Flat       [1,  2]

In [49]:
df1['bhk_list'].value_counts()

bhk_list
[2,  3]                    125
[1,  2]                     86
[1,  2,  3]                 61
[2,  3,  4]                 53
[2]                         35
[3,  4]                     33
[1,  2,  3,  4]             19
[3]                         17
[3,  4,  5]                 15
[1]                         14
[4]                         11
[2,  3,  4,  5]             10
[4,  5]                      4
[2,  4]                      3
[3,  4,  5,  6]              3
[4,  6]                      2
[3,  4,  6]                  2
[1,  3]                      1
[2,  3,  4,  5,  6,  7]      1
[5]                          1
[2,  3,  4,  5,  6]          1
[5,  6,  7]                  1
[1,  2,  3,  4,  5]          1
[1,  3,  4]                  1
[3,  5]                      1
[1,  2,  4]                  1
[2,  3,  5]                  1
Name: count, dtype: int64

In [67]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]"
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]"
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]"
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]"
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]"

In [153]:
def isL(text):

  cleaned = text.replace("Rs. ","").strip().replace(" Cr","").split(" - ")

  if len(cleaned) == 1:
    cleaned.append(cleaned[0])

  if "L" in text:

    if "L" in cleaned[0]:
      cleaned[0] = cleaned[0].replace("L", "").strip()
      cleaned[0] = round(float(cleaned[0])/100,2)

    if "L" in cleaned[1]:
      # Fixed: update cleaned[1] here, not [0] again
      cleaned[1] = cleaned[1].replace("L", "").strip()
      cleaned[1] = round(float(cleaned[1])/100,2)

  # Minimal change: Ensure values are explicitly cast to float
  return [float(cleaned[0]), float(cleaned[1])]

df1[['min_price', 'max_price']] = df1['pricedetails'].apply(isL).tolist()

In [123]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.5,6.91
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]",1.49,2.21
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]",3.38,8.97
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]",0.83,1.39

In [157]:
new_data = []

for i in range(len(df1)):
  text = df1.loc[i, 'propertysubname']
  bhk_list = text.replace(" BHK Flat","").strip().split(", ")

  prices = list(np.linspace(
          df1.loc[i,'min_price'],
          df1.loc[i,'max_price'],
          len(bhk_list)
      ).round(2))

  for bhk, price in zip(bhk_list, prices):
    new_row = df1.loc[i].copy()
    new_row['propertysubname'] = str(bhk) + " BHK Flat"
    new_row['pricedetails'] = round(price, 2)
    new_data.append(new_row)

new_df = pd.DataFrame(new_data)
new_df

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,3 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,3.22,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,2 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,3.50,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
1,Romell Espalier,3 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,5.20,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
...,...,...,...,...,...,...,...,...,...
500,Samarpan Anuraj CHS,2 BHK Flat,Scenic views of Sanjay Gandhi National Park | ...,https://www.99acres.com/samarpan-anuraj-chs-bo...,1.92,Pet Area | Park / Garden | Vaastu Compliant,"[1, 2]",1.30,1.92
501,Balaji Heights,1 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,1.25,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
501,Balaji Heights,2 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,2.15,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
502,Truearth Vedaa,1 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,0.75,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25
502,Truearth Vedaa,2 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,1.25,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25

In [163]:
new_df.drop(columns=['bhk_list',	'min_price',	'max_price'], inplace=True)

In [167]:
# Exporting the processed dataframe to a CSV file
new_df.to_csv('cleaned_multiple_BHK_real_estate.csv', index=False)