In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
new_df = pd.read_csv('/content/drive/MyDrive/Machine Learning/Projects/Real Estate Capstone Project/DataSets/new_properties.csv')
new_df.head()

/tmp/ipykernel_566/3577846626.py:1: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  new_df = pd.read_csv('/content/drive/MyDrive/Machine Learning/Projects/Real Estate Capstone Project/DataSets/new_properties.csv')

,ID,Possession Status,Availability Starts From,Floor No,Commercial,Developer,Approved Authority Name,Units Available,Price,Price (English),Flooring Type,Electricity Status,Maintenance Type,Maintenance Charges,Booking Amount,Landmark,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Property Uniqueness,Unit of Carpet Area,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Floor Data,Type of Property,City,bedroom,Data Referred From,floors,Water Status,Luxury Flat,Covered Area.1,Carpet Area Unit,isPrimeLocationProperty,Tenants Preference,Location,Property,covArea Unit,isLuxuryServiceProvided,Property Lifespan,balconies,Rera,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,Possession By,NRI Pref,Land Area / Covered Area,Land Area Unit,Pantry Type
0,12685,Under Construction,Dec '25,5,N,NaN,KDMC,1.0,3150000.0,31.5 Lac,Vitrified,No/Rare Powercut,Per sq. Unit Monthly,3.0,100000.0,Kalyan West Bapgaon,635.0,NaN,4960.0,375.0,Kalyan West,NaN,Sq-ft,Y,Freehold,Unfurnished,2.0,1 Covered,East,"Garden/Park, Pool",New Property,5 of 14 Floor,Apartment,Thane,1,Agent,14.0,Water Availability 24 Hours Available,F,635,Sq-ft,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,Sq-ft,0,NaN,2.0,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
1,12684,Ready to Move,NaN,20,Y,TATA Housing Development Company Ltd.,TMC,10.0,6300000.0,63 Lac,Vitrified,No/Rare Powercut,Per sq. Unit Monthly,3.0,100000.0,Rajoli naka,579.0,Tata Amantra,10880.0,579.0,Kalyan West,NaN,Sq-ft,Y,Freehold,Unfurnished,2.0,1 Covered,East,Main Road,New Property,20 of 34 Floor,Apartment,Thane,2,Agent,34.0,Water Availability 24 Hours Available,F,579,Sq-ft,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,Sq-ft,0,New Construction,NaN,Y,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
2,12683,Ready to Move,NaN,18,N,Sai Satyam Developers,KDMC,0.0,5400000.0,54 Lac,Vitrified,No/Rare Powercut,Monthly,1200.0,100000.0,This property has reputed scholl ints vicinity.,850.0,Sai Satyam Homes,6352.0,585.0,Kalyan West,East Facing Property,Sq-ft,Y,Freehold,Unfurnished,2.0,1 Open,East,"Garden/Park, Main Road",New Property,18 of 18 Floor,Apartment,Thane,2,Agent,18.0,Water Availability 24 Hours Available,F,850,Sq-ft,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,Sq-ft,0,New Construction,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,Y,NaN,NaN,NaN
3,12682,Under Construction,Dec '25,5,N,Birla Estates,KDMC,70.0,9000000.0,90 Lac,Vitrified,No/Rare Powercut,Monthly,3200.0,100000.0,Shahad is one of the attractive locations to o...,1050.0,Birla Vanya,8571.0,815.0,Kalyan West,NaN,Sq-ft,Y,Freehold,Unfurnished,2.0,"1 Covered, 1 Open",East,"Pool, Garden/Park, Main Road",New Property,5 of 27 Floor,Apartment,Thane,2,Agent,27.0,Water Availability 24 Hours Available,F,1050,Sq-ft,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,Sq-ft,0,NaN,3.0,Y,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
4,12681,Under Construction,Dec '24,8,Y,Godrej Properties,NaN,NaN,4950000.0,49.5 Lac,NaN,NaN,NaN,NaN,500000.0,majiwada metro station,561.0,Godrej Nirvaan,8824.0,419.0,Kalyan West,NaN,Sq-ft,Y,Freehold,Semi-Furnished,2.0,NaN,East,Garden/Park,New Property,8 of 26 Floor,Apartment,Thane,1,Agent,26.0,NaN,F,561,Sq-ft,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,Sq-ft,0,NaN,NaN,Y,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN

In [4]:
new_df.drop(
columns=[
'ID',
'Data Referred From',
'Approved Authority Name',
'Landmark',
'Availability Starts From',
'Booking Amount',
'Maintenance Charges',
'Maintenance Type',
'Unit of Carpet Area',
'covArea Unit',
'Carpet Area Unit',
'Price (English)',
'Commercial',
'City',
'Rera',
'Possession By',
'NRI Pref',
'Land Area / Covered Area',
'Land Area Unit',
'Pantry Type'
], inplace=True)

In [5]:
new_df.shape

(12685, 125)

In [6]:
new_df.head()

,Possession Status,Floor No,Developer,Units Available,Price,Flooring Type,Electricity Status,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Property Uniqueness,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Floor Data,Type of Property,bedroom,floors,Water Status,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden
0,Under Construction,5,NaN,1.0,3150000.0,Vitrified,No/Rare Powercut,635.0,NaN,4960.0,375.0,Kalyan West,NaN,Y,Freehold,Unfurnished,2.0,1 Covered,East,"Garden/Park, Pool",New Property,5 of 14 Floor,Apartment,1,14.0,Water Availability 24 Hours Available,F,635,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,NaN,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,Ready to Move,20,TATA Housing Development Company Ltd.,10.0,6300000.0,Vitrified,No/Rare Powercut,579.0,Tata Amantra,10880.0,579.0,Kalyan West,NaN,Y,Freehold,Unfurnished,2.0,1 Covered,East,Main Road,New Property,20 of 34 Floor,Apartment,2,34.0,Water Availability 24 Hours Available,F,579,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,Ready to Move,18,Sai Satyam Developers,0.0,5400000.0,Vitrified,No/Rare Powercut,850.0,Sai Satyam Homes,6352.0,585.0,Kalyan West,East Facing Property,Y,Freehold,Unfurnished,2.0,1 Open,East,"Garden/Park, Main Road",New Property,18 of 18 Floor,Apartment,2,18.0,Water Availability 24 Hours Available,F,850,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,Under Construction,5,Birla Estates,70.0,9000000.0,Vitrified,No/Rare Powercut,1050.0,Birla Vanya,8571.0,815.0,Kalyan West,NaN,Y,Freehold,Unfurnished,2.0,"1 Covered, 1 Open",East,"Pool, Garden/Park, Main Road",New Property,5 of 27 Floor,Apartment,2,27.0,Water Availability 24 Hours Available,F,1050,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,NaN,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,Under Construction,8,Godrej Properties,NaN,4950000.0,NaN,NaN,561.0,Godrej Nirvaan,8824.0,419.0,Kalyan West,NaN,Y,Freehold,Semi-Furnished,2.0,NaN,East,Garden/Park,New Property,8 of 26 Floor,Apartment,1,26.0,NaN,F,561,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [7]:
new_df.describe()

,Units Available,Price,Covered Area,sqft Price,Carpet Area,Bathroom,bedroom,floors,isLuxuryServiceProvided,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden
count,6135.000000,1.260100e+04,11374.000000,1.148000e+04,10133.000000,12616.000000,12685.000000,11819.000000,12685.0,5762.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.00000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000,12685.000000
mean,7.751589,2.640261e+07,1037.746439,2.243507e+04,819.201224,2.143389,1.987150,18.272697,0.0,1.925200,0.644777,0.733071,0.604020,0.616003,0.603863,0.627592,0.652582,0.667875,0.722428,0.644225,0.562870,0.636579,0.598896,0.607016,0.636973,0.633189,0.646906,0.631376,0.583051,0.611431,0.606937,0.577769,0.578321,0.552148,0.558849,0.564683,0.612771,0.602523,0.566102,0.535751,0.538195,0.540481,0.539141,0.537170,0.537328,0.538195,0.537958,0.536066,0.535987,0.536066,0.536145,0.537012,0.537406,0.537012,0.536776,0.538195,0.535909,0.535909,0.538747,0.538274,0.536618,0.537958,0.542925,0.535987,0.536539,0.541585,0.536618,0.538904,0.543004,0.536697,0.537170,0.537406,0.537406,0.539141,0.535909,0.536697,0.536460,0.477887,0.511707,0.514072,0.453764,0.537091,0.536460,0.537564,0.536303,0.538037,0.54119,0.537091,0.539693,0.544028,0.537091,0.537485,0.540402,0.540323,0.536539,0.536855,0.537958,0.540166,0.544028,0.536382
std,26.335448,3.653648e+08,727.327389,3.187654e+05,585.037811,0.926965,0.943404,14.436397,0.0,1.077033,0.478600,0.442373,0.489079,0.486376,0.489113,0.483465,0.476169,0.470994,0.447819,0.478766,0.496051,0.481004,0.490141,0.488433,0.480892,0.481953,0.477951,0.482451,0.493074,0.487444,0.488450,0.493934,0.493847,0.497293,0.496544,0.495818,0.487136,0.489396,0.495631,0.498740,0.498559,0.498378,0.498485,0.498636,0.498624,0.498559,0.498577,0.498717,0.498723,0.498717,0.498711,0.498648,0.498618,0.498648,0.498665,0.498559,0.498729,0.498729,0.498516,0.498553,0.498677,0.498577,0.498174,0.498723,0.498683,0.498287,0.498677,0.498504,0.498167,0.498671,0.498636,0.498618,0.498618,0.498485,0.498729,0.498671,0.498689,0.499530,0.499883,0.499822,0.497877,0.498642,0.498689,0.498607,0.498700,0.498571,0.49832,0.498642,0.498442,0.498077,0.498642,0.498613,0.498385,0.498391,0.498683,0.498660,0.498577,0.498404,0.498077,0.498694
min,0.000000,1.000000e+05,10.000000,0.000000e+00,2.000000,1.000000,1.000000,1.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,7.000000e+06,605.500000,1.000000e+04,468.000000,2.000000,1.000000,7.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.350000e+07,850.000000,1.634850e+04,671.000000,2.000000,2.000000,15.000000,0.0,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,5.000000,2.550000e+07,1200.000000,2.461500e+04,950.000000,2.000000,3.000000,24.000000,0.0,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,750.000000,4.080000e+10,15006.000000,3.400000e+07,20870.000000,10.000000,6.000000,200.000000,0.0,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12685 entries, 0 to 12684
Columns: 125 entries, Possession Status to Aesthetically designed landscape garden
dtypes: float64(8), int64(92), object(25)
memory usage: 12.1+ MB

In [9]:
pd.set_option('display.max_rows', None)

## Nan value counts

In [10]:
new_df.isna().sum()

Possession Status                            78
Floor No                                    858
Developer                                  5679
Units Available                            6550
Price                                        84
Flooring Type                              4534
Electricity Status                         5425
Covered Area                               1311
Project Name                               4531
sqft Price                                 1205
Carpet Area                                2552
Area Name                                     0
Property Uniqueness                        8025
Society                                       0
Ownership Type                             3260
furnished Type                               77
Bathroom                                     69
Parking                                    6159
Facing                                     3569
Amenities Facing                           4099
Transaction Type                              0
Floor Data                                  858
Type of Property                              0
bedroom                                       0
floors                                      866
Water Status                               5396
Luxury Flat                                   0
Covered Area.1                             1311
isPrimeLocationProperty                       0
Tenants Preference                            0
Location                                    323
Property                                    323
isLuxuryServiceProvided                       0
Property Lifespan                          4812
balconies                                  6923
Power Back Up                                 0
Lift                                          0
Rain Water Harvesting                         0
Club House                                    0
Swimming Pool                                 0
Gymnasium                                     0
Park                                          0
Parking.1                                     0
Security                                      0
Water Storage                                 0
Private Terrace/Garden                        0
Vaastu Compliant                              0
Service/Goods Lift                            0
Air Conditioned                               0
Visitor Parking                               0
Intercom Facility                             0
Maintenance Staff                             0
Waste Disposal                                0
Laundry Service                               0
Internet/Wi-Fi Connectivity                   0
DTH Television Facility                       0
RO Water System                               0
Banquet Hall                                  0
Bar/Lounge                                    0
Cafeteria/Food Court                          0
Conference Room                               0
Piped Gas                                     0
Jogging and Strolling Track                   0
Outdoor Tennis Courts                         0
Mansion                                       0
Downtown                                      0
Skyline View                                  0
Wrap Around Balcony                           0
Island Kitchen Layout                         0
Full Glass Wall                               0
House help accommodation                      0
Concierge Services                            0
Garden View                                   0
Marble flooring                               0
Well Furnished                                0
Modular Kitchen                               0
Helipad                                       0
Private pool                                  0
Private Jaccuzi                               0
Mini Cinema Theatre                           0
Golf Course                                   0
Infinity Swimming Pool                        0
Pool with temperature control                 0
Sea facing                                    0
Skydeck                                       0
Earth quake resistant                         0
Theme based Architectures                     0
Health club with Steam / Jaccuzi              0
Large Clubhouse                               0
Large Open space                              0
Fingerprint Access                            0
Grand Entrance lobby                          0
Private Garage                                0
Fireplace                                     0
Wine Cellar                                   0
Sky Villa                                     0
Water Front                                   0
Hilltop                                       0
Smart Home                                    0
Barbeque space                                0
Kids play area                                0
Library                                       0
Puja Room                                     0
Study                                         0
Servant Room                                  0
Store                                         0
Aerobics Room                                 0
Canopy Walk                                   0
Coffee Lounge & Restaurants                   0
Dance Studio                                  0
Event Space & Amphitheatre                    0
Flower Gardens                                0
Guest Accommodation                           0
Indoor Squash & Badminton Courts              0
Kids Play Area                                0
Kids Play Pool With Water Slides              0
Library And Business Centre                   0
Meditation Area                               0
Multipurpose Courts                           0
Recreational Pool                             0
Rentable CommuniPfty Space                    0
Retail Boulevard (Retail Shops)               0
Cycling & Jogging Track                       0
Fire Fighting Equipment                       0
Aesthetically designed landscape garden       0
dtype: int64

In [11]:
new_df.nunique()

Possession Status                            21
Floor No                                     70
Developer                                   942
Units Available                              82
Price                                      1251
Flooring Type                               202
Electricity Status                            4
Covered Area                               1359
Project Name                               2337
sqft Price                                 5608
Carpet Area                                1186
Area Name                                   357
Property Uniqueness                         462
Society                                       2
Ownership Type                                4
furnished Type                                3
Bathroom                                      8
Parking                                      83
Facing                                        8
Amenities Facing                             13
Transaction Type                              5
Floor Data                                 1298
Type of Property                              5
bedroom                                       6
floors                                       83
Water Status                                  5
Luxury Flat                                   1
Covered Area.1                             1897
isPrimeLocationProperty                       2
Tenants Preference                            2
Location                                    365
Property                                      6
isLuxuryServiceProvided                       1
Property Lifespan                             6
balconies                                     8
Power Back Up                                 2
Lift                                          2
Rain Water Harvesting                         2
Club House                                    2
Swimming Pool                                 2
Gymnasium                                     2
Park                                          2
Parking.1                                     2
Security                                      2
Water Storage                                 2
Private Terrace/Garden                        2
Vaastu Compliant                              2
Service/Goods Lift                            2
Air Conditioned                               2
Visitor Parking                               2
Intercom Facility                             2
Maintenance Staff                             2
Waste Disposal                                2
Laundry Service                               2
Internet/Wi-Fi Connectivity                   2
DTH Television Facility                       2
RO Water System                               2
Banquet Hall                                  2
Bar/Lounge                                    2
Cafeteria/Food Court                          2
Conference Room                               2
Piped Gas                                     2
Jogging and Strolling Track                   2
Outdoor Tennis Courts                         2
Mansion                                       2
Downtown                                      2
Skyline View                                  2
Wrap Around Balcony                           2
Island Kitchen Layout                         2
Full Glass Wall                               2
House help accommodation                      2
Concierge Services                            2
Garden View                                   2
Marble flooring                               2
Well Furnished                                2
Modular Kitchen                               2
Helipad                                       2
Private pool                                  2
Private Jaccuzi                               2
Mini Cinema Theatre                           2
Golf Course                                   2
Infinity Swimming Pool                        2
Pool with temperature control                 2
Sea facing                                    2
Skydeck                                       2
Earth quake resistant                         2
Theme based Architectures                     2
Health club with Steam / Jaccuzi              2
Large Clubhouse                               2
Large Open space                              2
Fingerprint Access                            2
Grand Entrance lobby                          2
Private Garage                                2
Fireplace                                     2
Wine Cellar                                   2
Sky Villa                                     2
Water Front                                   2
Hilltop                                       2
Smart Home                                    2
Barbeque space                                2
Kids play area                                2
Library                                       2
Puja Room                                     2
Study                                         2
Servant Room                                  2
Store                                         2
Aerobics Room                                 2
Canopy Walk                                   2
Coffee Lounge & Restaurants                   2
Dance Studio                                  2
Event Space & Amphitheatre                    2
Flower Gardens                                2
Guest Accommodation                           2
Indoor Squash & Badminton Courts              2
Kids Play Area                                2
Kids Play Pool With Water Slides              2
Library And Business Centre                   2
Meditation Area                               2
Multipurpose Courts                           2
Recreational Pool                             2
Rentable CommuniPfty Space                    2
Retail Boulevard (Retail Shops)               2
Cycling & Jogging Track                       2
Fire Fighting Equipment                       2
Aesthetically designed landscape garden       2
dtype: int64

In [12]:
new_df.drop(columns=[
  'Property Uniqueness',
'Units Available',
'Developer',
'Electricity Status',
'Water Status',
'Possession Status'
], inplace=True)

In [13]:
new_df.head()

,Floor No,Price,Flooring Type,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Floor Data,Type of Property,bedroom,floors,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden
0,5,3150000.0,Vitrified,635.0,NaN,4960.0,375.0,Kalyan West,Y,Freehold,Unfurnished,2.0,1 Covered,East,"Garden/Park, Pool",New Property,5 of 14 Floor,Apartment,1,14.0,F,635,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,NaN,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,20,6300000.0,Vitrified,579.0,Tata Amantra,10880.0,579.0,Kalyan West,Y,Freehold,Unfurnished,2.0,1 Covered,East,Main Road,New Property,20 of 34 Floor,Apartment,2,34.0,F,579,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,18,5400000.0,Vitrified,850.0,Sai Satyam Homes,6352.0,585.0,Kalyan West,Y,Freehold,Unfurnished,2.0,1 Open,East,"Garden/Park, Main Road",New Property,18 of 18 Floor,Apartment,2,18.0,F,850,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,5,9000000.0,Vitrified,1050.0,Birla Vanya,8571.0,815.0,Kalyan West,Y,Freehold,Unfurnished,2.0,"1 Covered, 1 Open",East,"Pool, Garden/Park, Main Road",New Property,5 of 27 Floor,Apartment,2,27.0,F,1050,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,NaN,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,8,4950000.0,NaN,561.0,Godrej Nirvaan,8824.0,419.0,Kalyan West,Y,Freehold,Semi-Furnished,2.0,NaN,East,Garden/Park,New Property,8 of 26 Floor,Apartment,1,26.0,F,561,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [14]:
pd.reset_option('display.max_rows')

In [15]:
new_df[new_df['floors'].isna()]

,Floor No,Price,Flooring Type,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Floor Data,Type of Property,bedroom,floors,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden
57,NaN,2500000.0,NaN,620.0,NaN,4032.0,NaN,Kalyan West,Y,NaN,Furnished,2.0,NaN,NaN,NaN,Resale,NaN,Residential House,2,NaN,F,620,Y,Bachelors/Family,NaN,NaN,0,Less than 5 years,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
86,NaN,4499000.0,NaN,NaN,Tycoons Square,NaN,421.0,Kalyan West,N,NaN,Unfurnished,2.0,1 Covered,NaN,NaN,New Property,NaN,Apartment,1,NaN,F,NaN,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
113,NaN,15000000.0,NaN,1600.0,NaN,9375.0,NaN,Kalyan West,N,NaN,Semi-Furnished,2.0,NaN,NaN,NaN,Resale,NaN,Residential House,2,NaN,F,1600,Y,Bachelors/Family,NaN,NaN,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
266,NaN,2715125.0,NaN,545.0,Mali Pinnacle,4982.0,376.0,Kalyan East,N,NaN,Unfurnished,1.0,1 Open,NaN,NaN,New Property,NaN,Apartment,1,NaN,F,545,Y,Bachelors/Family,"Kalyan East, Thane",1 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
370,NaN,19500000.0,Ceramic Tiles,1000.0,Oshiwara mhada,17500.0,750.0,Oshiwara,Y,Co-operative Society,Semi-Furnished,2.0,1 Open,North,"Garden/Park, Main Road",Resale,NaN,Apartment,2,NaN,F,1000,Y,Bachelors/Family,"Oshiwara, Mumbai",2 BHK Flat,0,10 to 15 years,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12676,NaN,14600000.0,Vitrified,NaN,Arkade Prime,NaN,575.0,Andheri East,N,NaN,Unfurnished,2.0,NaN,NaN,NaN,New Property,NaN,Apartment,2,NaN,F,NaN,Y,Bachelors/Family,"Andheri East, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12677,NaN,11000000.0,Vitrified,NaN,Arkade Prime,NaN,415.0,Andheri East,N,NaN,Unfurnished,2.0,NaN,NaN,NaN,New Property,NaN,Apartment,1,NaN,F,NaN,Y,Bachelors/Family,"Andheri East, Mumbai",1 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12678,NaN,20922633.0,"Vitrified,Wooden,Marble",996.0,Hillcrest,21007.0,NaN,Andheri East,N,NaN,Unfurnished,2.0,NaN,NaN,NaN,New Property,NaN,Apartment,3,NaN,F,996.0,Y,Bachelors/Family,"Andheri East, Mumbai",3 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12679,NaN,18709662.0,"Vitrified,Wooden,Marble",891.0,Hillcrest,20998.0,NaN,Andheri East,N,NaN,Unfurnished,2.0,NaN,NaN,NaN,New Property,NaN,Apartment,2,NaN,F,891.0,Y,Bachelors/Family,"Andheri East, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12680,NaN,22200000.0,Vitrified,NaN,Kalpataru Vivant,NaN,618.0,Jogeshwari Vikhroli Link Road,N,NaN,Unfurnished,2.0,1 Covered,NaN,NaN,New Property,NaN,Apartment,2,NaN,F,NaN,Y,Bachelors/Family,"Jogeshwari Vikhroli Link Road, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
non_numeric_floors = new_df[pd.to_numeric(new_df['Floor No'], errors='coerce').isna() & new_df['Floor No'].notna()]
display("Rows with non-numeric Floor No:")
display(non_numeric_floors[['Floor No']].head())

'Rows with non-numeric Floor No:'

           Floor No
98           Ground
128          Ground
146          Ground
179          Ground
199  Upper Basement

In [17]:
new_df[new_df.index==199]

,Floor No,Price,Flooring Type,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Floor Data,Type of Property,bedroom,floors,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden
199,Upper Basement,6900000.0,"Marble,Vitrified",865.0,Godrej Upavan,7976.0,541.0,Kalyan West,Y,Freehold,Unfurnished,2.0,"1 Covered, 1 Open",East,"Garden/Park, Pool, Main Road",New Property,Upper Basement of 33 Floor,Apartment,2,33.0,F,865,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [18]:
floor_map = {
    'Ground': 0,
    'Upper Basement': -1,
}

new_df['Floor No'] = new_df['Floor No'].replace(floor_map)
new_df['Floor No'] = pd.to_numeric(new_df['Floor No'], errors='coerce')

display(new_df.loc[[199, 98, 128], ['Floor No', 'floors']])

     Floor No  floors
199      -1.0    33.0
98        0.0     7.0
128       0.0     5.0

In [19]:
new_df["floor_ratio"] = new_df["Floor No"] / new_df["floors"]

In [20]:
new_df.drop(columns = ['Floor No', 'floors', 'Floor Data'], inplace = True)

In [21]:
new_df['Price'] = round(new_df['Price']/10000000,2)

In [22]:
new_df['Price'].isna().sum()

np.int64(84)

In [23]:
new_df[new_df['Price'].isna()]

,Price,Flooring Type,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Type of Property,bedroom,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio
253,NaN,NaN,600.0,Sai Samarth,NaN,NaN,Kalyan East,Y,NaN,Unfurnished,1.0,1 Covered,NaN,NaN,Resale,Apartment,1,F,600,N,Bachelors/Family,"Kalyan East, Thane",1 BHK Flat,0,Less than 5 years,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.400000
405,NaN,NaN,250.0,NaN,NaN,NaN,Jogeshwari West,Y,NaN,NaN,NaN,NaN,NaN,NaN,Resale,Apartment,1,F,250,Y,Bachelors/Family,"Jogeshwari West, Mumbai",1 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
406,NaN,NaN,1550.0,NaN,NaN,NaN,Jogeshwari West,Y,NaN,NaN,NaN,NaN,NaN,NaN,Resale,Apartment,2,F,1550,Y,Bachelors/Family,"Jogeshwari West, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
794,NaN,NaN,651.0,Versatile Valley,NaN,NaN,Dombivli East,Y,NaN,Unfurnished,1.0,NaN,NaN,NaN,Resale,Apartment,1,F,651,N,Bachelors/Family,"Dombivli East, Thane",1 BHK Flat,0,NaN,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.473684
795,NaN,NaN,NaN,Lodha Codename Smart Buy,NaN,1987.0,Dombivli East,Y,NaN,Semi-Furnished,3.0,NaN,NaN,NaN,Resale,Apartment,3,F,NaN,N,Bachelors/Family,"Dombivli East, Thane",3 BHK Flat,0,NaN,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.285714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12055,NaN,NaN,750.0,Kanakia Sevens,NaN,NaN,Andheri East,Y,NaN,NaN,NaN,NaN,NaN,NaN,Resale,Apartment,2,F,750.0,N,Bachelors/Family,"Andheri East, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12056,NaN,NaN,225.0,Bindra Apartments,NaN,NaN,Andheri East,Y,NaN,Semi-Furnished,1.0,NaN,NaN,NaN,Resale,Residential House,1,F,225.0,N,Bachelors/Family,NaN,NaN,0,5 to 10 years,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12057,NaN,NaN,NaN,NaN,NaN,675.0,Marol,Y,NaN,Unfurnished,2.0,NaN,NaN,NaN,Resale,Apartment,2,F,NaN,N,Bachelors/Family,"Marol, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.714286
12058,NaN,Vitrified,NaN,Crescent Landmark,NaN,640.0,Marol,Y,Freehold,Semi-Furnished,NaN,1 Covered,East,Main Road,Resale,Apartment,2,F,NaN,N,Bachelors/Family,"Marol, Mumbai",2 BHK Flat,0,Less than 5 years,NaN,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.333333
12059,NaN,NaN,795.0,Kanakia Sevens,NaN,NaN,Andheri East,Y,NaN,NaN,NaN,NaN,NaN,NaN,Resale,Apartment,2,F,795.0,Y,Bachelors/Family,"Andheri East, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN

In [24]:
cols_to_check = ['Price', 'Carpet Area', 'Project Name']

missing_data_rows = new_df[new_df[cols_to_check].isna().all(axis=1)]
miss_index =  new_df[new_df[cols_to_check].isna().all(axis=1)].index
print(f"Total rows with all missing value in {cols_to_check}: {len(missing_data_rows)}")
display(missing_data_rows[cols_to_check].head())

print("\nMissing value count per column:")
print(new_df[cols_to_check].isna().sum())

Total rows with all missing value in ['Price', 'Carpet Area', 'Project Name']: 10

      Price  Carpet Area Project Name
405     NaN          NaN          NaN
406     NaN          NaN          NaN
797     NaN          NaN          NaN
1912    NaN          NaN          NaN
2256    NaN          NaN          NaN

Missing value count per column:
Price             84
Carpet Area     2552
Project Name    4531
dtype: int64

In [25]:
new_df.drop(index=miss_index, inplace=True)

In [26]:
new_df.drop(columns='Flooring Type', inplace=True)

In [27]:
new_df['Project Name'] = new_df['Project Name'].fillna("Unknown Project")

In [28]:
new_df.head()

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Type of Property,bedroom,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio
0,0.32,635.0,Unknown Project,4960.0,375.0,Kalyan West,Y,Freehold,Unfurnished,2.0,1 Covered,East,"Garden/Park, Pool",New Property,Apartment,1,F,635,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,NaN,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.357143
1,0.63,579.0,Tata Amantra,10880.0,579.0,Kalyan West,Y,Freehold,Unfurnished,2.0,1 Covered,East,Main Road,New Property,Apartment,2,F,579,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.588235
2,0.54,850.0,Sai Satyam Homes,6352.0,585.0,Kalyan West,Y,Freehold,Unfurnished,2.0,1 Open,East,"Garden/Park, Main Road",New Property,Apartment,2,F,850,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.000000
3,0.90,1050.0,Birla Vanya,8571.0,815.0,Kalyan West,Y,Freehold,Unfurnished,2.0,"1 Covered, 1 Open",East,"Pool, Garden/Park, Main Road",New Property,Apartment,2,F,1050,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,NaN,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.185185
4,0.50,561.0,Godrej Nirvaan,8824.0,419.0,Kalyan West,Y,Freehold,Semi-Furnished,2.0,NaN,East,Garden/Park,New Property,Apartment,1,F,561,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.307692

In [29]:
new_df['Covered Area'].isna().sum()

np.int64(1309)

In [30]:
new_df[new_df['Covered Area'].isna()][['Covered Area', 'Carpet Area']]

       Covered Area  Carpet Area
15              NaN        980.0
24              NaN        390.0
40              NaN        980.0
49              NaN        390.0
86              NaN        421.0
...             ...          ...
12675           NaN        615.0
12676           NaN        575.0
12677           NaN        415.0
12680           NaN        618.0
12683           NaN        821.0

[1309 rows x 2 columns]

In [31]:
new_df = new_df.dropna(subset=['Covered Area', 'Carpet Area'], how='all')

In [32]:
ratio_by_type = (
    new_df.groupby('Type of Property')
      .apply(lambda x: (x['Covered Area'] / x['Carpet Area']).median())
)

/tmp/ipykernel_566/3368424253.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: (x['Covered Area'] / x['Carpet Area']).median())

In [33]:
ratio_by_type

Type of Property
Apartment                  1.377391
Builder Floor Apartment    1.235294
Penthouse                  1.348485
Residential House          1.219093
Villa                      1.269231
dtype: float64

In [34]:
new_df['Type of Property'].map(ratio_by_type)

0        1.377391
1        1.377391
2        1.377391
3        1.377391
4        1.377391
           ...
12680    1.377391
12681    1.377391
12682    1.377391
12683    1.377391
12684    1.377391
Name: Type of Property, Length: 12664, dtype: float64

In [35]:
ratios = new_df['Type of Property'].map(ratio_by_type)
new_df['Covered Area'] = new_df['Covered Area'].fillna(ratios * new_df['Carpet Area'])

new_df['Covered Area'] = new_df['Covered Area'].round(2)
new_df['Covered Area'].isna().sum()

np.int64(0)

In [36]:
new_df.rename({'sqft Price ': 'sqft Price'}, axis=1, inplace=True)

new_df['sqft Price'].isna().sum()

np.int64(1184)

In [37]:
new_df['sqft Price'] = new_df['sqft Price'].fillna((new_df['Price'] * 10000000) / new_df['Covered Area'])
new_df['sqft Price'].isna().sum()

np.int64(67)

In [38]:
new_df[(new_df['sqft Price'].isna()) & (new_df['Price'].isna())].shape

(67, 116)

In [39]:
new_df.dropna(subset=['sqft Price'], inplace=True)

In [40]:
new_df['sqft Price'].isna().sum()

np.int64(0)

In [41]:
map = {'Y':1, 'N':0}
new_df['Society']= new_df['Society'].map(map)

In [42]:
new_df[new_df['Carpet Area'].isna()]

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Type of Property,bedroom,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio
12,0.49,595.0,Rosalie,8235.0,NaN,Kalyan West,0,Co-operative Society,Unfurnished,1.0,NaN,North - East,Main Road,New Property,Apartment,1,F,595,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.473684
37,0.49,595.0,Rosalie,8235.0,NaN,Kalyan West,0,Co-operative Society,Unfurnished,1.0,NaN,North - East,Main Road,New Property,Apartment,1,F,595,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.473684
55,0.24,675.0,Unknown Project,3556.0,NaN,Kalyan West,1,NaN,Unfurnished,2.0,NaN,NaN,NaN,Resale,Apartment,2,F,675,Y,Bachelors/Family,"Kalyan West, Thane",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000
56,0.20,605.0,Unknown Project,3306.0,NaN,Kalyan West,1,Freehold,Unfurnished,1.0,NaN,East,NaN,Resale,Apartment,1,F,605,Y,Bachelors/Family,"Kalyan West, Thane",1 BHK Flat,0,Less than 5 years,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.000000
57,0.25,620.0,Unknown Project,4032.0,NaN,Kalyan West,1,NaN,Furnished,2.0,NaN,NaN,NaN,Resale,Residential House,2,F,620,Y,Bachelors/Family,NaN,NaN,0,Less than 5 years,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12530,4.00,1250.0,Kanakia Rainforest,32000.0,NaN,Andheri East,0,Freehold,Semi-Furnished,4.0,3 Covered,East,Main Road,Resale,Apartment,4,F,1250.0,Y,Bachelors/Family,"Andheri East, Mumbai",4 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.800000
12569,1.91,1035.0,Blue Meadows,18454.0,NaN,Andheri East,0,Co-operative Society,Furnished,2.0,1 Open,North - West,"Pool, Garden/Park",Resale,Apartment,2,F,1035.0,Y,Bachelors/Family,"Andheri East, Mumbai",2 BHK Flat,0,NaN,NaN,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.727273
12660,4.25,1377.0,Oberoi Splendor,30864.0,NaN,Andheri East,1,Co-operative Society,Unfurnished,2.0,1 Covered,North,Garden/Park,Resale,Apartment,3,F,1377.0,Y,Bachelors/Family,"Andheri East, Mumbai",3 BHK Flat,0,10 to 15 years,2.0,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,1,1,0,0,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.185185
12678,2.09,996.0,Hillcrest,21007.0,NaN,Andheri East,0,NaN,Unfurnished,2.0,NaN,NaN,NaN,New Property,Apartment,3,F,996.0,Y,Bachelors/Family,"Andheri East, Mumbai",3 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12679,1.87,891.0,Hillcrest,20998.0,NaN,Andheri East,0,NaN,Unfurnished,2.0,NaN,NaN,NaN,New Property,Apartment,2,F,891.0,Y,Bachelors/Family,"Andheri East, Mumbai",2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN

In [43]:
new_df['Carpet Area'] = new_df['Carpet Area'].fillna(new_df['Covered Area']/ ratios)

In [44]:
new_df[new_df['Location'].isna()]

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,Ownership Type,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Type of Property,bedroom,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Location,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio
57,0.25,620.00,Unknown Project,4032.0,508.574890,Kalyan West,1,NaN,Furnished,2.0,NaN,NaN,NaN,Resale,Residential House,2,F,620,Y,Bachelors/Family,NaN,NaN,0,Less than 5 years,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
72,0.56,805.00,Vrindavan Garden,6957.0,660.327075,Kalyan West,0,NaN,Furnished,2.0,NaN,NaN,NaN,Resale,Residential House,2,F,805,N,Bachelors/Family,NaN,NaN,0,Less than 5 years,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.571429
113,1.50,1600.00,Unknown Project,9375.0,1312.451328,Kalyan West,0,NaN,Semi-Furnished,2.0,NaN,NaN,NaN,Resale,Residential House,2,F,1600,Y,Bachelors/Family,NaN,NaN,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
261,0.13,455.00,Unknown Project,2857.0,345.000000,Kalyan East,1,Freehold,Unfurnished,1.0,1 Covered,North - East,Main Road,Resale,Residential House,1,F,455,Y,Bachelors/Family,NaN,NaN,0,New Construction,2.0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.500000
627,0.38,180.00,Unknown Project,21111.0,180.000000,Indira Nagar,1,NaN,Semi-Furnished,1.0,NaN,NaN,NaN,Resale,Residential House,1,F,180,Y,Bachelors/Family,NaN,NaN,0,Above 20 years,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12417,9.50,7000.00,Unknown Project,13571.0,5000.000000,Sher E Punjab Society,0,Co-operative Society,Furnished,5.0,NaN,North,Garden/Park,Resale,Villa,6,F,7000.0,N,Bachelors/Family,NaN,NaN,0,Above 20 years,1.0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12431,2.25,1153.26,Dsk Madhuban,23784.0,946.000000,Sakinaka Junction,1,Co-operative Society,Semi-Furnished,2.0,1 Covered,North,Garden/Park,Resale,Residential House,3,F,NaN,N,Bachelors/Family,NaN,NaN,0,5 to 10 years,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.333333
12433,4.40,1600.00,Unknown Project,27500.0,1500.000000,Amboli,1,Freehold,Unfurnished,3.0,NaN,West,Main Road,Resale,Villa,2,F,1600.0,N,Bachelors/Family,NaN,NaN,0,Above 20 years,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN
12435,4.00,1728.00,Unknown Project,23148.0,1380.000000,Andheri East,0,Co-operative Society,Furnished,2.0,1 Covered,South,Garden/Park,Resale,Residential House,2,F,1728.0,Y,Bachelors/Family,NaN,NaN,0,Above 20 years,NaN,0,0,0,0,0,0,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.500000
12533,1.80,808.26,VKG Krishna Residences,27149.0,663.000000,Andheri East,1,Freehold,Unfurnished,2.0,2 Covered,North - East,"Pool, Main Road",New Property,Residential House,2,F,NaN,Y,Bachelors/Family,NaN,NaN,0,NaN,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.000000

In [45]:
new_df.drop(columns='Location', inplace=True)

In [46]:
new_df.drop(columns=['Ownership Type'], inplace=True)

In [47]:
new_df[~new_df['Parking'].str.contains('open|Covered', case=False, na=False)]

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Parking,Facing,Amenities Facing,Transaction Type,Type of Property,bedroom,Luxury Flat,Covered Area.1,isPrimeLocationProperty,Tenants Preference,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio
4,0.50,561.00,Godrej Nirvaan,8824.000000,419.000000,Kalyan West,1,Semi-Furnished,2.0,NaN,East,Garden/Park,New Property,Apartment,1,F,561,Y,Bachelors/Family,1 BHK Flat,0,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.307692
6,0.55,725.00,Unknown Project,7586.000000,550.000000,Kalyan West,0,Unfurnished,2.0,NaN,East,"Garden/Park, Main Road",Resale,Apartment,2,F,725,Y,Bachelors/Family,2 BHK Flat,0,15 to 20 years,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.142857
7,0.42,650.00,Unknown Project,6462.000000,585.000000,Kalyan West,0,Semi-Furnished,1.0,NaN,East,Main Road,Resale,Apartment,1,F,650,Y,Bachelors/Family,1 BHK Flat,0,5 to 10 years,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.500000
8,0.34,592.00,Godrej Riviera,5826.000000,370.000000,Kalyan West,1,Unfurnished,1.0,NaN,North - East,"Garden/Park, Main Road",New Property,Apartment,1,F,592,Y,Bachelors/Family,1 BHK Flat,0,NaN,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.727273
9,0.50,644.00,Unknown Project,7764.000000,430.000000,Kalyan West,0,Unfurnished,1.0,NaN,West,NaN,Resale,Apartment,1,F,644,Y,Bachelors/Family,1 BHK Flat,0,10 to 15 years,1.0,1,1,0,1,1,1,1,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12675,1.53,847.10,Romell Orbis,18061.622004,615.000000,Andheri East,0,Unfurnished,2.0,NaN,NaN,NaN,New Property,Apartment,2,F,NaN,Y,Bachelors/Family,2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12676,1.46,792.00,Arkade Prime,18434.343434,575.000000,Andheri East,0,Unfurnished,2.0,NaN,NaN,NaN,New Property,Apartment,2,F,NaN,Y,Bachelors/Family,2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12677,1.10,571.62,Arkade Prime,19243.553410,415.000000,Andheri East,0,Unfurnished,2.0,NaN,NaN,NaN,New Property,Apartment,1,F,NaN,Y,Bachelors/Family,1 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12678,2.09,996.00,Hillcrest,21007.000000,723.106061,Andheri East,0,Unfurnished,2.0,NaN,NaN,NaN,New Property,Apartment,3,F,996.0,Y,Bachelors/Family,3 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
12679,1.87,891.00,Hillcrest,20998.000000,646.875000,Andheri East,0,Unfurnished,2.0,NaN,NaN,NaN,New Property,Apartment,2,F,891.0,Y,Bachelors/Family,2 BHK Flat,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN

In [48]:
new_df['Parking'].value_counts(dropna=False).head(20)

Parking
NaN                  6091
1 Covered            2896
1 Open               1569
2 Covered             922
1 Covered, 1 Open     524
3 Covered             186
2 Open                102
4 Covered              59
2 Covered, 1 Open      33
2 Covered, 2 Open      19
3 Open                 16
10 Open                15
1 Covered, 2 Open      10
5 Covered               9
4 Open                  7
7 Open                  6
15 Open                 6
12 Covered              6
6 Open                  6
40 Open                 5
Name: count, dtype: int64

In [49]:
new_df['Parking_Status'] = np.where(
    new_df['Parking'].isna(),
    'Unknown',
    'Available'
)
new_df.drop(columns='Parking', inplace=True)

In [50]:
new_df['furnished Type'] = new_df['furnished Type'].fillna(new_df['furnished Type'].mode()[0])

In [51]:
new_df['Bathroom'] = new_df['Bathroom'].fillna(new_df.groupby('Property')['Bathroom'].transform('mean').round())

In [52]:
new_df['Facing'] = new_df['Facing'].fillna("Unknown")

In [53]:
new_df.drop('Amenities Facing', inplace=True, axis=1)

In [54]:
new_df['Transaction Type'].isna().sum()

np.int64(0)

In [55]:
new_df['Type of Property'].isna().sum()

np.int64(0)

In [56]:
new_df['bedroom'].isna().sum()

np.int64(0)

In [57]:
new_df['Luxury Flat'].isna().sum()

np.int64(0)

In [58]:
new_df.drop('Luxury Flat', axis=1, inplace=True)

In [59]:
new_df['isPrimeLocationProperty'].value_counts()

isPrimeLocationProperty
Y    9379
N    3218
Name: count, dtype: int64

In [60]:
new_df.drop('Covered Area.1', axis=1, inplace=True)

In [61]:
new_df.drop('Tenants Preference', axis=1, inplace=True)

In [62]:
missing_properties = new_df[new_df['Property'].isna()]['bedroom']

new_df['Property'].map(missing_properties)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
12680   NaN
12681   NaN
12682   NaN
12683   NaN
12684   NaN
Name: Property, Length: 12597, dtype: float64

In [63]:
new_df['Property'] = new_df['Property'].fillna(new_df['bedroom'])

print(f"Missing Property values: {new_df['Property'].isna().sum()}")
display(new_df[['bedroom', 'Property']].head())

Missing Property values: 0

   bedroom    Property
0        1  1 BHK Flat
1        2  2 BHK Flat
2        2  2 BHK Flat
3        2  2 BHK Flat
4        1  1 BHK Flat

In [64]:
new_df.head()

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,isLuxuryServiceProvided,Property Lifespan,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio,Parking_Status
0,0.32,635.0,Unknown Project,4960.0,375.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,1,Y,1 BHK Flat,0,NaN,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.357143,Available
1,0.63,579.0,Tata Amantra,10880.0,579.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,Y,2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.588235,Available
2,0.54,850.0,Sai Satyam Homes,6352.0,585.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,Y,2 BHK Flat,0,New Construction,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.000000,Available
3,0.90,1050.0,Birla Vanya,8571.0,815.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,Y,2 BHK Flat,0,NaN,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.185185,Available
4,0.50,561.0,Godrej Nirvaan,8824.0,419.0,Kalyan West,1,Semi-Furnished,2.0,East,New Property,Apartment,1,Y,1 BHK Flat,0,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.307692,Unknown

In [65]:
new_df['Property'] = new_df['Property'].str.split(" ").str.get(0)

In [66]:
new_df['Property'] = new_df['Property'].fillna(new_df['bedroom'])

new_df['Property'] = pd.to_numeric(new_df['Property'], errors='coerce').astype('Int64')


print(f"Remaining missing values in Property: {new_df['Property'].isna().sum()}")
display(new_df[['bedroom', 'Property']].head())

Remaining missing values in Property: 0

   bedroom  Property
0        1         1
1        2         2
2        2         2
3        2         2
4        1         1

In [67]:
new_df.drop('isLuxuryServiceProvided', axis=1, inplace=True)

In [68]:
new_df['balconies'].value_counts(dropna=False)

balconies
NaN    6862
1.0    2674
2.0    1452
3.0    1139
4.0     349
5.0      84
6.0      27
7.0       6
8.0       4
Name: count, dtype: int64

In [69]:
new_df['balconies'] = new_df['balconies'].fillna(new_df.groupby(['Project Name', 'bedroom'])['balconies'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan))

new_df['balconies'] = new_df['balconies'].fillna(new_df['bedroom'])

print(f"Remaining missing values in balconies: {new_df['balconies'].isna().sum()}")
display(new_df['balconies'].value_counts(dropna=False))

Remaining missing values in balconies: 0

balconies
1.0    7631
2.0    2695
3.0    1658
4.0     472
5.0     100
6.0      31
7.0       6
8.0       4
Name: count, dtype: int64

In [70]:
with pd.option_context('display.max_rows', None):
  print(new_df.isna().sum())

Price                                         0
Covered Area                                  0
Project Name                                  0
sqft Price                                    0
Carpet Area                                   0
Area Name                                     0
Society                                       0
furnished Type                                0
Bathroom                                      2
Facing                                        0
Transaction Type                              0
Type of Property                              0
bedroom                                       0
isPrimeLocationProperty                       0
Property                                      0
Property Lifespan                          4755
balconies                                     0
Power Back Up                                 0
Lift                                          0
Rain Water Harvesting                         0
Club House                                    0
Swimming Pool                                 0
Gymnasium                                     0
Park                                          0
Parking.1                                     0
Security                                      0
Water Storage                                 0
Private Terrace/Garden                        0
Vaastu Compliant                              0
Service/Goods Lift                            0
Air Conditioned                               0
Visitor Parking                               0
Intercom Facility                             0
Maintenance Staff                             0
Waste Disposal                                0
Laundry Service                               0
Internet/Wi-Fi Connectivity                   0
DTH Television Facility                       0
RO Water System                               0
Banquet Hall                                  0
Bar/Lounge                                    0
Cafeteria/Food Court                          0
Conference Room                               0
Piped Gas                                     0
Jogging and Strolling Track                   0
Outdoor Tennis Courts                         0
Mansion                                       0
Downtown                                      0
Skyline View                                  0
Wrap Around Balcony                           0
Island Kitchen Layout                         0
Full Glass Wall                               0
House help accommodation                      0
Concierge Services                            0
Garden View                                   0
Marble flooring                               0
Well Furnished                                0
Modular Kitchen                               0
Helipad                                       0
Private pool                                  0
Private Jaccuzi                               0
Mini Cinema Theatre                           0
Golf Course                                   0
Infinity Swimming Pool                        0
Pool with temperature control                 0
Sea facing                                    0
Skydeck                                       0
Earth quake resistant                         0
Theme based Architectures                     0
Health club with Steam / Jaccuzi              0
Large Clubhouse                               0
Large Open space                              0
Fingerprint Access                            0
Grand Entrance lobby                          0
Private Garage                                0
Fireplace                                     0
Wine Cellar                                   0
Sky Villa                                     0
Water Front                                   0
Hilltop                                       0
Smart Home                                    0
Barbeque space                                0
Kids play area                                0
Library                                       0
Puja Room                                     0
Study                                         0
Servant Room                                  0
Store                                         0
Aerobics Room                                 0
Canopy Walk                                   0
Coffee Lounge & Restaurants                   0
Dance Studio                                  0
Event Space & Amphitheatre                    0
Flower Gardens                                0
Guest Accommodation                           0
Indoor Squash & Badminton Courts              0
Kids Play Area                                0
Kids Play Pool With Water Slides              0
Library And Business Centre                   0
Meditation Area                               0
Multipurpose Courts                           0
Recreational Pool                             0
Rentable CommuniPfty Space                    0
Retail Boulevard (Retail Shops)               0
Cycling & Jogging Track                       0
Fire Fighting Equipment                       0
Aesthetically designed landscape garden       0
floor_ratio                                 875
Parking_Status                                0
dtype: int64

In [71]:
ratio_fill_map = new_df.groupby('Type of Property')['floor_ratio'].median()

new_df['floor_ratio'] = new_df['floor_ratio'].fillna(new_df['Type of Property'].map(ratio_fill_map))


remaining_nans = new_df['floor_ratio'].isna().sum()
if remaining_nans > 0:
    new_df['floor_ratio'] = new_df['floor_ratio'].fillna(new_df['floor_ratio'].median())

print(f"Remaining missing values in floor_ratio: {new_df['floor_ratio'].isna().sum()}")
display(new_df['floor_ratio'].describe())

Remaining missing values in floor_ratio: 0

count    12597.000000
mean         0.522242
std          0.277381
min         -1.000000
25%          0.313433
50%          0.512821
75%          0.727273
max          1.000000
Name: floor_ratio, dtype: float64

In [72]:
new_df.duplicated().sum()

np.int64(2652)

In [73]:
new_df.drop_duplicates(inplace=True)
new_df = new_df.reset_index(drop=True)
print(f"Duplicates removed. New shape: {new_df.shape}")

Duplicates removed. New shape: (9945, 109)

In [74]:
new_df.drop('Property Lifespan', inplace=True, axis=1)

In [75]:
new_df.to_csv('Cleaned RS Dataset.csv', index=False)

## Building Recommender System

In [76]:
new_df.head()

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio,Parking_Status
0,0.32,635.0,Unknown Project,4960.0,375.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,1,Y,1,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.357143,Available
1,0.63,579.0,Tata Amantra,10880.0,579.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,Y,2,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.588235,Available
2,0.54,850.0,Sai Satyam Homes,6352.0,585.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,Y,2,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.000000,Available
3,0.90,1050.0,Birla Vanya,8571.0,815.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,Y,2,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.185185,Available
4,0.50,561.0,Godrej Nirvaan,8824.0,419.0,Kalyan West,1,Semi-Furnished,2.0,East,New Property,Apartment,1,Y,1,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.307692,Unknown

In [77]:
num_cols = [
    'Price',
    'Covered Area',
    'sqft Price',
    'Carpet Area',
    'Bathroom',
    'bedroom',
    'balconies',
    'floor_ratio',
    'Property',
]

cat_cols = [
    # 'Project Name',
    'Area Name',
    'furnished Type',
    'Facing',
    'Transaction Type',
    'Type of Property',
    'Parking_Status'
]

binary_cols = [x for x in new_df.columns if x not in num_cols and x not in cat_cols]

In [78]:
filter_cols = [
    'Project Name',
    'Area Name',
    'property',
    'Type of Property',
    'furnished Type'
]

In [79]:
popular_amenities = [
    'Swimming Pool',
    'Gymnasium',
    'Club House',
    'Park',
    'Security',
    'Lift',
    'Power Back Up',
    'Visitor Parking',
    'Piped Gas',
    'Society'
]

luxury_amenities = [
    'Sea facing',
    'Skydeck',
    'Private pool ',
    'Private Jaccuzi',
    'Infinity Swimming Pool',
    'Smart Home',
    'Wine Cellar',
    'Sky Villa',
    'Private Terrace/Garden',
    'Helipad',
    'Golf Course',
    'Mini Cinema Theatre',
    'Concierge Services',
    'Health club with Steam / Jaccuzi',
    'Servant Room',
    'Island Kitchen Layout',
    'Wrap Around Balcony'
]

family_amenities = [
    'Kids play area',
    'Kids Play Pool With Water Slides',
    'Library',
    'Puja Room',
    'Flower Gardens',
    'Aesthetically designed landscape garden',
    'Jogging and Strolling Track',
    'Cycling & Jogging Track',
    'Multipurpose Courts',
    'Indoor Squash & Badminton Courts',
    'Cafeteria/Food Court',
    'Banquet Hall'
]

hidden_amenities = [
    'Rain Water Harvesting',
    'Water Storage',
    'Intercom Facility',
    'Maintenance Staff',
    'Waste Disposal',
    'Fire Fighting Equipment',
    'Internet/Wi-Fi Connectivity',
    'DTH Television Facility',
    'Air Conditioned'
]

In [80]:
def filter_properties(new_df, project_name="Any", location="Any", bhk="Any", property_type="Any", furnishing="Any",
                      selected_popular_amenities=None, selected_luxury_amenities=None, selected_family_amenities=None, min_price=None, max_price=None):

    filtered_df = new_df.copy()

    filters = {
        "Project Name": project_name,
        "Area Name": location,
        "bedroom": bhk,
        "Type of Property": property_type,
        "furnished Type": furnishing
    }

    for col, value in filters.items():
        if value != "Any":
            filtered_df = filtered_df[filtered_df[col] == value]

    if min_price is not None:
      filtered_df = filtered_df[filtered_df["Price"] >= min_price]

    if max_price is not None:
      filtered_df = filtered_df[filtered_df["Price"] <= max_price]

    if selected_popular_amenities:
        for amenity in selected_popular_amenities:
            filtered_df = filtered_df[filtered_df[amenity] == 1]

    if selected_luxury_amenities:
        for amenity in selected_luxury_amenities:
            filtered_df = filtered_df[filtered_df[amenity] == 1]

    if selected_family_amenities:
        for amenity in selected_family_amenities:
            filtered_df = filtered_df[filtered_df[amenity] == 1]



    return filtered_df

In [81]:
for col in new_df.columns:
    if new_df[col].dtype == 'object':
        if set(new_df[col].unique()).issubset({'Y', 'N', np.nan}):
            new_df[col] = new_df[col].map({'Y': 1, 'N': 0}).fillna(0).astype(int)

new_df.dropna(subset=['Bathroom'], inplace=True)
new_df = new_df.reset_index(drop=True)

In [82]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [83]:
num_transformer = Pipeline([
    ('scaler', StandardScaler())
])
cat_transformer = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [84]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols)
    ],
    remainder='passthrough'
)

In [85]:
X = preprocessor.fit_transform(new_df.drop('Project Name', axis=1))

In [86]:
X.shape

(9943, 482)

In [87]:
from sklearn.neighbors import NearestNeighbors
nn = NearestNeighbors(metric='cosine', n_neighbors=11)
nn.fit(X)

print(f"Model fitted successfully with matrix X shape: {X.shape}")

Model fitted successfully with matrix X shape: (9943, 482)

In [88]:
def recommend_properties(property_idx, n_recommendations=10):

    distances, indices = nn.kneighbors(
        X[property_idx].reshape(1, -1),
        n_neighbors=n_recommendations + 1
    )

    recommendations = new_df.iloc[indices[0][1:]].copy()

    #  similarity score
    recommendations['Similarity (%)'] = (
        (1 - distances[0][1:]) * 100
    ).round(2)

    return recommendations[
        [
            'Project Name',
            'Area Name',
            'Price',
            'bedroom',
            'Type of Property',
            'Similarity (%)'
        ]
    ]

In [89]:
recommend_properties(1000)

,Project Name,Area Name,Price,bedroom,Type of Property,Similarity (%)
949,Unknown Project,Dombivli East,0.40,2,Apartment,82.41
968,Unknown Project,Dombivli East,0.45,2,Apartment,81.84
1221,Unknown Project,Dombivli East,0.36,1,Apartment,80.44
939,Unknown Project,Dombivli East,0.70,2,Apartment,78.27
1877,Vinay Unique Imperia,Virar West,0.50,2,Apartment,78.08
884,Unknown Project,Dombivli East,0.30,1,Apartment,77.21
918,Unknown Project,Dombivli East,0.35,1,Apartment,77.21
959,Unknown Project,Dombivli East,0.90,2,Apartment,77.13
944,Unknown Project,Dombivli East,0.28,1,Apartment,76.21
945,Unknown Project,Dombivli East,0.32,1,Apartment,75.77

In [90]:
new_df[new_df.index==1000][['Project Name',	'Area Name',	'Price',	'bedroom',	'Type of Property']]

        Project Name      Area Name  Price  bedroom Type of Property
1000  Devki Prem CHS  Dombivli East   0.75        2        Apartment

In [91]:
X_df = pd.DataFrame(X, columns=preprocessor.get_feature_names_out())
X_df.head()

,num__Price,num__Covered Area,num__sqft Price,num__Carpet Area,num__Bathroom,num__bedroom,num__balconies,num__floor_ratio,num__Property,cat__Area Name_4 Bunglows,cat__Area Name_AP Narayan Chowk,cat__Area Name_Aarey Milk Colony,cat__Area Name_Adv RD Kowte Chowk,cat__Area Name_Agashi,cat__Area Name_Agripada,cat__Area Name_Air India Colony,cat__Area Name_Akurli Nagar,cat__Area Name_Alika Nagar,cat__Area Name_Amboli,cat__Area Name_Amrut Nagar,cat__Area Name_Anand Nagar,cat__Area Name_Anand Nagar Santacruz East,cat__Area Name_Anand Nagar Thane West,cat__Area Name_Andheri East,cat__Area Name_Andheri West,cat__Area Name_Appa Pada,cat__Area Name_Asalfa Village JJC,cat__Area Name_Asavari,cat__Area Name_Asha Nagar,cat__Area Name_Ashok Nagar Western Mumbai,cat__Area Name_Ashok Van,cat__Area Name_Azad Nagar,cat__Area Name_Azad Nagar 2,cat__Area Name_Azad Nagar JJC,cat__Area Name_Babar Shaikh Chowk,cat__Area Name_Balaji Nagar,cat__Area Name_Balkum Naka,cat__Area Name_Balkum village,cat__Area Name_Bamandaya Pada,cat__Area Name_Banamalipur,cat__Area Name_Bander Pakhadi,cat__Area Name_Bandivali,cat__Area Name_Behram Baug,cat__Area Name_Bhalchandra Nagar,cat__Area Name_Bhaskar Colony,cat__Area Name_Bhavani Nagar,cat__Area Name_Bhawani Shankar,cat__Area Name_Bhayandarpada,cat__Area Name_Bhoiwada,cat__Area Name_Bimbisar Nagar,cat__Area Name_Bolinj,cat__Area Name_Brahmand,cat__Area Name_Brhmanwada,cat__Area Name_CAMA Industrial Estate,cat__Area Name_Century Bazaar,cat__Area Name_Chakala,cat__Area Name_Chakala MIDC,cat__Area Name_Chakki Naka,cat__Area Name_Chandrakant Dhuru Wadi,cat__Area Name_Charai,cat__Area Name_Charkop,cat__Area Name_Charkop Industrial Estate,cat__Area Name_Charkop Sector 1,cat__Area Name_Charkop Sector 2,cat__Area Name_Charkop Sector 3,cat__Area Name_Charkop Sector 4,cat__Area Name_Charkop Sector 5,cat__Area Name_Charkop Sector 6,cat__Area Name_Charkop Sector 7,cat__Area Name_Charkop Sector 8,cat__Area Name_Charkop Sector 9,cat__Area Name_Charkop Village,cat__Area Name_Chembur East,cat__Area Name_Chembur West,cat__Area Name_Chikhal Dongari,cat__Area Name_Chulne,cat__Area Name_Churchgate,cat__Area Name_Churchgate station,cat__Area Name_Churi Wadi,cat__Area Name_Customs Colony,cat__Area Name_D.N. Nagar,cat__Area Name_DN Nagar,cat__Area Name_Dadar East,cat__Area Name_Dadar TT Circle,cat__Area Name_Dadar West,cat__Area Name_Dahisar East,cat__Area Name_Dahisar West,cat__Area Name_Damodarwadi,cat__Area Name_Danda,cat__Area Name_Dattaguru nagar,cat__Area Name_Dattani Park,cat__Area Name_Desai Village,cat__Area Name_Dhanji Wadi,cat__Area Name_Dhanukar Wadi,cat__Area Name_Dhobi Ali,cat__Area Name_Dhokali,cat__Area Name_Dhumal Nagar,cat__Area Name_Dindayal Nagar Vasai,cat__Area Name_Dindoshi,cat__Area Name_Dombivli East,cat__Area Name_Dombivli West,cat__Area Name_Dr Charatsingh Colony,cat__Area Name_Durgeshwari Welfare Society,cat__Area Name_Ekta Nagar Charkop,cat__Area Name_Fateh Baug,cat__Area Name_Film City,cat__Area Name_Film City Road,cat__Area Name_Five Gardens,cat__Area Name_Four Bungalows,cat__Area Name_Gandhi Nagar Dombivli,cat__Area Name_Ganesh Nagar,cat__Area Name_Ganesh Nagar JJC Area,cat__Area Name_Gautam Nagar,cat__Area Name_Gawand Baug,cat__Area Name_Geeta Nagar Mira Road,cat__Area Name_Ghantali,cat__Area Name_Ghartan Pada,cat__Area Name_Gilbert Hill JJC,cat__Area Name_Gokul Township,cat__Area Name_Gokuldham,cat__Area Name_Golani Naka,cat__Area Name_Golibar,cat__Area Name_Gomant Nagar,cat__Area Name_Gondavali Gaothan,cat__Area Name_Goraswadi,cat__Area Name_Goregaon East,cat__Area Name_Grant Road,cat__Area Name_Gulmohar Road,cat__Area Name_Hanuman Nagar,cat__Area Name_Hariniwas Circle,cat__Area Name_Hasmukh Nagar,cat__Area Name_Hind Nagar,cat__Area Name_Hindu Colony,cat__Area Name_Hiranandani Estate,cat__Area Name_ITT Bhatti,cat__Area Name_Indian Oil Nagar- Shivaji Nagar,cat__Area Name_Indira Nagar,cat__Area Name_Irani Wada,cat__Area Name_Irla,cat__Area Name_JB Nagar,cat__Area Name_Jakhadevi Chowk,cat__Area Name_Jambli Naka,cat__Area Name_Janta Nagar,cat__Area Name_Jayprakash Nagar,cat__Area Name_Jethava Nagar,cat__Area Name_Jijamata Road,cat__Area Name_Jogeshwari East,cat__Area Name_Jogeshwari Vikhroli Link Road,cat__Area Name_Jogeshwari West,cat__Area Name_Joshi Wadi,cat__Area Name_Juhu Koliwada,cat__Area Name_Kabutarkhana Purandare Chowk,cat__Area Name_Kadam Wadi Marol,cat__Area Name_Kajuwadi,cat__Area Name_Kaka Sahab Dadarkar Chowk,cat__Area Name_Kalina,cat__Area Name_Kalyan East,cat__Area Name_Kalyan West,cat__Area Name_Kamla Nagar,cat__Area Name_Kandarpada,cat__Area Name_Kandivali East,cat__Area Name_Kandivali West,cat__Area Name_Kanti Nagar,cat__Area Name_Kanya Pada,cat__Area Name_Kapurbawdi,cat__Area Name_Ketki Pada,cat__Area Name_Khar Danda,cat__Area Name_Khar East,cat__Area Name_Khar West,cat__Area Name_Khopat,cat__Area Name_Kings Circle,cat__Area Name_Kokani Pada,cat__Area Name_Koladongri,cat__Area Name_Kolbad,cat__Area Name_Kolivary,cat__Area Name_Koliwada,cat__Area Name_Kolshet,cat__Area Name_Kolshet Road,cat__Area Name_Kondivita Village,cat__Area Name_Kopargaon,cat__Area Name_Kopri,cat__Area Name_Kranti Nagar,cat__Area Name_Kurar Village,cat__Area Name_L Tilak Colony,cat__Area Name_Lallu Bhai Park,cat__Area Name_Laxmi Industrial Estate,cat__Area Name_Laxmi Nagar,cat__Area Name_Laxmiben Chheda Nagar,cat__Area Name_Leo Peter Wadi,cat__Area Name_Lok Puram,cat__Area Name_Lokhandwala Complex,cat__Area Name_Lokhandwala Twp,cat__Area Name_Lokmanya Nagar,cat__Area Name_Louis Wadi,cat__Area Name_Lower Parel East,cat__Area Name_Lower Parel West,cat__Area Name_MSES Colony,cat__Area Name_Mahagiri Koliwada,cat__Area Name_Mahajan Wadi,cat__Area Name_Mahalaxmi Race Course,cat__Area Name_Mahalaxmi Sindhi Colony,cat__Area Name_Mahatama Gandhi Road Amrut Nagar,cat__Area Name_Mahavir Nagar,cat__Area Name_Maheshwari Nagar,cat__Area Name_Mahim East,cat__Area Name_Mahim West,cat__Area Name_Majas Wadi,cat__Area Name_Majiwada,cat__Area Name_Malad East,cat__Area Name_Malcom Baug,cat__Area Name_Mali Nagar,cat__Area Name_Malpa Dongri,cat__Area Name_Mancharji Edhalji Joshi Chowk,cat__Area Name_Manpada,cat__Area Name_Maratha Colony Dahisar,cat__Area Name_Marine Drive,cat__Area Name_Marine Lines,cat__Area Name_Marine Lines East,cat__Area Name_Marol,cat__Area Name_Marol Maroshi,cat__Area Name_Marol Maroshi Road,cat__Area Name_Marol Naka,cat__Area Name_Marol Naka Junction,cat__Area Name_Matunga East,cat__Area Name_Matunga West,cat__Area Name_Meenatai Thakrey Chowk,cat__Area Name_Mhatre Wadi,cat__Area Name_Millat Nagar,cat__Area Name_Mira Road East,cat__Area Name_Miragaon,cat__Area Name_Mogra Village,cat__Area Name_Mogra Village Road,cat__Area Name_Mumbai Central,cat__Area Name_NL Complex,cat__Area Name_NNP Colony,cat__Area Name_Nagari Nivara Parishad,cat__Area Name_Naigaon East,cat__Area Name_Naigaon West,cat__Area Name_Nalasopara East,cat__Area Name_Nalasopara West,cat__Area Name_Nandivali Gaon,cat__Area Name_Nandivli,cat__Area Name_Natwar Nagar,cat__Area Name_Naupada,cat__Area Name_Navagaon,cat__Area Name_Navneeth Colony,cat__Area Name_North Ave,cat__Area Name_Old Khar,cat__Area Name_Oshiwara,cat__Area Name_Oswal Nagari,cat__Area Name_Owale,cat__Area Name_PMGP Colony,cat__Area Name_Panch Pakhdi,cat__Area Name_Pandurang Wadi,cat__Area Name_Parle Colony,cat__Area Name_Parsi Wada,cat__Area Name_Patel Nagar,cat__Area Name_Pathan Wadi Chowk,cat__Area Name_Pathanwadi,cat__Area Name_Patlipada,cat__Area Name_Pawar Nagar,cat__Area Name_Penkarpada,cat__Area Name_Pokharan Road Number 1,cat__Area Name_Pokharan Road Number 2,cat__Area Name_Poonam Nagar,cat__Area Name_Potohar Nagar,cat__Area Name_Prabhadevi,cat__Area Name_Prabhat Colony,cat__Area Name_Prabodhankar Thakre Chowk,cat__Area Name_Primal Nagar,cat__Area Name_Pushpa Park,cat__Area Name_RPF Colony,cat__Area Name_RTO Colony,cat__Area Name_Rabodi,cat__Area Name_Rahul Nagar Chembur,cat__Area Name_Ram Maruti Road Naupada,cat__Area Name_Ram Nagar,cat__Area Name_Rambaug Lane Number 4,cat__Area Name_Raunak Park,cat__Area Name_Rawal Pada,cat__Area Name_Royal Palms Estate,cat__Area Name_Runwal Nagar,cat__Area Name_S Haralayya Chowk,cat__Area Name_SV Patel Nagar,cat__Area Name_Sahar Village,cat__Area Name_Sai Baba Complex,cat__Area Name_Saki Vihar Road,cat__Area Name_Sakinaka Junction,cat__Area Name_Samata Nagar,cat__Area Name_Samel Pada,cat__Area Name_Santacruz East,cat__Area Name_Santacruz West,cat__Area Name_Sanyas Ashram Chowk,cat__Area Name_Saraswat Colony,cat__Area Name_Savarkar Nagar,cat__Area Name_Seepz Area,cat__Area Name_Sen Nagar,cat__Area Name_Seven Bungalows,cat__Area Name_Shahaji Raje Marg,cat__Area Name_Shaheen Nagar,cat__Area Name_Shakti Nagar,cat__Area Name_Sham Nagar,cat__Area Name_Shankar Pada,cat__Area Name_Shanti Ashram,cat__Area Name_Shastri Nagar D Phase,cat__Area Name_Sher E Punjab Society,cat__Area Name_Shivai Nagar,cat__Area Name_Shivaji Nagar,cat__Area Name_Shivaji Nagar Malad East,cat__Area Name_Shivaji Park,cat__Area Name_Shree Siddhivinayak Mandir Chowk,cat__Area Name_Shreyas Colony,cat__Area Name_Shri Swami Samarth Nagar,cat__Area Name_Singh Aghri Estate,cat__Area Name_Sion East,cat__Area Name_Sion Koliwada,cat__Area Name_Sion West,cat__Area Name_Sonar Pada,cat__Area Name_Subhash Nagar,"cat__Area Name_Sundar Nagar, Kalina",cat__Area Name_Sundervan Complex,cat__Area Name_Suresh Colony,cat__Area Name_Suryavanshi Kshatriya Sabhagruha Chowk,cat__Area Name_Suyog Nagar,cat__Area Name_Talav Pali,cat__Area Name_Teen Hath Naka,cat__Area Name_Thakur Complex,"cat__Area Name_Thakur Village, Kandivali East",cat__Area Name_Thane East,cat__Area Name_Thane West,cat__Area Name_Tilak Nagar,cat__Area Name_Tirupati Nagar,cat__Area Name_Tisgaon Naka,cat__Area Name_Triveni Nagar,cat__Area Name_Upper Govind Nagar,cat__Area Name_Usarghar Gaon,cat__Area Name_Uthalsar,cat__Area Name_Vaishali Nagar,cat__Area Name_Vaishali Nagar Dahisar,cat__Area Name_Vartak Nagar,cat__Area Name_Vasai East,cat__Area Name_Vasai West,cat__Area Name_Vasant Vihar,cat__Area Name_Veera Desai Road,cat__Area Name_Venkatapuram-Balapuram,cat__Area Name_Versova Marg,cat__Area Name_Vidya Nagari,cat__Area Name_Vijay Nagar,cat__Area Name_Vile Parle East,cat__Area Name_Vile Parle West,cat__Area Name_Virar East,cat__Area Name_Virar West,cat__Area Name_Virat Nagar,cat__Area Name_Vishnu Nagar,cat__Area Name_Vishveshwar Nagar,cat__Area Name_Vithaldas Nagar,cat__Area Name_Vrindavan Society,cat__Area Name_Waghbil,cat__Area Name_Waghdevi Nagar,cat__Area Name_Wagle Industrial Estate,cat__Area Name_Willingdon Colony,cat__Area Name_Y K Nagar,cat__Area Name_Yashavant Nagar,cat__Area Name_Yashodham,cat__Area Name_Yashodhan Nagar,cat__Area Name_Yeshodham,cat__furnished Type_Furnished,cat__furnished Type_Semi-Furnished,cat__furnished Type_Unfurnished,cat__Facing_East,cat__Facing_North,cat__Facing_North - East,cat__Facing_North - West,cat__Facing_South,cat__Facing_South - East,cat__Facing_South -West,cat__Facing_Unknown,cat__Facing_West,cat__Transaction Type_New Property,cat__Transaction Type_Other,cat__Transaction Type_Rent,cat__Transaction Type_Rent/Lease,cat__Transaction Type_Resale,cat__Type of Property_Apartment,cat__Type of Property_Builder Floor Apartment,cat__Type of Property_Penthouse,cat__Type of Property_Residential House,cat__Type of Property_Villa,cat__Parking_Status_Available,cat__Parking_Status_Unknown,remainder__Society,remainder__isPrimeLocationProperty,remainder__Power Back Up,remainder__Lift,remainder__Rain Water Harvesting,remainder__Club House,remainder__Swimming Pool,remainder__Gymnasium,remainder__Park,remainder__Parking.1,remainder__Security,remainder__Water Storage,remainder__Private Terrace/Garden,remainder__Vaastu Compliant,remainder__Service/Goods Lift,remainder__Air Conditioned,remainder__Visitor Parking,remainder__Intercom Facility,remainder__Maintenance Staff,remainder__Waste Disposal,remainder__Laundry Service,remainder__Internet/Wi-Fi Connectivity,remainder__DTH Television Facility,remainder__RO Water System,remainder__Banquet Hall,remainder__Bar/Lounge,remainder__Cafeteria/Food Court,remainder__Conference Room,remainder__Piped Gas,remainder__Jogging and Strolling Track,remainder__Outdoor Tennis Courts,remainder__Mansion,remainder__Downtown,remainder__Skyline View,remainder__Wrap Around Balcony,remainder__Island Kitchen Layout,remainder__Full Glass Wall,remainder__House help accommodation,remainder__Concierge Services,remainder__Garden View,remainder__Marble flooring,remainder__Well Furnished,remainder__Modular Kitchen,remainder__Helipad,remainder__Private pool,remainder__Private Jaccuzi,remainder__Mini Cinema Theatre,remainder__Golf Course,remainder__Infinity Swimming Pool,remainder__Pool with temperature control,remainder__Sea facing,remainder__Skydeck,remainder__Earth quake resistant,remainder__Theme based Architectures,remainder__Health club with Steam / Jaccuzi,remainder__Large Clubhouse,remainder__Large Open space,remainder__Fingerprint Access,remainder__Grand Entrance lobby,remainder__Private Garage,remainder__Fireplace,remainder__Wine Cellar,remainder__Sky Villa,remainder__Water Front,remainder__Hilltop,remainder__Smart Home,remainder__Barbeque space,remainder__Kids play area,remainder__Library,remainder__Puja Room,remainder__Study,remainder__Servant Room,remainder__Store,remainder__Aerobics Room,remainder__Canopy Walk,remainder__Coffee Lounge & Restaurants,remainder__Dance Studio,remainder__Event Space & Amphitheatre,remainder__Flower Gardens,remainder__Guest Accommodation,remainder__Indoor Squash & Badminton Courts,remainder__Kids Play Area,remainder__Kids Play Pool With Water Slides,remainder__Library And Business Centre,remainder__Meditation Area,remainder__Multipurpose Courts,remainder__Recreational Pool,remainder__Rentable CommuniPfty Space,remainder__Retail Boulevard (Retail Shops),remainder__Cycling & Jogging Track,remainder__Fire Fighting Equipment,remainder__Aesthetically designed landscape garden
0,-0.060810,-0.549999,-0.054967,-0.698197,-0.151378,-1.033196,0.391593,-0.601287,-1.033196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,-0.053269,-0.625064,-0.037730,-0.339534,-0.151378,0.016576,-0.671653,0.231121,0.016576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,-0.055458,-0.261804,-0.050914,-0.328985,-0.151378,0.016576,0.391593,1.714320,0.016576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [92]:
X_weighted = X.copy()

price_col_idx = 0
bedroom_col_idx = 5

X_weighted[:, price_col_idx] *= 5.0
X_weighted[:, bedroom_col_idx] *= 2.0

# 3. Fit a new model with the weighted matrix
nn_weighted = NearestNeighbors(metric='cosine', n_neighbors=11)
nn_weighted.fit(X_weighted)

print("Weighted model trained. High weights give columns more influence on recommendations.")

Weighted model trained. High weights give columns more influence on recommendations.

In [93]:
# import joblib

# # Save the preprocessor and the weighted model
# joblib.dump(preprocessor, 'property_preprocessor.joblib')
# joblib.dump(nn_weighted, 'weighted_nn_model.joblib')
# # Also saving the cleaned dataframe for the app to display results
# new_df.to_csv('cleaned_properties_final.csv', index=False)

# print("Files saved successfully for Streamlit integration:")
# print("1. property_preprocessor.joblib")
# print("2. weighted_nn_model.joblib")
# print("3. cleaned_properties_final.csv")

In [94]:
X_weighted

array([[-0.30405165, -0.54999903, -0.05496655, ...,  1.        ,
         1.        ,  1.        ],
       [-0.26634482, -0.6250639 , -0.03772951, ...,  1.        ,
         1.        ,  1.        ],
       [-0.27729196, -0.26180355, -0.05091352, ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [-0.11551748, -0.20684534, -0.00826933, ...,  0.        ,
         0.        ,  0.        ],
       [-0.07537795,  0.11464677,  0.00861248, ...,  1.        ,
         1.        ,  1.        ],
       [-0.11795018, -0.48297683,  0.00922684, ...,  1.        ,
         1.        ,  1.        ]])

In [95]:
new_df.drop('Project Name', axis=1).head()

,Price,Covered Area,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio,Parking_Status
0,0.32,635.0,4960.0,375.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,1,1,1,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.357143,Available
1,0.63,579.0,10880.0,579.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,1,2,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.588235,Available
2,0.54,850.0,6352.0,585.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,1,2,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.000000,Available
3,0.90,1050.0,8571.0,815.0,Kalyan West,1,Unfurnished,2.0,East,New Property,Apartment,2,1,2,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.185185,Available
4,0.50,561.0,8824.0,419.0,Kalyan West,1,Semi-Furnished,2.0,East,New Property,Apartment,1,1,1,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.307692,Unknown

## Recommender with Manual Weights

- **NOTE: We arent assigning weights to price and we arent scaling it. This will keep Price raw and the difference between 3cr and 15cr will be clearly seen**
- Tried with scaling but it wasnt giving priority to price

In [96]:
from sklearn.preprocessing import MinMaxScaler

COLUMN_WEIGHTS = {

    # Numerical
    'Price':        1.0, # NOTE: We arent assigning weights to price and we arent scaling it
    'bedroom':      3.0,
    'Covered Area': 3.0,
    'sqft Price':   1.0,
    'Bathroom':     2.0,
    'Carpet Area':  1.0,
    'balconies':    0.5,
    'floor_ratio':  0.3,

    # Categorical
    'Area Name':        3.0,
    'furnished Type':   2.0,
    'Type of Property': 2.0,
    'Transaction Type': 1.0,
    'Facing':           0.5,
    'Parking_Status':   0.5,

    # Binary
    'Society':          1.0,
    'Swimming Pool':    1.0,
    'Gymnasium':        1.0,
    'Club House':       0.8,
    'Park':             0.8,
    'Security':         1.0,
    'Lift':             0.8,
    'Power Back Up':    0.5,
    'Visitor Parking':  0.5,
    'Piped Gas':        0.3,
}

In [97]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, TargetEncoder


def build_sklearn_weighted_matrix(df, col_weights):
    parts = []
    scaler = MinMaxScaler()
    ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
    te = TargetEncoder(cv=3)

    SKIP_SCALING = ['Price']

    # Pre-calculate area encoding if needed so it's available for the loop
    area_encoded = None
    if 'Area Name' in df.columns and 'Price' in df.columns:
        area_encoded = te.fit_transform(df[['Area Name']], df['Price'])

    for col, weight in col_weights.items():
        if col not in df.columns:
            continue

        if col == 'Area Name':
            if area_encoded is not None:
                parts.append(area_encoded * weight)

        elif df[col].dtype == 'object':
            encoded = ohe.fit_transform(df[[col]])
            parts.append(encoded * weight)

        elif col in SKIP_SCALING:
            parts.append(df[[col]].values * weight)

        else:
            scaled = scaler.fit_transform(df[[col]])
            parts.append(scaled * weight)

    return np.hstack(parts)

X_weighted_final = build_sklearn_weighted_matrix(new_df, COLUMN_WEIGHTS)
print(f"Final Weighted Matrix Shape: {X_weighted_final.shape}")

nn_model = NearestNeighbors(metric='cosine', n_neighbors=11, algorithm='brute')
nn_model.fit(X_weighted_final)

Final Weighted Matrix Shape: (9943, 43)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=11)

In [98]:
def recommend_v2(property_idx, n=10):

    query_vector = X_weighted_final[property_idx].reshape(1, -1)


    distances, indices = nn_model.kneighbors(query_vector, n_neighbors=n+1)


    rec_indices = indices[0][1:]
    rec_distances = distances[0][1:]

    results = new_df.iloc[rec_indices].copy()

    results['Similarity (%)'] = ((1 - rec_distances) * 100).round(2)

    return results[[
        'Project Name', 'Area Name', 'Price','Property',
        'bedroom', 'Type of Property', 'furnished Type', 'Similarity (%)'
    ]]


display(recommend_v2(9761))

,Project Name,Area Name,Price,Property,bedroom,Type of Property,furnished Type,Similarity (%)
9213,Unknown Project,Amboli,3.60,3,3,Apartment,Unfurnished,99.99
6057,Romell Aether,Goregaon East,3.60,3,3,Apartment,Unfurnished,99.99
8622,Unknown Project,Amboli,3.75,3,3,Apartment,Unfurnished,99.97
8215,Sarova Epsilon,Samata Nagar,3.51,3,3,Apartment,Unfurnished,99.94
8596,Sarova Epsilon,Samata Nagar,3.15,3,3,Apartment,Unfurnished,99.94
439,Indradarshan II,Oshiwara,4.05,3,3,Apartment,Unfurnished,99.93
9359,Vasant Oasis,Andheri East,3.10,3,3,Apartment,Unfurnished,99.83
4632,Dosti Mezzo 22,Sion East,3.93,3,3,Apartment,Unfurnished,99.82
9762,Veda,Andheri East,3.10,3,3,Apartment,Unfurnished,99.81
4496,Sterling Apartment,Chembur East,3.90,3,3,Apartment,Unfurnished,99.79

In [99]:
new_df[new_df.index == 9761][['Project Name',	'Area Name',	'Price',	'bedroom',	'Type of Property',	'furnished Type']]
# 5234

     Project Name Area Name  Price  bedroom Type of Property furnished Type
9761  The Gateway    Amboli    3.6        3        Apartment    Unfurnished

In [100]:
new_df.sample(7)

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio,Parking_Status
3507,0.60,850.00,Mukta Residency,7059.000000,605.000000,Thane West,0,Semi-Furnished,2.0,East,Resale,Apartment,2,0,2,4.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.000000,Available
2492,5.20,1542.68,Unknown Project,33707.573833,1120.000000,Vile Parle East,1,Furnished,3.0,East,Resale,Apartment,3,1,3,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.700000,Available
7498,0.45,450.00,Unknown Project,10000.000000,364.285714,Khar West,0,Unfurnished,1.0,Unknown,Resale,Builder Floor Apartment,1,1,1,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,Unknown
4422,2.30,900.00,Runwal OYT,29487.000000,674.000000,Sion West,0,Semi-Furnished,2.0,North - East,New Property,Apartment,2,1,2,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.758621,Available
7473,6.75,1694.19,Unknown Project,39842.048413,1230.000000,Khar West,1,Unfurnished,3.0,West,New Property,Apartment,3,1,3,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.666667,Available
3727,0.99,1000.00,Dosti Oak,9900.000000,545.000000,Balkum village,0,Furnished,2.0,Unknown,Resale,Apartment,2,1,2,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.466667,Unknown
3157,0.35,300.00,Unknown Project,11667.000000,300.000000,Thane West,0,Semi-Furnished,1.0,North - West,Resale,Apartment,1,1,1,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.200000,Unknown

In [101]:
new_df[new_df.index.isin([9761, 9120, 6057])]

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio,Parking_Status
6057,3.6,1350.0,Romell Aether,26667.0,980.0,Goregaon East,1,Unfurnished,3.0,East,Resale,Apartment,3,1,3,3.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.685714,Available
9120,3.6,1800.0,The Gateway,20000.0,1120.0,Amboli,1,Unfurnished,3.0,East,Resale,Apartment,3,1,3,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.625000,Available
9761,3.6,1500.0,The Gateway,24000.0,1120.0,Amboli,1,Unfurnished,3.0,East,Resale,Apartment,3,1,3,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.687500,Available

In [102]:
# import joblib


# joblib.dump(nn_model, 'weighted_nn_model_v2.joblib')
# joblib.dump(X_weighted_final, 'X_weighted_matrix.joblib')

# print("Manual weighting artifacts saved successfully:")
# print("1. weighted_nn_model_v2.joblib")
# print("2. X_weighted_matrix.joblib")

In [103]:
new_df.sample(5)

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio,Parking_Status
7306,13.67,2136.0,Unknown Project,63998.000000,2136.000000,Mahalaxmi Race Course,1,Semi-Furnished,4.0,East,New Property,Apartment,4,1,4,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.571429,Available
4056,1.25,750.0,Highland Haven,16667.000000,585.000000,Balkum village,0,Semi-Furnished,2.0,Unknown,Resale,Apartment,2,1,2,3.0,0,1,0,1,1,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.869565,Available
462,1.40,688.7,Unknown Project,20328.154494,500.000000,Oshiwara,1,Semi-Furnished,1.0,North - East,Resale,Apartment,2,1,2,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.428571,Available
3344,0.60,850.0,Vedant Apartments,7059.000000,617.108586,Thane West,0,Unfurnished,2.0,Unknown,Resale,Apartment,2,0,2,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,Unknown
6970,0.65,594.0,Mangal Krupa,10943.000000,431.250000,Malad East,0,Unfurnished,2.0,Unknown,Resale,Apartment,1,1,1,1.0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0.666667,Unknown

In [104]:
import pandas as pd

X_weighted_df = pd.DataFrame(X_weighted_final)

print("Weighted Matrix DataFrame (First 5 rows):")
display(X_weighted_df.head())

Weighted Matrix DataFrame (First 5 rows):

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42
0,0.32,0.0,0.125033,0.000146,0.222222,0.017874,0.071429,0.203571,1.722607,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,1.0,1.0,1.0,0.8,0.8,1.0,0.8,0.5,0.5,0.3
1,0.63,0.6,0.113830,0.000320,0.222222,0.027650,0.000000,0.238235,1.669458,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,1.0,1.0,1.0,0.8,0.8,1.0,0.8,0.5,0.5,0.3
2,0.54,0.6,0.168045,0.000187,0.222222,0.027938,0.071429,0.300000,1.703363,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,1.0,1.0,1.0,0.8,0.8,1.0,0.8,0.5,0.5,0.3
3,0.90,0.6,0.208055,0.000252,0.222222,0.038959,0.142857,0.177778,1.669458,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,1.0,1.0,1.0,0.8,0.8,1.0,0.8,0.5,0.5,0.3
4,0.50,0.0,0.110229,0.000260,0.222222,0.019983,0.000000,0.196154,1.722607,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,1.0,1.0,1.0,0.8,0.8,1.0,0.8,0.5,0.5,0.3

In [105]:
amenity_cols = [c for c in new_df.columns if new_df[c].dtype in ['int64', 'float64']
                and new_df[c].between(0, 1).all()]

fill_rates = new_df[amenity_cols].mean().sort_values(ascending=False)
print(fill_rates)

isPrimeLocationProperty    0.744142
Lift                       0.732877
Security                   0.723524
Parking.1                  0.667304
Park                       0.648396
                             ...
Society                    0.523886
Study                      0.508096
Servant Room               0.507593
Puja Room                  0.477723
Store                      0.453384
Length: 92, dtype: float64

In [106]:
new_df[new_df['Price']==new_df['Price'].median()].head()

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,Power Back Up,Lift,Rain Water Harvesting,Club House,Swimming Pool,Gymnasium,Park,Parking.1,Security,Water Storage,Private Terrace/Garden,Vaastu Compliant,Service/Goods Lift,Air Conditioned,Visitor Parking,Intercom Facility,Maintenance Staff,Waste Disposal,Laundry Service,Internet/Wi-Fi Connectivity,DTH Television Facility,RO Water System,Banquet Hall,Bar/Lounge,Cafeteria/Food Court,Conference Room,Piped Gas,Jogging and Strolling Track,Outdoor Tennis Courts,Mansion,Downtown,Skyline View,Wrap Around Balcony,Island Kitchen Layout,Full Glass Wall,House help accommodation,Concierge Services,Garden View,Marble flooring,Well Furnished,Modular Kitchen,Helipad,Private pool,Private Jaccuzi,Mini Cinema Theatre,Golf Course,Infinity Swimming Pool,Pool with temperature control,Sea facing,Skydeck,Earth quake resistant,Theme based Architectures,Health club with Steam / Jaccuzi,Large Clubhouse,Large Open space,Fingerprint Access,Grand Entrance lobby,Private Garage,Fireplace,Wine Cellar,Sky Villa,Water Front,Hilltop,Smart Home,Barbeque space,Kids play area,Library,Puja Room,Study,Servant Room,Store,Aerobics Room,Canopy Walk,Coffee Lounge & Restaurants,Dance Studio,Event Space & Amphitheatre,Flower Gardens,Guest Accommodation,Indoor Squash & Badminton Courts,Kids Play Area,Kids Play Pool With Water Slides,Library And Business Centre,Meditation Area,Multipurpose Courts,Recreational Pool,Rentable CommuniPfty Space,Retail Boulevard (Retail Shops),Cycling & Jogging Track,Fire Fighting Equipment,Aesthetically designed landscape garden,floor_ratio,Parking_Status
327,1.4,650.0,Abba Residency,21538.000000,470.000000,Malcom Baug,1,Semi-Furnished,2.0,West,Resale,Apartment,1,1,1,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.500000,Available
349,1.4,915.0,Roswalt Zaiden,15300.000000,610.000000,Jogeshwari West,1,Furnished,2.0,South -West,New Property,Apartment,2,1,2,2.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.552632,Available
406,1.4,750.0,Unknown Project,18667.000000,544.507576,Jogeshwari West,0,Semi-Furnished,1.0,Unknown,Resale,Apartment,2,1,2,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,Available
462,1.4,688.7,Unknown Project,20328.154494,500.000000,Oshiwara,1,Semi-Furnished,1.0,North - East,Resale,Apartment,2,1,2,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.428571,Available
480,1.4,705.0,Abba Residency,19858.000000,470.000000,Jogeshwari West,0,Unfurnished,2.0,West,Resale,Apartment,1,1,1,1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.500000,Available

In [107]:
new_df['amenity_score'] = (

    (new_df['Price'] >= 2).astype(int) +

    (new_df['Covered Area'] >= 1000).astype(int) +

    (new_df['bedroom'] >= 3).astype(int) +

    (new_df['Bathroom'] >= 3).astype(int) +

    (new_df['balconies'] >= 2).astype(int) +

    (new_df['isPrimeLocationProperty'] == 1).astype(int)
)

In [108]:
new_df['luxury_score'] = (

    (new_df['Price'] >= 5).astype(int) * 3 +

    (new_df['Price'] >= 10).astype(int) * 3 +

    (new_df['Covered Area'] >= 1500).astype(int) * 2 +

    (new_df['Carpet Area'] >= 1200).astype(int) * 2 +

    (new_df['bedroom'] >= 4).astype(int) * 2 +

    (new_df['Bathroom'] >= 4).astype(int) * 1 +

    (new_df['isPrimeLocationProperty'] == 1).astype(int) * 2
)

In [109]:
keep_cols = [
    'Price',
    'Covered Area',
    'Project Name',
    'sqft Price',
    'Carpet Area',
    'Area Name',
    'Society',
    'furnished Type',
    'Bathroom',
    'Facing',
    'Transaction Type',
    'Type of Property',
    'bedroom',
    'isPrimeLocationProperty',
    'Property',
    'balconies',
    'floor_ratio',
    'Parking_Status',
    'amenity_score',
    'luxury_score'
]
new_df = new_df[keep_cols]

In [ ]:
new_df["Price"].max()

4080.0

In [ ]:
new_df["Price"].sort_values(ascending=False)

2222    4080.00
6701     280.00
5356      45.00
5319      41.00
5378      38.00
         ...
2828       0.04
9134       0.04
7641       0.02
2223       0.01
8148       0.01
Name: Price, Length: 9943, dtype: float64

In [ ]:
new_df.loc[2222, 'Price'] = 5.0

np.float64(4080.0)

In [110]:
new_df.to_csv('Final RS Dataset.csv', index=False)

In [146]:
COLUMN_WEIGHTS = {
    'Price': 4,
    'Area Name': 4,
    'Covered Area': 3,
    'bedroom': 3,
    'Bathroom': 2,

    'Type of Property': 7,

    'amenity_score': 2,
    'luxury_score': 3
}

In [147]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, TargetEncoder


def build_sklearn_weighted_matrix(df, col_weights):
    parts = []
    scaler = MinMaxScaler()
    ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
    te = TargetEncoder(cv=3)

    # SKIP_SCALING = ['Price']

    area_encoded = None
    if 'Area Name' in df.columns and 'Price' in df.columns:
        area_encoded = te.fit_transform(df[['Area Name']], df['Price'])

    for col, weight in col_weights.items():
        if col not in df.columns:
            continue

        if col == 'Area Name':
            if area_encoded is not None:
                parts.append(area_encoded * weight)

        elif df[col].dtype == 'object':
            encoded = ohe.fit_transform(df[[col]])
            parts.append(encoded * weight)

        # elif col in SKIP_SCALING:
        #     parts.append(df[[col]].values * weight)

        else:
            scaled = scaler.fit_transform(df[[col]])
            parts.append(scaled * weight)

    return np.hstack(parts)

X_weighted_final = build_sklearn_weighted_matrix(new_df, COLUMN_WEIGHTS)
print(f"Final Weighted Matrix Shape: {X_weighted_final.shape}")

nn_model = NearestNeighbors(metric='cosine', n_neighbors=11, algorithm='brute')
nn_model.fit(X_weighted_final)

Final Weighted Matrix Shape: (9943, 12)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=11)

In [148]:
import joblib

joblib.dump(nn_model, 'latest_weighted_nn_model.joblib')
joblib.dump(X_weighted_final, 'latest_X_weighted_matrix.joblib')

['latest_X_weighted_matrix.joblib']

In [143]:
def recommend_v2(property_idx, n=5):

    query_vector = X_weighted_final[property_idx].reshape(1, -1)


    distances, indices = nn_model.kneighbors(query_vector, n_neighbors=n+1)


    rec_indices = indices[0][1:]
    rec_distances = distances[0][1:]

    results = new_df.iloc[rec_indices].copy()

    similarity = 1 / (1 + rec_distances)
    results['Similarity (%)'] = (similarity * 100).round(2)

    return results[[
        'Project Name', 'Area Name', 'Price','Property',
        'bedroom', 'Type of Property', 'furnished Type', 'Similarity (%)'
    ]]


display(recommend_v2(5965))

,Project Name,Area Name,Price,Property,bedroom,Type of Property,furnished Type,Similarity (%)
1771,Prabhat Complex,Virar West,1.15,4,4,Apartment,Unfurnished,99.50
5876,Unknown Project,Naigaon West,0.75,4,4,Villa,Semi-Furnished,99.48
705,Runwal Gardens,Dombivli East,4.50,4,4,Apartment,Unfurnished,99.47
698,IRA INSIGNIA,Dombivli East,1.90,4,4,Apartment,Unfurnished,99.27
2841,Jai Residency,Vasai East,1.40,3,3,Apartment,Unfurnished,98.23

In [139]:
new_df.sample(5)

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,floor_ratio,Parking_Status,amenity_score,luxury_score
1529,1.80,1150.00,Kalpnagri Dhaivat,15652.0,800.000000,Vaishali Nagar,0,Furnished,2.0,Unknown,Resale,Apartment,2,1,2,2.0,0.066667,Available,3,2
5965,2.50,2000.00,Unknown Project,12500.0,2000.000000,Naigaon East,0,Semi-Furnished,4.0,Unknown,Resale,Villa,4,0,4,3.0,0.512821,Unknown,5,7
737,0.21,674.92,Unknown Project,4285.0,490.000000,Dombivli East,1,Semi-Furnished,1.0,Unknown,Resale,Apartment,1,0,1,1.0,0.000000,Unknown,0,0
7859,1.75,1100.00,Unknown Project,15909.0,798.611111,Kandivali West,0,Unfurnished,2.0,North,Resale,Apartment,2,0,2,1.0,1.000000,Unknown,1,0
9331,3.53,1190.00,Platinum Life,29663.0,950.000000,Andheri West,1,Unfurnished,3.0,East,New Property,Apartment,3,1,3,3.0,0.458333,Available,6,2

In [114]:
new_df[new_df.index == 9761][['Project Name',	'Area Name',	'Price',	'bedroom',	'Type of Property',	'furnished Type']]
# 5234

     Project Name Area Name  Price  bedroom Type of Property furnished Type
9761  The Gateway    Amboli    3.6        3        Apartment    Unfurnished

In [115]:
new_df[new_df.index.isin([9761, 9177, 8799])]

,Price,Covered Area,Project Name,sqft Price,Carpet Area,Area Name,Society,furnished Type,Bathroom,Facing,Transaction Type,Type of Property,bedroom,isPrimeLocationProperty,Property,balconies,floor_ratio,Parking_Status,amenity_score,luxury_score
8799,2.60,1515.0,Unknown Project,17162.0,1099.905303,Andheri West,1,Furnished,3.0,East,Resale,Apartment,3,1,3,1.0,0.312500,Available,5,4
9177,4.75,1600.0,Adani Western Heights,29688.0,1150.000000,Andheri West,0,Unfurnished,3.0,East,Resale,Apartment,3,1,3,1.0,0.392857,Unknown,5,4
9761,3.60,1500.0,The Gateway,24000.0,1120.000000,Amboli,1,Unfurnished,3.0,East,Resale,Apartment,3,1,3,1.0,0.687500,Available,5,4

In [123]:
def filter_properties(new_df, project_name="Any", location="Any", bhk="Any", property_type="Any", furnishing="Any", min_price=None, max_price=None):
    filtered_df = new_df.copy()

    filters = {
        "Project Name": project_name,
        "Area Name": location,
        "bedroom": bhk,
        "Type of Property": property_type,
        "furnished Type": furnishing
    }

    for col, value in filters.items():
        if value != "Any":
            filtered_df = filtered_df[filtered_df[col] == value]

    if min_price is not None:
        filtered_df = filtered_df[filtered_df["Price"] >= min_price]
    if max_price is not None:
        filtered_df = filtered_df[filtered_df["Price"] <= max_price]

    return filtered_df

# --- EASY WORKFLOW EXAMPLE ---
# Step 1: User filters properties (e.g., looking for 3 BHK in Amboli)
search_results = filter_properties(new_df, location="Amboli", bhk=3)

# Step 2: User selects one property from the results (we'll take the first one as an example)
if not search_results.empty:
    selected_property_index = search_results.index[0]
    print(f"User selected property at index: {selected_property_index}")

    # Step 3: Display recommendations based on that specific selection
    recommendations = recommend_v2(selected_property_index, n=5)

    print("\nProperties similar to your selection:")
    display(recommendations)
else:
    print("No properties found matching those filters.")

User selected property at index: 8622

Properties similar to your selection:

,Project Name,Area Name,Price,Property,bedroom,Type of Property,furnished Type,Similarity (%)
6222,Unknown Project,Gokuldham,2.55,3,3,Apartment,Furnished,100.0
510,Kalpataru Vivant,Jogeshwari Vikhroli Link Road,2.82,3,3,Apartment,Unfurnished,100.0
519,Kalpataru Vivant,Jogeshwari Vikhroli Link Road,2.90,3,3,Apartment,Semi-Furnished,100.0
674,Kalpataru Vivant,Jogeshwari Vikhroli Link Road,2.75,3,3,Apartment,Unfurnished,100.0
6290,Jyoti Sukriti,Gokuldham,3.00,3,3,Apartment,Unfurnished,100.0

In [125]:
new_df["Price"].max()

4080.0

In [128]:
new_df["Price"].sort_values(ascending=False)

2222    4080.00
6701     280.00
5356      45.00
5319      41.00
5378      38.00
         ...
2828       0.04
9134       0.04
7641       0.02
2223       0.01
8148       0.01
Name: Price, Length: 9943, dtype: float64

In [130]:
new_df.loc[2222, 'Price'] = 5.0

np.float64(4080.0)