In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('/content/drive/MyDrive/Machine Learning/Projects/Real Estate Capstone Project/DataSets/independent_house_main.csv')
df2 = pd.read_csv('/content/drive/MyDrive/Machine Learning/Projects/Real Estate Capstone Project/DataSets/farmhouse_main.csv')

df1_copy = df1.copy()
df2_copy = df2.copy()

In [3]:
df1.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,...,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"1 Bedroom House in Tembhipada, Bhandup West",https://www.99acres.com/1-bhk-bedroom-independ...,NaN,Rs. 20 Lac,Rs. 13333 / sq.ft.,150 sqft (Plot Area) / 13.94 sq.m.,150 sqft (Plot Area) / 13.94 sq.m.,1.0,1.0,0.0,...,"Tembhipada, Bhandup West",2 floors total,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,Z91029480
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",https://www.99acres.com/2-bhk-bedroom-independ...,NaN,Rs. 6 Crore,Rs. 63157 / sq.ft.,950 sqft (Plot Area) / 88.26 sq.m.,950 sqft (Plot Area) / 88.26 sq.m.,2.0,2.0,0.0,...,Zaver Mansion Bungalow,1 floors total,NaN,10-20 Years Old / Under Construction,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,D91016984
2,"5 Bedroom House in Juhu Lane, Andheri West",https://www.99acres.com/5-bhk-bedroom-independ...,NaN,Rs. 25 Crore,Rs. 89285 / sq.ft.,2800 sqft (Plot Area) / 260.13 sq.m.,2800 sqft (Plot Area) / 260.13 sq.m.,5.0,3.0,2.0,...,"Juhu Lane, Andheri West",1 floors total,North,5-10 Years Old / Ready to Move,Standard chartered ATM (ATM) | Jeevan Jyot Med...,"Located in juhu lane, andheri west, this furni...","Furnished (Modular Kitchen, Refrigerator, Bed,...",North Facing | Corner Property | Overlooking M...,O,F90986152
3,"4 Bedroom House in Chembur East, Mumbai",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,Rs. 8 Crore,Rs. 27586 / sq.ft.,2900 sqft (Built-Up Area) / 269.42 sq.m.,2900 sqft (Built-Up Area) / 269.42 sq.m.,4.0,4.0,0.0,...,"Chembur East, Mumbai",3 floors total,NaN,5-10 Years Old / Ready to Move,bhaji & machhi market (Shopping) | Shanni Mand...,We are proud owners of house/villa available f...,NaN,NaN,O,V90986074
4,"3 Bedroom House in Nahur East, Bhandup",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,Rs. 10.7 Crore,Rs. 44583 / sq.ft.,1550 sqft (Plot Area) / 144 sq.m.,1550 sqft (Plot Area) / 144 sq.m.,3.0,2.0,1.0,...,"Nahur East, Bhandup",2 floors total,North-East,10-20 Years Old / Under Construction,Bethesda Church TATA COUNTY (Religious Place) ...,Available due to owner relocating overseas. \n...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Water Storage | Piped Gas |...,O,L90974662

In [4]:
df2.head()

,roperty_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"2 Bedroom Farm house in karjat panvel, Navi Mu...",https://www.99acres.com/2-bhk-bedroom-farm-hou...,NaN,Rs. 2.2 Crore,21779 sqft (Plot Area) / 2023.33 sq.m.,21779 sqft (Plot Area) / 2023.33 sq.m.,2,2,3,NaN,karjat panvel,NaN,East,1-5 Years Old / 1-5 Years Old,NaN,"Near by karjat station, near by greenery, near...",NaN,Reserved Parking | Lift | Water Storage | Pipe...,A,V88824568
1,"4 Bedroom Farm house in karjat, Navi Mumbai",https://www.99acres.com/4-bhk-bedroom-farm-hou...,NaN,Rs. 2.02 Crore,20000 sqft (Plot Area) / 1858.06 sq.m.,20000 sqft (Plot Area) / 1858.06 sq.m.,4,3,4,NaN,karjat,1 floors total,NaN,5-10 Years Old / Ready to Move,NaN,"Near by station , near by karjat station, near...","Furnished (Lights, Fans, Geyser, Sofa)",Reserved Parking | Water Storage | Piped Gas |...,A,F88215342
2,"3 Bedroom Farm house in Karjat, Thane",https://www.99acres.com/3-bhk-bedroom-farm-hou...,NaN,Rs. 4.5 Crore,22868 sqft (Plot Area) / 2124.51 sq.m.,22868 sqft (Plot Area) / 2124.51 sq.m.,3,4,3,NaN,"Karjat, Thane",2 floors total,North-East,0-1 Year Old / 0-1 Year Old,Dr. Sabale Orthopaedic Hospital (Hospital) | M...,Canaltouch 20 guntha mountain view 3bhk bungal...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Solar Panels | Lift | Piped Gas | Club House |...,A,G82088626
3,"2 Bedroom Farm house in Karjat, Thane",https://www.99acres.com/2-bhk-bedroom-farm-hou...,NaN,Rs. 3.7 Crore,65339 sqft (Plot Area) / 6070.19 sq.m.,65339 sqft (Plot Area) / 6070.19 sq.m.,2,3,1,NaN,"Karjat, Thane",2 floors total,South-East,10-20 Years Old / Under Construction,Dr. Sabale Orthopaedic Hospital (Hospital) | M...,River touch 60 guntha 2bhk bungalow with swimm...,"Semi-Furnished (Lights, Fans, AC, TV, Bed, War...",Solar Panels | Lift | Piped Gas | Club House |...,A,X78933269
4,"3 Bedroom Farm house in Karjat, Thane",https://www.99acres.com/3-bhk-bedroom-farm-hou...,NaN,Rs. 4.25 Crore,27224 sqft (Plot Area) / 2529.19 sq.m.,27224 sqft (Plot Area) / 2529.19 sq.m.,3,4,4,NaN,"Karjat, Thane",2 floors total,North-West,0-1 Year Old / 0-1 Year Old,Dr. Sabale Orthopaedic Hospital (Hospital) | M...,25 guntha mountain view ready farmhouse for sa...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Solar Panels | Lift | Piped Gas | Club House |...,A,X74896685

# **df1 - Independent House / Villa**


### property_name
- few names and other with eg 2 Bedroom House in 'location'
- 176th row has 48 bedrooms (invalid)

### society
- random names mostly not realated to societies and few contain location

### price
- price in Crore and Lac
- Contains Available on request

### rate
- contains price/sqft

### area
- contains sqft (others are unwanted)

### areaWithType
- exactly same as area (drop)

### additional room
- contains pooja room, study room, etc.
- many values empty

### address
- contains address. Extract only the main value

### no of floors
- contains floors. convert it to numeric

### facing
- facing of the house

### agePossession
- contains range of years and status eg Under Construction, Ready to move

### nearby location
- Seperated By '|'

### description
- about the house

### furnishDetails
- convert it to furnished, semi-furnished, unfurnished

### features
- seperated by '|'

### rating
- O and A

### property_id
- drop it

## MISSING DATA:

- property_name: 0.0%
- link: 0.68%
- society: 50.55%
- price: 0.68%
- rate: 0.68%
- area: 0.68%
- areaWithType: 0.68%
- bedRoom: 0.68%
- bathroom: 0.68%
- balcony: 1.19%
- additionalRoom: 97.11%
- address: 0.68%
- noOfFloor: 6.98%
- facing: 44.09%
- agePossession: 4.51%
- nearbyLocations: 11.49%
- description: 0.68%
- furnishDetails: 23.74%
- features: 31.15%
- rating: 0.68%
- property_id: 0.68%

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1175 non-null   object
 1   link             1167 non-null   object
 2   society          581 non-null    object
 3   price            1167 non-null   object
 4   rate             1167 non-null   object
 5   area             1167 non-null   object
 6   areaWithType     1167 non-null   object
 7   bedRoom          1167 non-null   float64
 8   bathroom         1167 non-null   float64
 9   balcony          1161 non-null   float64
 10  additionalRoom   34 non-null     object
 11  address          1167 non-null   object
 12  noOfFloor        1093 non-null   object
 13  facing           657 non-null    object
 14  agePossession    1122 non-null   object
 15  nearbyLocations  1040 non-null   object
 16  description      1167 non-null   object
 17  furnishDetails   896 non-null    object
 18  features         809 non-null    object
 19  rating           1167 non-null   object
 20  property_id      1167 non-null   object
dtypes: float64(3), object(18)
memory usage: 192.9+ KB

In [6]:
df1.describe()

           bedRoom     bathroom      balcony
count  1167.000000  1167.000000  1161.000000
mean      3.072836     3.077978     1.558140
std       2.256458     3.271571     1.457539
min       1.000000     0.000000     0.000000
25%       1.000000     2.000000     0.000000
50%       3.000000     3.000000     1.000000
75%       4.000000     4.000000     3.000000
max      48.000000    96.000000     4.000000

In [7]:
def checkMissingData(df):

  print("Missing Data: \n")
  for i in df.columns:
    percent = round(df[i].isna().sum()/df.shape[0]*100,2)
    print(f"- {i}: {percent}%")

checkMissingData(df1)

Missing Data:

- property_name: 0.0%
- link: 0.68%
- society: 50.55%
- price: 0.68%
- rate: 0.68%
- area: 0.68%
- areaWithType: 0.68%
- bedRoom: 0.68%
- bathroom: 0.68%
- balcony: 1.19%
- additionalRoom: 97.11%
- address: 0.68%
- noOfFloor: 6.98%
- facing: 44.09%
- agePossession: 4.51%
- nearbyLocations: 11.49%
- description: 0.68%
- furnishDetails: 23.74%
- features: 31.15%
- rating: 0.68%
- property_id: 0.68%

In [8]:
df1.head(1)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,...,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,"1 Bedroom House in Tembhipada, Bhandup West",https://www.99acres.com/1-bhk-bedroom-independ...,NaN,Rs. 20 Lac,Rs. 13333 / sq.ft.,150 sqft (Plot Area) / 13.94 sq.m.,150 sqft (Plot Area) / 13.94 sq.m.,1.0,1.0,0.0,...,"Tembhipada, Bhandup West",2 floors total,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,Z91029480

In [9]:
df1['bhk'] = df1['link'].str.split("m/").str.get(1).str.split("-b").str.get(0).astype(float)

In [10]:
df1.drop(columns=['link', 'society', 'areaWithType', 'property_id'], inplace=True)

## Property_name

In [11]:
df1.head(2)

,property_name,price,rate,area,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,bhk
0,"1 Bedroom House in Tembhipada, Bhandup West",Rs. 20 Lac,Rs. 13333 / sq.ft.,150 sqft (Plot Area) / 13.94 sq.m.,1.0,1.0,0.0,NaN,"Tembhipada, Bhandup West",2 floors total,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1.0
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",Rs. 6 Crore,Rs. 63157 / sq.ft.,950 sqft (Plot Area) / 88.26 sq.m.,2.0,2.0,0.0,NaN,Zaver Mansion Bungalow,1 floors total,NaN,10-20 Years Old / Under Construction,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2.0

In [12]:
df1['property_name'].isna().sum()

np.int64(0)

In [13]:
df1.drop(index=176, inplace=True)

## price

In [14]:
df1[df1['price'].isna()]

,property_name,price,rate,area,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,bhk
1167,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1168,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1169,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1170,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1171,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1172,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1173,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1174,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df1.dropna(subset=['price'],inplace=True)

In [16]:
(df1['price'].str.contains('request', case=False, na=False)).sum()

np.int64(3)

In [17]:
df1= df1[~df1['price'].str.contains('request', case=False, na=False)].reset_index(drop=True)

In [18]:
missing_unit = df1[~df1['price'].str.contains('Lac|Crore', case=False, na=False)]

if missing_unit.empty:
    print("All entries contain either 'Lac' or 'Crore'.")
else:
    print(f"Found {len(missing_unit)} entries without standard units:")
    display(missing_unit[['price']])

All entries contain either 'Lac' or 'Crore'.

In [19]:
def priceCleaning(text):

    text = text.replace("Rs. ", "").strip()

    if "Crore" in text:
        text = text.replace(" Crore", "").strip()
        return round(float(text),2)

    if "Lac" in text:
        text = text.replace(" Lac", "").strip()
        return round(float(text) / 100,2)


df1['price'] = df1['price'].apply(priceCleaning)

## rate

In [20]:
df1.head()

,property_name,price,rate,area,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,bhk
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,Rs. 13333 / sq.ft.,150 sqft (Plot Area) / 13.94 sq.m.,1.0,1.0,0.0,NaN,"Tembhipada, Bhandup West",2 floors total,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1.0
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,Rs. 63157 / sq.ft.,950 sqft (Plot Area) / 88.26 sq.m.,2.0,2.0,0.0,NaN,Zaver Mansion Bungalow,1 floors total,NaN,10-20 Years Old / Under Construction,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2.0
2,"5 Bedroom House in Juhu Lane, Andheri West",25.0,Rs. 89285 / sq.ft.,2800 sqft (Plot Area) / 260.13 sq.m.,5.0,3.0,2.0,NaN,"Juhu Lane, Andheri West",1 floors total,North,5-10 Years Old / Ready to Move,Standard chartered ATM (ATM) | Jeevan Jyot Med...,"Located in juhu lane, andheri west, this furni...","Furnished (Modular Kitchen, Refrigerator, Bed,...",North Facing | Corner Property | Overlooking M...,O,5.0
3,"4 Bedroom House in Chembur East, Mumbai",8.0,Rs. 27586 / sq.ft.,2900 sqft (Built-Up Area) / 269.42 sq.m.,4.0,4.0,0.0,NaN,"Chembur East, Mumbai",3 floors total,NaN,5-10 Years Old / Ready to Move,bhaji & machhi market (Shopping) | Shanni Mand...,We are proud owners of house/villa available f...,NaN,NaN,O,4.0
4,"3 Bedroom House in Nahur East, Bhandup",10.7,Rs. 44583 / sq.ft.,1550 sqft (Plot Area) / 144 sq.m.,3.0,2.0,1.0,NaN,"Nahur East, Bhandup",2 floors total,North-East,10-20 Years Old / Under Construction,Bethesda Church TATA COUNTY (Religious Place) ...,Available due to owner relocating overseas. \n...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Water Storage | Piped Gas |...,O,3.0

In [21]:
df1.rename(columns={"rate": "rate_per_sqft"},inplace=True)

In [22]:
df1['rate_per_sqft'] =df1['rate_per_sqft'].str.replace("Rs. ","").str.split("/").str.get(0)

In [23]:
df1['rate_per_sqft'] = df1['rate_per_sqft'].astype(float)

## area

In [24]:
def parse_area(val):
    if pd.isna(val):
        return np.nan, np.nan
    first_part = str(val).split('/')[0].strip()  # 4800 sqft (Plot Area)
    num = float(first_part.split('sqft')[0].strip())
    if 'Plot' in val:       atype = 'plot'
    elif 'Built' in val:    atype = 'buildup'
    elif 'Carpet' in val:   atype = 'carpet'
    else:                   atype = 'unknown'
    return num, atype

df1[['area_sqft', 'area_type']] = df1['area'].apply(
    lambda x: pd.Series(parse_area(x))
)

In [25]:
df1.drop(columns='area', inplace=True)

In [26]:
df1.head()

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,bhk,area_sqft,area_type
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,13333.0,1.0,1.0,0.0,NaN,"Tembhipada, Bhandup West",2 floors total,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1.0,150.0,plot
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,63157.0,2.0,2.0,0.0,NaN,Zaver Mansion Bungalow,1 floors total,NaN,10-20 Years Old / Under Construction,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2.0,950.0,plot
2,"5 Bedroom House in Juhu Lane, Andheri West",25.0,89285.0,5.0,3.0,2.0,NaN,"Juhu Lane, Andheri West",1 floors total,North,5-10 Years Old / Ready to Move,Standard chartered ATM (ATM) | Jeevan Jyot Med...,"Located in juhu lane, andheri west, this furni...","Furnished (Modular Kitchen, Refrigerator, Bed,...",North Facing | Corner Property | Overlooking M...,O,5.0,2800.0,plot
3,"4 Bedroom House in Chembur East, Mumbai",8.0,27586.0,4.0,4.0,0.0,NaN,"Chembur East, Mumbai",3 floors total,NaN,5-10 Years Old / Ready to Move,bhaji & machhi market (Shopping) | Shanni Mand...,We are proud owners of house/villa available f...,NaN,NaN,O,4.0,2900.0,buildup
4,"3 Bedroom House in Nahur East, Bhandup",10.7,44583.0,3.0,2.0,1.0,NaN,"Nahur East, Bhandup",2 floors total,North-East,10-20 Years Old / Under Construction,Bethesda Church TATA COUNTY (Religious Place) ...,Available due to owner relocating overseas. \n...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Water Storage | Piped Gas |...,O,3.0,1550.0,plot

## bedroom, bathroom, balcony

In [27]:
print(df1['bedRoom'].isna().sum())
print(df1['bathroom'].isna().sum())
print(df1['balcony'].isna().sum())

0
0
6

In [28]:
df1['balcony'] = df1['balcony'].fillna(0)

In [29]:
df1['bedRoom'] = df1['bedRoom'].astype(int)
df1['bathroom'] = df1['bathroom'].astype(int)
df1['balcony'] = df1['balcony'].astype(int)

In [30]:
df1.drop(columns='additionalRoom',inplace=True)

In [31]:
df1.head(2)

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,bhk,area_sqft,area_type
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,13333.0,1,1,0,"Tembhipada, Bhandup West",2 floors total,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1.0,150.0,plot
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,63157.0,2,2,0,Zaver Mansion Bungalow,1 floors total,NaN,10-20 Years Old / Under Construction,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2.0,950.0,plot

## address

In [32]:
df1['address'].unique()

array(['Tembhipada, Bhandup West', 'Zaver Mansion Bungalow',
       'Juhu Lane, Andheri West', 'Chembur East, Mumbai',
       'Nahur East, Bhandup', 'Irani Wadi, Kandivali West',
       'Vidyavihar West, Mumbai', 'Charkop, Kandivali West',
       'Kanjur Village, Bhandup', 'Ghatkopar East, Mumbai',
       'Mulund Colony, Mulund West',
       'New Gautam Nagar, Govandi East, Mumbai', 'Borivali West, Mumbai',
       'Veena Nagar Phase 2, Mulund West',
       'Deonar Municipal Colony, Govandi East, Mumbai',
       'Ashtavinayak Nagar, Borivali West', 'Bhandup West, Mumbai',
       'Saifee Park, Marol', 'Sector 8 Charkop, Kandivali West',
       'Rani Sati Nagar, Malad', 'Goregaon West, Mumbai',
       'Kalina, Santacruz East', 'Hallow Pul, Kurla, Mumbai',
       'Grant Road, Mumbai', 'Khar West, Mumbai', 'titwala',
       'Kajupada, Borivali East', 'Azad Nagar, Andheri West',
       'Samata Nagar, Kandivali East', 'Upper Govind Nagar, Malad East',
       'Pereira Wadi, Asalpha, Mumbai', 'Malvani, Malad West',
       'Deonar, Chembur East', 'Seven Bunglow, Andheri West',
       'Sector 1 Charkop, Kandivali West', 'Govandi, Mumbai',
       'Chembur, Mumbai', 'Eksar, Borivali West',
       'Hiranandani Gardens Powai, Mumbai', 'Powai, Mumbai',
       'Andheri West, Mumbai', 'Mankhurd West, Govandi East, Mumbai',
       'Mandala, Mankhurd, Mumbai', 'Sector 9 Charkop, Kandivali West',
       'Tata Nagar, Bhandup', 'Mysore Colony, Chembur East',
       'Rathodi, Malad West', 'RP Nagar, Dharavi, Mumbai',
       'Sangam Nagar, Wadala East', 'Vidyavihar, Mumbai',
       'Aram Nagar Part 1, Andheri West', 'Bhandup East, Mumbai',
       'Chuim Village, Khar, Mumbai', 'Harbadevi, Madh, Mumbai',
       'Gorai, Mumbai', 'Yashodham, Goregaon East',
       'Lokhandwala Andheri West, Mumbai', 'Juhu, Mumbai',
       'Matunga, Mumbai', 'Malad West, Mumbai',
       'Juhu Koliwada, Santacruz', 'Pali Hill, Mumbai',
       'Hill road, Bandra West', 'Peddar Road, Mumbai',
       'Prabhadevi, Mumbai', 'Walkeshwar, Malabar Hill, Mumbai',
       'Chandivali, Mumbai', 'Bandra West, Mumbai',
       'Dahisar East, Mumbai', 'Sector 4 Charkop, Kandivali West',
       'Swastik Park, Chembur East',
       'Siddharth Nagar, Goregaon, Goregaon West', 'Mulund, Mumbai',
       'Andheri East, Mumbai', 'Swapna Nagari, Mulund West',
       'Miniland, Mumbai', 'Gamadia Colony, Tardeo, Mumbai',
       'Goregaon East, Mumbai', 'Veera Desai Road, Andheri West',
       'Kandarpada, Dahisar, Mumbai', 'Worli, Mumbai',
       'Juhu Tara, Mumbai', 'Parel, Mumbai', 'Lower Parel West, Mumbai',
       'Union Park, Pali Hill, Mumbai', 'Juhu Circle, Mumbai',
       'Versova, Andheri West', 'Madh, Mumbai', 'Yari Road, Andheri West',
       'Sector 7 Kandivali West, Mumbai',
       'Sector 5 Charkop, Kandivali West', 'Ashok Van, Dahisar, Mumbai',
       'Sahar, Andheri East', 'Chinchpada, Borivali East',
       'Sakinaka, Mumbai', 'Dharavi, Mumbai',
       'Sathi D Souza Nagar, Sakinaka, Mumbai', 'Govandi West, Mumbai',
       'Kandivali West, Mumbai', 'Byculla East, Mumbai',
       'Sion Koliwada, Mumbai', 'Kandivali, Mumbai',
       'Motilal Nagar 1, Goregaon West', 'Santacruz East, Mumbai',
       'Mulund West, Mumbai', 'Vasai fata', 'Marve Village, Malad West',
       'Borivali East, Mumbai', 'Gaikwad Nagar, Malad West',
       'Marve Road, Malad West', 'Dadar East, Mumbai',
       'Shivaji Nagar, Mumbai', 'Vikhroli West, Mumbai',
       'Fish Market Area, Andheri West', 'JVLR, Andheri East',
       'Sector 3 Charkop, Kandivali West', 'Bhatwadi, Ghatkopar',
       'Mumbai Central', 'Sewri West, Mumbai', 'Ghatkopar West, Mumbai',
       'Link Road, Mumbai', 'Kamala Nagar, Kandivali West',
       'Nandkarni Park, Wadala East', 'Band Stand, Bandra West',
       'Kataria Colony, Dadar', 'Mhada Colony, Mulund', 'Nalasopara',
       'Kapol Wadi, Ghatkopar', 'IC Colony, Borivali West',
       'Mulund East, Mumbai', 'Santacruz West, Mumbai',
       'Sector 2 Charkop, Kandivali West',
       'Mahavir Nagar, Kandivali West', 'Chembur Camp, Mumbai',
       'IIT Area, Powai', 'Vishnu Nagar, Chembur East',
       'Kanjurmarg East, Mumbai', 'Amrut Nagar, Ghatkopar',
       'Vikhroli East, Mumbai', 'Santosh Nagar, Bandra West',
       'Asalpha, Mumbai', 'Pratap Nagar, Kanjurmarg',
       'Cotton Green, Parel', 'Marol, Mumbai',
       'Dahisar Gaothan, Kandivali East',
       'Maharashtra Nagar,Mankhurd, Mumbai',
       'Kirol Village, Vidyavihar, Mumbai', 'Chembur Gaothan, Mumbai',
       'Versova Village, Andheri West', 'Bhagat Singh 2, Goregaon West',
       'Kamala Nagar, Vile Parle', 'Bander Pakhadi, Kandivali West',
       'Wadala West, Mumbai', 'GuruTeg Bahadur Nagar, Sion, Mumbai',
       'miraroad to vasai', 'Jambhulpada, Ghatkopar',
       'Malpa Dongri, Andheri East', 'Tagore Nagar, Vikhroli East',
       'Mahim West, Mumbai', 'Kandivali East, Mumbai',
       'Moti Nagar, Mulund West', 'Bangur Nagar, Goregaon West',
       'Christian Gaon, Kurla, Mumbai', 'Best Nagar, Goregaon West',
       'Vile Parle East, Mumbai', 'Trombay, Mumbai', 'kalyan city Thane',
       'Ekta Nagar, Malad West', 'Mahim, Mumbai',
       'Air Force Quarters, Sion, Mumbai',
       'Navneeth Colony, Andheri West', 'Orlem, Malad West',
       'Sardar Vallabhbhai Patel Nagar, Mumbai',
       'Kamgar Nagar, Kurla, Mumbai', 'Govandi East, Mumbai',
       'Mata Ramabai Ambedkar Nagar, Bhandup West',
       'Kolivery Village, Santacruz East', 'Grant Road East, Mumbai',
       'Aarey Milk Colony, Goregaon East', 'Janata Colony, Jogeshwari',
       'Daulat Nagar, Borivali East', 'Mankhurd, Mumbai',
       'Chembur West, Mumbai', 'Royal Palms, Goregaon East',
       'Behram Baug, Jogeshwari', 'room no 532', 'Byculla, Mumbai',
       'sainath nagar, virar east,', 'Damle Colony, Kanjurmarg East',
       'Janata Nagar, Kandivali East', 'Juhu Scheme, Mumbai',
       'Borivali West gorai sector 2', 'Antop Hill, Mumbai',
       'Sion, Mumbai', 'Vakola, Santacruz East',
       'Tulshetpada, Bhandup West', 'Singh Agri Estate, Kandivali East',
       'Kurla East, Mumbai', 'aarey colony unit no 31',
       'Gorai 1, Borivali West', 'Dev Nagar, Borivali West',
       'Odhav Nagar, Borivali East', 'BS Ambedkar Nagar, Chembur East',
       'Ganesh Murti Nagar', 'Gautam Nagar, Borivali West',
       'Ghodapdeo, Byculla, Mumbai', 'Vile Parle West, Mumbai',
       'Ganesh Nagar, Chembur East', 'Keshav Pada, Mulund West',
       'Jankalyan Nagar, Malad West', 'Bhakti Palace, Dahisar, Mumbai',
       'Mohamed Ali Road, Mumbai', 'Sundervan Complex, Andheri West',
       'Laxmi Colony, Chembur East', 'Barve Nagar, Ghatkopar',
       'Mazgaon, Mumbai', 'meroli ward no 6',
       'Western Railway Colony, Borivali East, Dahisar, Mumbai',
       'Matunga East, Mumbai', 'Vikhroli Park Site, Mumbai',
       'Tirandaz, Vikhroli', 'Vidya Nagari, Santacruz East',
       'Western Railway Colony, Matunga, Mumbai',
       'Ramabai Ambedkar Nagar, Mumbai', 'SEEPZ, Andheri East',
       'Badhwar Park, Colaba, Mumbai', 'Battipada, Bhandup West',
       'Bhandup, Mumbai', 'Indira Nagar, Chembur',
       'Divya Park, Malad West', 'LBS Marg, Mumbai', 'Dadar West, Mumbai',
       'Jari Mari, Sakinaka, Mumbai', 'Sion East, Mumbai',
       'Jogeshwari East, Mumbai', 'Aram Nagar Part 2, Andheri West',
       'Jai Bhim Nagar, Goregaon East', 'Panchkutir Ganesh Nagar, Powai',
       'Dongri, Umerkhadi, Mumbai', 'Bandra Kurla Complex, Mumbai',
       'Kurla West, Mumbai', 'Bhawani Sankar, Dadar', 'Kherwadi, Bandra',
       'Acc Nagar, Chedda Nagar, Mumbai',
       'Gokuldham Colony, Goregaon East', 'Devidas Road',
       'Masjid Bandar, Mumbai', 'Sathe Nagar, Wadala',
       'Malad East, Mumbai', 'Jvpd Scheme, Vile Parle',
       'Lokhandwala Complex, Andheri West', 'Dadar, Mumbai',
       'Lalbaug, Parel', 'Khalai Village, Vidyavihar, Mumbai',
       'MMRDA Area, Santacruz East', 'Chirag Nagar, Ghatkopar',
       'Vidyavihar East, Mumbai', 'Ambivali, Jogeshwari',
       'Ghorale,Kishore Village', 'Seawoods, Navi Mumbai', 'Khopoli',
       'Virar West, Mumbai', 'Adaigaon, Navi Mumbai',
       'Dombivli East, Thane', 'Sector 1A Kopar Khairane',
       'Virathan Khurd', 'Vasant Vihar, Thane West', 'Vasai West, Mumbai',
       'Naigaon East, Mumbai', 'Adharwadi, Kalyan West',
       'Sector 8 Belapur, Navi Mumbai', 'Kalyan West, Thane',
       'Manpada, Thane', 'Bhiwandi, Thane',
       'Sector 12 Kharghar, Navi Mumbai', 'Chikhal Dongari, Virar West',
       'Sector 1 Kopar Khairane', 'Bhavani Nagar, Thane West',
       'Kasar Vadavali, Thane', 'Mira Road, Mira Bhayandar',
       'Sector 11 New Panvel, Navi Mumbai', 'Pisavli, Kalyan',
       'Devad, Vichumbe, Navi Mumbai', 'Vasai East, Mumbai',
       'Kashimira, Mira Road East',
       'Artist Village, Belapur, Navi Mumbai', 'Majiwada, Thane',
       'Titwala, Thane', 'Neral, Thane', 'Murbad, Thane',
       'Sector 6 New Panvel, Navi Mumbai', 'Malad, Thane Outskirts',
       'Arjunali, Thane', 'Shahad, Ulhasnagar, Thane',
       'New Panvel East, Navi Mumbai', 'Koliwada, Vasai, Mumbai',
       'Parshiwadi Varachi, Thane East', 'New Colony, Ambernath',
       'Rameshwadi, Badlapur', 'Badlapur East, Thane',
       'Sonar Pada, Dombivli East', 'Ghansoli, Navi Mumbai',
       'Rabodi Koliwada, Thane West', 'Chinchoti, Mumbai',
       'Nagsen Nagar, Mumbra, Thane', 'Sector 17 Nerul, Navi Mumbai',
       'Sector 8B Belapur, Navi Mumbai',
       'Sector 8 Kalamboli, Navi Mumbai', 'Owale, Ghodbunder Road',
       'Nagaon, Uran, Navi Mumbai', 'Khadavali, Thane',
       'Wagle Estate, Thane West', 'Ghodbunder Road, Thane',
       'OT Section, Ulhasnagar, Thane',
       'Dhakate Shahad, Ulhasnagar, Thane',
       'Nilemore, Nalasopara, Mumbai', 'Khadegolwali, Ulhasnagar, Thane',
       'Tisgao Naka, Kalyan', 'Ambernath West, Thane',
       'Sopara, Nalasopara, Mumbai', 'Bolinj, Virar West',
       'Karanjade, Navi Mumbai', 'Panch Pakhadi, Thane West',
       'Khatiwali, Thane', 'Sector 8 Kopar Khairane',
       'Vajreshwari, Thane', 'Rabale, Navi Mumbai',
       'Khemani Industry Area, Ulhasnagar, Thane', 'Kavesar, Thane West',
       'Lodha Heaven, Dombivli East', 'Sector 7 Kopar Khairane',
       'Badlapur West, Thane', 'Valivali Gaon, Badlapur',
       'Ambernath, Thane', 'JK Gram, Thane West', 'Badlapur, Thane',
       'Beturkar Pada, Kalyan West', 'Airoli, Navi Mumbai',
       'Uttan, Mira Bhayandar', 'Ulhasnagar, Thane',
       'Sector 8 Kharghar, Navi Mumbai', 'Panvel, Navi Mumbai',
       'Karjat, Thane', 'Sector 6 Vashi, Navi Mumbai',
       'Nilje Gaon, Thane', 'Old Panvel, Navi Mumbai',
       'Belapur, Navi Mumbai', 'Parnaka, Vasai, Mumbai',
       'New Panvel, Navi Mumbai', 'Brahmand, Thane West',
       'Sector 2 New Panvel, Navi Mumbai',
       'Sector 1 New Panvel, Navi Mumbai', 'Kharghar, Navi Mumbai',
       'Sector 8 Vashi, Navi Mumbai', 'Thane West',
       'Savarkar Nagar, Thane West', 'Louis Wadi, Thane West',
       'Sector 9 Nerul, Navi Mumbai',
       'Sector 24 CBD Belapur, Navi Mumbai',
       'Sector 20 Kharghar, Navi Mumbai', 'Belavali, Badlapur',
       'AG Nagar, Mira Road East', 'Sector 12 New Panvel East',
       'Wagholi, Nalasopara, Mumbai', 'Khanda, Neral, Thane',
       'Sector 7 Airoli, Navi Mumbai', 'Kelve', 'Yashwant Naga',
       'Nirmal, Nalasopara, Mumbai', 'Sector 18 Kopar Khairane',
       'Hiranandani Meadows, Manpada', 'Balkum, Thane',
       'Sector 21 Kharghar, Navi Mumbai', 'Pokhran 2, Thane',
       'Waghbil, Thane West', 'Sector 10 Kopar Khairane',
       'Samata Nagar, Thane West', 'Sector 14 Vashi, Navi Mumbai',
       'Vasai, Mumbai', 'Sector 4 Ghansoli, Navi Mumbai',
       'Sector 15 Vashi, Navi Mumbai', 'Sector 17 Kopar Khairane',
       'Sonivali, Badlapur', 'Khandeshhwar, Panvel',
       'Mira Road East, Mira Bhayandar', 'khopat, Thane West',
       'Rasayani, Navi Mumbai', 'Khalapur, Navi Mumbai',
       'Dronagiri, Navi Mumbai', 'Taloja, Navi Mumbai',
       'Pushpak Nagar, Navi Mumbai', 'Palaspa, Panvel',
       'Kanakia Park, Mira Road East', 'kelve east',
       'Sector 15 Kopar Khairane', 'Sector 6 Nerul, Navi Mumbai',
       'Sector 28 Vashi, Navi Mumbai', 'Sector 29 Vashi, Navi Mumbai',
       'Kopar Khairane, Navi Mumbai', 'Sector 2 Kopar Khairane',
       'Palaspe Phata, Panvel', 'Sector 21 Nerul, Navi Mumbai',
       'Bhayandar East, Mira Bhayandar', 'Vashi, Navi Mumbai',
       'Kalamboli, Navi Mumbai', 'Hawaiian Village, Thane West',
       'Sector 4 New Panvel, Navi Mumbai',
       'Sector 35E Kharghar, Navi Mumbai',
       'Sector 16 Ghansoli, Navi Mumbai',
       'Ghotkamp Koyana Vele, Navi Mumbai', 'Kolshet, Thane West',
       'Ulwe, Navi Mumbai', 'Sector 14 Roadpali, Kalamboli',
       'Prabhu Ali, Bhiwandi, Thane', 'Kachore Gaon, Kalyan',
       'Sector 4 Kopar Khairane', 'Nerul, Navi Mumbai',
       'Sector 21 Ulwe, Navi Mumbai', 'Nalasopara East, Mumbai',
       'Vangani, Thane', 'Nere, Navi Mumbai', 'Manda, Titwala, Thane',
       'Virar, Mumbai', 'Baneli, Thane', 'Bapuji Nagar, Thane West',
       'Ulhasnagar', 'Rai Village, Mira Bhayandar',
       'Mumbai Nashik Highway, Thane', 'Kegaon, Uran, Navi Mumbai',
       'Kalyan East, Thane', 'Sector 13 New Panvel East, Navi Mumbai',
       'Sector 6 Kharghar, Navi Mumbai', 'Vartak Nagar, Thane West',
       'Chandeni Koliwada, Thane East', 'Kalyan, Thane',
       'Dombivli West, Thane', 'Sector 7 Vashi, Navi Mumbai',
       'Manjarli, Badlapur', 'Anjurdive, Thane',
       'Chinchpada Gaon, Kalyan', 'Mumbra, Thane',
       'Sector 16 Airoli, Navi Mumbai', 'Holi Bazaar, Vasai, Mumbai',
       'Samel Pada, Nalasopara, Mumbai', 'Cidco Colony, Airoli',
       'Umesh Nagar, Dombivli', 'Shahapur, Thane',
       'Block G Sector 12 Kharghar, Navi Mumbai', 'Vichumbe, Navi Mumbai',
       'Juchandra, Naigaon East, Mumbai', 'Gandhi Nagar, Thane West',
       'Sector 12', 'Maratha Section 32, Ulhasnagar, Thane',
       'Mariam Nagar, Naigaon West, Mumbai', 'Golavli, Dombivli East',
       'Manda West, Titwala, Thane', 'Housing Board Colony, Ambernath',
       'Shahpur, Thane', 'Lonad, Thane', 'Deodal, Mumbai',
       'Sector 16 Nerul, Navi Mumbai', 'Kulgaon, Badlapur East',
       'Ambivli', 'Lokmanya Nagar, Thane West',
       'Sector 10 Sanpada, Navi Mumbai', 'Deepak Nagar, Ambernath',
       'Rajaram Nagar, Kalyan', 'Sector 16 Kalamboli, Navi Mumbai',
       'Nalasopara West, Mumbai', 'Manickpur, Vasai, Mumbai',
       'MIDC Residential Area, Dombivli East',
       'Vijay Nagar, Nalasopara, Mumbai', 'Mhada Colony, Badlapur East',
       'Dahivali, Thane', 'Ambernath East, Thane'], dtype=object)

In [33]:
location_map = {
'andheri':['andheri','versova','yari road','lokhandwala','veera desai','azad nagar','aram nagar','seven bunglow','sundervan complex','fish market area','juhu lane','mahakali caves','marol','sahar','seepz','malpa dongri','navneeth colony','behram baug'],
'bandra':['bandra','pali hill','band stand','kherwadi','santosh nagar','hill road','bandra kurla complex','bkc'],
'borivali':['borivali','ic colony','eksar','gorai','kajupada','ashtavinayak nagar','gautam nagar','dev nagar','odhav nagar','daulat nagar'],
'bhandup':['bhandup','nahur','kanjur village','kanjurmarg','tembhipada','tulshetpada','battipada','tata nagar'],
'chembur':['chembur','deonar','mysore colony','swastik park','vishnu nagar','chembur camp','chembur gaothan','bs ambedkar nagar','laxmi colony','indira nagar','acc nagar'],
'dadar':['dadar','kataria colony','bhawani sankar'],
'dahisar':['dahisar','ashok van','kandarpada','bhakti palace'],
'ghatkopar':['ghatkopar','chirag nagar','amrut nagar','barve nagar','bhatwadi','kapol wadi','jambhulpada'],
'goregaon':['goregaon','motilal nagar','bangur nagar','best nagar','bhagat singh','yashodham','royal palms','aarey','gokuldham colony','jai bhim nagar'],
'jogeshwari':['jogeshwari','ambivali','janata colony'],
'juhu':['juhu','jvpd','juhu tara','juhu koliwada','juhu scheme','juhu circle'],
'kandivali':['kandivali','charkop','mahavir nagar','samata nagar','irani wadi','kamala nagar','bander pakhadi','singh agri estate','janata nagar'],
'khar':['khar','chuim village'],
'kurla':['kurla','hallow pul','kamgar nagar','christian gaon'],
'malad':['malad','malvani','marve','orlem','rani sati nagar','ekta nagar','gaikwad nagar','jankalyan nagar','divya park'],
'mulund':['mulund','veena nagar','swapna nagari','moti nagar','keshav pada','mulund colony'],
'powai':['powai','hiranandani gardens','iit area','panchkutir ganesh nagar','chandivali'],
'santacruz':['santacruz','kalina','vakola','kolivery village','mmrda area','vidya nagari'],
'sion':['sion','guru teg bahadur nagar','air force quarters','sion koliwada'],
'vikhroli':['vikhroli','tagore nagar','tirandaz','park site'],
'vile parle':['vile parle','kamala nagar'],
'wadala':['wadala','sathe nagar','nandkarni park'],
'worli':['worli'],
'parel':['parel','lalbaug','cotton green'],
'colaba':['colaba','badhwar park'],
'byculla':['byculla','ghodapdeo'],
'mankhurd':['mankhurd','mandala'],
'matunga':['matunga'],
'mahim':['mahim'],
'mumbai central':['mumbai central'],
'panvel':['panvel','new panvel','old panvel','palaspa','palaspe phata','khandeshhwar'],
'kharghar':['kharghar'],
'kopar khairane':['kopar khairane'],
'ghansoli':['ghansoli'],
'vashi':['vashi'],
'nerul':['nerul'],
'belapur':['belapur'],
'ulwe':['ulwe'],
'kalamboli':['kalamboli','roadpali'],
'taloja':['taloja'],
'airoli':['airoli'],
'thane':['thane west','thane east','manpada','majiwada','wagle estate','lokmanya nagar','vartak nagar','pokhran','kavesar','balkum','brahmand','ghodbunder road','samata nagar','louis wadi'],
'kalyan':['kalyan','adharwadi','pisavli','tisgao naka','kachore gaon','rajaram nagar'],
'dombivli':['dombivli','sonar pada','golavli','umesh nagar'],
'badlapur':['badlapur','belavali','manjarli','rameshwadi'],
'ulhasnagar':['ulhasnagar','shahad'],
'ambernath':['ambarnath','ambernath'],
'vasai':['vasai','manickpur','parnaka','holi bazaar'],
'virar':['virar','bolinj'],
'nalasopara':['nalasopara','sopara','samel pada','nirmal'],
'mira road':['mira road','mira bhayandar','bhayandar','kashimira'],
'bhiwandi':['bhiwandi'],
'karjat':['karjat'],
'khopoli':['khopoli'],
'titwala':['titwala'],
'murbad':['murbad']
}

import re

def clean_location(loc):

    if pd.isna(loc):
        return np.nan

    loc = loc.lower().strip()

    loc = re.sub(r'\b(east|west|north|south)\b', '', loc)

    loc = " ".join(loc.split())

    for main_area, keywords in location_map.items():

        for word in keywords:

            if word in loc:
                return main_area.title()

    return loc.split(',')[0].title()


df1['address'] = df1['address'].apply(clean_location)

In [34]:
df1['address'].nunique()

151

In [35]:
df1.head()

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,bhk,area_sqft,area_type
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,13333.0,1,1,0,Bhandup,2 floors total,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1.0,150.0,plot
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,63157.0,2,2,0,Sion,1 floors total,NaN,10-20 Years Old / Under Construction,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2.0,950.0,plot
2,"5 Bedroom House in Juhu Lane, Andheri West",25.0,89285.0,5,3,2,Andheri,1 floors total,North,5-10 Years Old / Ready to Move,Standard chartered ATM (ATM) | Jeevan Jyot Med...,"Located in juhu lane, andheri west, this furni...","Furnished (Modular Kitchen, Refrigerator, Bed,...",North Facing | Corner Property | Overlooking M...,O,5.0,2800.0,plot
3,"4 Bedroom House in Chembur East, Mumbai",8.0,27586.0,4,4,0,Chembur,3 floors total,NaN,5-10 Years Old / Ready to Move,bhaji & machhi market (Shopping) | Shanni Mand...,We are proud owners of house/villa available f...,NaN,NaN,O,4.0,2900.0,buildup
4,"3 Bedroom House in Nahur East, Bhandup",10.7,44583.0,3,2,1,Bhandup,2 floors total,North-East,10-20 Years Old / Under Construction,Bethesda Church TATA COUNTY (Religious Place) ...,Available due to owner relocating overseas. \n...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Water Storage | Piped Gas |...,O,3.0,1550.0,plot

## noOfFloor

In [36]:
df1['noOfFloor'].unique()

array(['2 floors total', '1 floors total', '3 floors total',
       '23 floors total', nan, '7 floors total', '21 floors total',
       '4 floors total', '0 floors total', '18 floors total',
       '20 floors total', '6 floors total', '78 floors total',
       '12 floors total', '16 floors total', '19 floors total',
       '10 floors total', '35 floors total', '43 floors total',
       '11 floors total', '80 floors total', '5 floors total',
       '15 floors total', '13 floors total', '8 floors total',
       '9 floors total', '30 floors total', '32 floors total',
       '40 floors total', '14 floors total'], dtype=object)

In [37]:
df1['noOfFloor'].isna().sum()

np.int64(74)

In [38]:
df1['noOfFloor'] = df1['noOfFloor'].str.split(" ").str.get(0).astype(float)

In [39]:
# Here  filling empty values of floors, based on bedrooms
df1['noOfFloor'] = df1.groupby('bedRoom')['noOfFloor'].transform(lambda x: x.fillna(x.median()))
df1['noOfFloor'] = df1['noOfFloor'].astype(int)

In [40]:
df1.head()

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,bhk,area_sqft,area_type
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,13333.0,1,1,0,Bhandup,2,NaN,10-20 Years Old / Under Construction,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1.0,150.0,plot
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,63157.0,2,2,0,Sion,1,NaN,10-20 Years Old / Under Construction,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2.0,950.0,plot
2,"5 Bedroom House in Juhu Lane, Andheri West",25.0,89285.0,5,3,2,Andheri,1,North,5-10 Years Old / Ready to Move,Standard chartered ATM (ATM) | Jeevan Jyot Med...,"Located in juhu lane, andheri west, this furni...","Furnished (Modular Kitchen, Refrigerator, Bed,...",North Facing | Corner Property | Overlooking M...,O,5.0,2800.0,plot
3,"4 Bedroom House in Chembur East, Mumbai",8.0,27586.0,4,4,0,Chembur,3,NaN,5-10 Years Old / Ready to Move,bhaji & machhi market (Shopping) | Shanni Mand...,We are proud owners of house/villa available f...,NaN,NaN,O,4.0,2900.0,buildup
4,"3 Bedroom House in Nahur East, Bhandup",10.7,44583.0,3,2,1,Bhandup,2,North-East,10-20 Years Old / Under Construction,Bethesda Church TATA COUNTY (Religious Place) ...,Available due to owner relocating overseas. \n...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Water Storage | Piped Gas |...,O,3.0,1550.0,plot

In [41]:
df1.drop(columns=['facing'], inplace=True)

## agePossession

In [42]:
df1['agePossession'].unique()

array(['10-20 Years Old / Under Construction',
       '5-10 Years Old / Ready to Move', '0-1 Year Old / 0-1 Year Old',
       '1-5 Years Old / 1-5 Years Old', nan, 'New Construction',
       '20+ Years Old / Under Construction'], dtype=object)

In [43]:
df1['agePossession'].isna().sum()

np.int64(44)

In [44]:
def parse_age_possession(val):
    if pd.isna(val):
        return np.nan, np.nan

    parts = str(val).split('/')
    age = parts[0].strip()
    possession = parts[1].strip() if len(parts) > 1 else age

    return age, possession

df1[['property_age', 'possession_status']] = df1['agePossession'].apply(
    lambda x: pd.Series(parse_age_possession(x))
)
df1.drop(columns=['agePossession'], inplace=True)

In [45]:
df1.sample(2)

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,address,noOfFloor,nearbyLocations,description,furnishDetails,features,rating,bhk,area_sqft,area_type,property_age,possession_status
585,Santacruz East Hanuman Tekdi gate no 1,0.20,10000.0,1,1,0,Santacruz,1,Umar Masjid (Religious Place) | Cross INRI (Re...,This is sra chowl property future re developme...,NaN,NaN,O,1.0,200.0,plot,10-20 Years Old,Under Construction
912,Nisarg Highway Touch,0.85,2833.0,2,3,4,Neral,2,Aayush Nursing Home (Hospital) | Sai Hospital ...,Welcome to nisargs constructions our company w...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Solar Panels | Water Storag...,A,2.0,3000.0,plot,0-1 Year Old,0-1 Year Old

In [46]:
print(df1['property_age'].value_counts())
print(df1['possession_status'].value_counts())

property_age
10-20 Years Old     501
0-1 Year Old        225
5-10 Years Old      211
1-5 Years Old       180
New Construction      1
20+ Years Old         1
Name: count, dtype: int64
possession_status
Under Construction    502
0-1 Year Old          225
Ready to Move         211
1-5 Years Old         180
New Construction        1
Name: count, dtype: int64

In [47]:
possession_map = {
    'Ready to Move'  : 'Ready to Move',
    'Under Construction' : 'Under Construction',
    '0-1 Year Old'   : 'Ready to Move',
    '1-5 Years Old'  : 'Ready to Move',
    'New Construction': 'Ready to Move'
}
df1['possession_status'] = df1['possession_status'].replace(possession_map)

In [48]:
# filling with most frequent value
df1['property_age'] = df1['property_age'].fillna(df1['property_age'].mode()[0])
df1['possession_status'] = df1['possession_status'].fillna(df1['possession_status'].mode()[0])

In [49]:
df1['bhk'] = df1['bhk'].astype(int)

In [50]:
df1.head()

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,address,noOfFloor,nearbyLocations,description,furnishDetails,features,rating,bhk,area_sqft,area_type,property_age,possession_status
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,13333.0,1,1,0,Bhandup,2,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1,150.0,plot,10-20 Years Old,Under Construction
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,63157.0,2,2,0,Sion,1,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2,950.0,plot,10-20 Years Old,Under Construction
2,"5 Bedroom House in Juhu Lane, Andheri West",25.0,89285.0,5,3,2,Andheri,1,Standard chartered ATM (ATM) | Jeevan Jyot Med...,"Located in juhu lane, andheri west, this furni...","Furnished (Modular Kitchen, Refrigerator, Bed,...",North Facing | Corner Property | Overlooking M...,O,5,2800.0,plot,5-10 Years Old,Ready to Move
3,"4 Bedroom House in Chembur East, Mumbai",8.0,27586.0,4,4,0,Chembur,3,bhaji & machhi market (Shopping) | Shanni Mand...,We are proud owners of house/villa available f...,NaN,NaN,O,4,2900.0,buildup,5-10 Years Old,Ready to Move
4,"3 Bedroom House in Nahur East, Bhandup",10.7,44583.0,3,2,1,Bhandup,2,Bethesda Church TATA COUNTY (Religious Place) ...,Available due to owner relocating overseas. \n...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Water Storage | Piped Gas |...,O,3,1550.0,plot,10-20 Years Old,Under Construction

In [63]:
df1['nearby_loc_count'] = df1['nearbyLocations'].apply(lambda x: len(str(x).split('|')) if pd.notna(x) else 0)

In [64]:
df1.head()

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,address,noOfFloor,nearbyLocations,description,furnishDetails,features,rating,bhk,area_sqft,area_type,property_age,possession_status,nearby_loc_count
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,13333.0,1,1,0,Bhandup,2,Sonapur Market (Shopping) | Vitthal Temple (Re...,"This 1 bhk independent house in tembhipada, bh...",NaN,NaN,O,1,150.0,plot,10-20 Years Old,Under Construction,5
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,63157.0,2,2,0,Sion,1,NaN,Accessibility to everything . Centre of south ...,Unfurnished,Close to School | Close to Hospital | Close to...,O,2,950.0,plot,10-20 Years Old,Under Construction,0
2,"5 Bedroom House in Juhu Lane, Andheri West",25.0,89285.0,5,3,2,Andheri,1,Standard chartered ATM (ATM) | Jeevan Jyot Med...,"Located in juhu lane, andheri west, this furni...","Furnished (Modular Kitchen, Refrigerator, Bed,...",North Facing | Corner Property | Overlooking M...,O,5,2800.0,plot,5-10 Years Old,Ready to Move,5
3,"4 Bedroom House in Chembur East, Mumbai",8.0,27586.0,4,4,0,Chembur,3,bhaji & machhi market (Shopping) | Shanni Mand...,We are proud owners of house/villa available f...,NaN,NaN,O,4,2900.0,buildup,5-10 Years Old,Ready to Move,5
4,"3 Bedroom House in Nahur East, Bhandup",10.7,44583.0,3,2,1,Bhandup,2,Bethesda Church TATA COUNTY (Religious Place) ...,Available due to owner relocating overseas. \n...,"Furnished (Lights, Fans, AC, TV, Bed, Wardrobe...",Reserved Parking | Water Storage | Piped Gas |...,O,3,1550.0,plot,10-20 Years Old,Under Construction,5

In [67]:
df1.drop(columns=['description', 'nearbyLocations'], inplace=True)

## furnishing

In [76]:
def furnishDetail(text):
    if pd.isna(text): return "Unknown"

    text_lower = text.lower()

    if "unfurnished" in text_lower:
        return "Unfurnished"
    elif "semi-furnished" in text_lower:
        return "Semi Furnished"
    elif "furnished" in text_lower:
        return "Furnished"
    else:
        return "Unknown"

df1['furnishDetails'] = df1['furnishDetails'].apply(furnishDetail)

## features

In [77]:
df1['features']

0                                                     NaN
1       Close to School | Close to Hospital | Close to...
2       North Facing | Corner Property | Overlooking M...
3                                                     NaN
4       Reserved Parking | Water Storage | Piped Gas |...
                              ...
1158    Solar Panels | Club House | Intercom | ATM | I...
1159                                                  NaN
1160                                                  NaN
1161                                                  NaN
1162                                                  NaN
Name: features, Length: 1163, dtype: object

In [82]:
df1['feature_count'] = df1['features'].apply(lambda x: len(str(x).split('|')) if pd.notna(x) else 0)
df1.drop(columns=['features'], inplace=True)

In [83]:
df1.head()

,property_name,price,rate_per_sqft,bedRoom,bathroom,balcony,address,noOfFloor,furnishDetails,rating,bhk,area_sqft,area_type,property_age,possession_status,nearby_loc_count,feature_count
0,"1 Bedroom House in Tembhipada, Bhandup West",0.2,13333.0,1,1,0,Bhandup,2,Unknown,O,1,150.0,plot,10-20 Years Old,Under Construction,5,0
1,"2 Bedroom House in Zaver Mansion Bungalow, Mum...",6.0,63157.0,2,2,0,Sion,1,Unfurnished,O,2,950.0,plot,10-20 Years Old,Under Construction,0,3
2,"5 Bedroom House in Juhu Lane, Andheri West",25.0,89285.0,5,3,2,Andheri,1,Furnished,O,5,2800.0,plot,5-10 Years Old,Ready to Move,5,4
3,"4 Bedroom House in Chembur East, Mumbai",8.0,27586.0,4,4,0,Chembur,3,Unknown,O,4,2900.0,buildup,5-10 Years Old,Ready to Move,5,0
4,"3 Bedroom House in Nahur East, Bhandup",10.7,44583.0,3,2,1,Bhandup,2,Furnished,O,3,1550.0,plot,10-20 Years Old,Under Construction,5,17

## rating

In [86]:
df1['rating'].value_counts()

rating
O      643
A      485
3.7     15
3.8      9
4.1      3
3.9      2
4.3      2
4        1
4.2      1
3.1      1
3.4      1
Name: count, dtype: int64

In [88]:
rating_map = {
    'O': 5,
    'A': 4
}

def parse_rating(val):
    if pd.isna(val): return np.nan
    if val in rating_map: return rating_map[val]
    try: return float(val)
    except: return np.nan

df1['rating'] = df1['rating'].apply(parse_rating)

In [90]:
df1.drop(columns='property_name', inplace=True)

In [91]:
df1.to_csv("cleaned_independent_house.csv",index=False)