In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/real_estate_main.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DS/DataSets/mumbai_flats.csv')

df1_copy = df1.copy()
df2_copy = df2.copy()

In [ ]:
df1.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat in Kandivali West, Mumbai",Amity Global Business School (1.5 Km) [Univers...,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat in Vile Parle, Mumbai",Vile Parle Railway Station (0.8 km) [Railway S...,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat in Andheri East, Mumbai",JB Nagar Metro Station (4 mins) [Metro Station...,Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat in Chembur, Mumbai",St Gregorios Primary School (1.1 Km) [School] ...,"21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat in Govandi, Mumbai",National Highway 48 (1.9 Km) [Highway] | Chemb...,Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [ ]:
df2.head()

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...
1,1 BHK Flat,19.0 L,"Ananta Vardhman Nagar, Tembhode, Palghar, Mumbai",630 sq.ft,₹3.02 K/sq.ft,3 Year Old,Ready to move,Middleof 4 floors,Unfurnished,NaN,Ananta Vardhman Nagar,No ChargeAccess Zero Brokerage Properties,390 sq.ft,1,1,2,1 Open Parking,"1 BHK Flat for sale in Palghar, Mumbai - conta..."
2,1 BHK Flat,73.0 L,"JP North Barcelona, Kashimira, Mira Road East,...",580 sq.ft,₹12.59 K/sq.ft,1 Years Old,Ready to move,Lowerof 25 floors,Semi Furnished,NaN,JP North Barcelona,1.5 LacsAccess Zero Brokerage Properties,475 sq.ft,1,2,2,No Parking,1 BHK Flat for sale in Mumbai. This property i...
3,1 BHK Flat,1.1 Cr,"Chandak Nischay, Ambawadi, Dahisar East, Mumbai",410 sq.ft,₹26.83 K/sq.ft,1 Years Old,Ready to move,Higherof 35 floors,Semi Furnished,NaN,Chandak Nischay,1.1 LacsAccess Zero Brokerage Properties,368 sq.ft,1,2,1,2 Covered Parking,Check out this 1 BHK Flat for sale in Dahisar ...
4,3 BHK Flat,2.25 Cr,"Neelam Solstice Phase I, Nalanda Nagar, Ramaba...",1052 sq.ft,₹21.39 K/sq.ft,1 Years Old,Ready to move,Lowerof 26 floors,Semi Furnished,NaN,Neelam Solstice Phase I,2.1 LacsAccess Zero Brokerage Properties,915 sq.ft,3,2,3,1 Covered Parking,"Situated in ghatkopar east, central mumbai sub..."

In [ ]:
df1['NearbyLocations'].isna().value_counts()

NearbyLocations
False    437
True      66
Name: count, dtype: int64

In [ ]:
df1.drop(columns='NearbyLocations', inplace=True)

In [ ]:
df1.sample(5)

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
282,Courtyard,"2, 3 BHK Flat in Santacruz East, Mumbai",Stunning infinity pool with panoramic city vie...,https://www.99acres.com/courtyard-santacruz-ea...,Rs. 1.94 - 3.02 Cr,Pet Area | Swimming Pool
190,Ajmera Greenfinity,"1, 2, 3 BHK Flat in Wadala East, Mumbai",Project Directly Connected To Mono Rail and Ea...,https://www.99acres.com/ajmera-greenfinity-wad...,Rs. 1.43 - 3 Cr,Park / Garden
74,Puneet Amarjyoti,"1, 2 BHK Flat in Vikhroli East, Mumbai",Private balconies offering serene garden views...,https://www.99acres.com/puneet-amarjyoti-vikhr...,Rs. 96 L - 1.21 Cr,Spa | Pet Area | Park / Garden
374,CCI Rivali Park Stargaze,"2, 3 BHK Flat in Magathane, Borivali East","Directly facing the expansive 22,000-acre Sanj...",https://www.99acres.com/cci-rivali-park-starga...,Rs. 1.84 - 3.14 Cr,Park / Garden | Pet Area
73,Puneet Shivalaya,"1 BHK Flat in Tagore Nagar, Vikhroli East",Walking distance from Vikhroli Railway Station...,https://www.99acres.com/puneet-shivalaya-tagor...,Rs. 90.29 L,Pet Area | Lift

In [ ]:
df1.columns= df1.columns.str.strip().str.lower().str.replace(' ', '_')

In [ ]:
df1['propertysubname'].isna().value_counts()

propertysubname
False    503
Name: count, dtype: int64

In [ ]:
df1['propertysubname'] = df1['propertysubname'].str.split("in").str.get(0)

In [ ]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area

In [ ]:
# Clean the list by stripping whitespace and removing empty strings
df1['bhk_list'] = df1['propertysubname'].str.replace(" BHK Flat","").str.strip().str.split(",")
display(df1[['propertysubname','bhk_list']].head())

     propertysubname     bhk_list
0  1, 2, 3 BHK Flat   [1,  2,  3]
1  2, 3, 4 BHK Flat   [2,  3,  4]
2     1, 2 BHK Flat       [1,  2]
3  2, 3, 4 BHK Flat   [2,  3,  4]
4     1, 2 BHK Flat       [1,  2]

In [ ]:
df1['bhk_list'].value_counts()

bhk_list
[2,  3]                    125
[1,  2]                     86
[1,  2,  3]                 61
[2,  3,  4]                 53
[2]                         35
[3,  4]                     33
[1,  2,  3,  4]             19
[3]                         17
[3,  4,  5]                 15
[1]                         14
[4]                         11
[2,  3,  4,  5]             10
[4,  5]                      4
[2,  4]                      3
[3,  4,  5,  6]              3
[4,  6]                      2
[3,  4,  6]                  2
[1,  3]                      1
[2,  3,  4,  5,  6,  7]      1
[5]                          1
[2,  3,  4,  5,  6]          1
[5,  6,  7]                  1
[1,  2,  3,  4,  5]          1
[1,  3,  4]                  1
[3,  5]                      1
[1,  2,  4]                  1
[2,  3,  5]                  1
Name: count, dtype: int64

In [ ]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]"
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]"
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]"
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]"
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]"

In [ ]:
df1[df1['propertyname']=='Srushtiraj Siddhi Square']

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list
162,Srushtiraj Siddhi Square,1 BHK Flat,Sophisticated Modern Architecture | Vastu-Comp...,https://www.99acres.com/srushtiraj-siddhi-squa...,Rs. 80 - 92.5 L,Pet Area | Vaastu Compliant,[1]

In [ ]:
def parse_price(text):
    # 1. Clean the string and split into min/max
    text = str(text).replace('Rs. ', '').strip()
    parts = text.split(' - ') if ' - ' in text else [text, text]

    clean_prices = []
    for p in parts:
        # Extract the number from the string
        num = float(''.join(c for c in p if c.isdigit() or c == '.'))

        # Convert Lakh to Crore (e.g. 80 -> 0.8)
        # We check if 'L' is in the part or if the whole text is Lakh-based
        if 'L' in p or ('Cr' not in p and 'L' in text):
            num = round(num / 100, 2)

        clean_prices.append(num)
    return clean_prices

# Apply conversion to get numeric min/max columns
df1[['min_price', 'max_price']] = df1['pricedetails'].apply(parse_price).tolist()

# 3. Create the expanded dataset (one row per BHK type)
new_rows = []
for i, row in df1.iterrows():
    # Get BHK numbers (e.g. "1, 2")
    bhk_names = row['propertysubname'].replace('BHK Flat', '').split(',')

    # Spread prices linearly between min and max
    bhk_count = len(bhk_names)
    bhk_prices = np.linspace(row['min_price'], row['max_price'], bhk_count)

    for name, price in zip(bhk_names, bhk_prices):
        new_row = row.copy()
        new_row['propertysubname'] = name.strip() + " BHK Flat"
        new_row['pricedetails'] = round(price, 2)
        new_rows.append(new_row)

new_df = pd.DataFrame(new_rows)

# Show result for the specific apartment mentioned
display(new_df[new_df['propertyname'] == 'Srushtiraj Siddhi Square'][['propertyname', 'propertysubname', 'pricedetails', 'min_price', 'max_price']])

,propertyname,propertysubname,pricedetails,min_price,max_price
162,Srushtiraj Siddhi Square,1 BHK Flat,0.8,0.8,0.93

In [ ]:
# Checking if conversios are done properly
display(new_df[new_df['propertyname'] == 'Priyam Residency'][['propertyname', 'propertysubname', 'pricedetails', 'min_price', 'max_price']])

         propertyname propertysubname  pricedetails  min_price  max_price
257  Priyam Residency      1 BHK Flat          0.87       0.87       0.95

In [ ]:
df1.head()

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,"1, 2, 3 BHK Flat",5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,Rs. 1.37 - 3.22 Cr,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,"2, 3, 4 BHK Flat",One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,Rs. 3.5 - 6.91 Cr,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
2,Satellite Aristia,"1, 2 BHK Flat",Exclusive rooftop swimming pool with breathtak...,https://www.99acres.com/satellite-aristia-andh...,Rs. 1.49 - 2.21 Cr,Swimming Pool | Rooftop Amenities,"[1, 2]",1.49,2.21
3,One Meraki,"2, 3, 4 BHK Flat","21,686 sq. ft. sky garden with an infinity roo...",https://www.99acres.com/one-meraki-chembur-cen...,Rs. 3.38 - 8.97 Cr,Pet Area | Park / Garden | Rooftop Amenities |...,"[2, 3, 4]",3.38,8.97
4,Domain,"1, 2 BHK Flat",Unique rooftop Astro deck for stargazing & pan...,https://www.99acres.com/domain-govandi-central...,Rs. 83 L - 1.39 Cr,Rooftop Amenities | Party Area,"[1, 2]",0.83,1.39

In [ ]:
new_data = []

for i in range(len(df1)):
  text = df1.loc[i, 'propertysubname']
  bhk_list = text.replace(" BHK Flat","").strip().split(", ")

  prices = list(np.linspace(
          df1.loc[i,'min_price'],
          df1.loc[i,'max_price'],
          len(bhk_list)
      ).round(2))

  for bhk, price in zip(bhk_list, prices):
    new_row = df1.loc[i].copy()
    new_row['propertysubname'] = str(bhk) + " BHK Flat"
    new_row['pricedetails'] = round(price, 2)
    new_data.append(new_row)

new_df = pd.DataFrame(new_data)
new_df

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,bhk_list,min_price,max_price
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
0,ModiRealty Olive,3 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,3.22,Spa | Vaastu Compliant | Children's Play Area ...,"[1, 2, 3]",1.37,3.22
1,Romell Espalier,2 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,3.50,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
1,Romell Espalier,3 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,5.20,Spa | Pet Area | Swimming Pool,"[2, 3, 4]",3.50,6.91
...,...,...,...,...,...,...,...,...,...
500,Samarpan Anuraj CHS,2 BHK Flat,Scenic views of Sanjay Gandhi National Park | ...,https://www.99acres.com/samarpan-anuraj-chs-bo...,1.92,Pet Area | Park / Garden | Vaastu Compliant,"[1, 2]",1.30,1.92
501,Balaji Heights,1 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,1.25,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
501,Balaji Heights,2 BHK Flat,"Strategic connectivity to Metro stations, WEH,...",https://www.99acres.com/balaji-heights-borival...,2.15,Rooftop Amenities | Park / Garden | Parking,"[1, 2]",1.25,2.15
502,Truearth Vedaa,1 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,0.75,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25
502,Truearth Vedaa,2 BHK Flat,"Prime Vikhroli location with seamless metro, r...",https://www.99acres.com/truearth-vedaa-vikhrol...,1.25,Pet Area | Yoga / Meditation | Gymnasium | Chi...,"[1, 2]",0.75,1.25

In [ ]:
new_df.drop(columns=['bhk_list',	'min_price',	'max_price'], inplace=True)

In [ ]:
new_df.sample(3)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
299,Omkar Alta Monte,3 BHK Flat,Providing large Podium Level Garden with eleva...,https://www.99acres.com/omkar-alta-monte-malad...,6.86,Pet Area | Park / Garden | Jogging Track | Pod...
240,34 Park Estate,3 BHK Flat,A magnificent 34 storeys with 34 Lifestyle Ame...,https://www.99acres.com/34-park-estate-goregao...,3.13,Park / Garden | Spa | Pet Area
110,Godrej Vistas,3 BHK Flat,Sweeping views of mangroves and majestic hills...,https://www.99acres.com/godrej-vistas-vikhroli...,5.22,Pet Area

In [ ]:
new_df[new_df['propertyname']=='Srushtiraj Siddhi Square']

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities
162,Srushtiraj Siddhi Square,1 BHK Flat,Sophisticated Modern Architecture | Vastu-Comp...,https://www.99acres.com/srushtiraj-siddhi-squa...,0.8,Pet Area | Vaastu Compliant

In [ ]:
new_df.iloc[50,2]

'28.32 k sq.m richly landscaped private park | 7 exclusive swimming pools are available | First Evander Holyfield gym of India'

In [ ]:
import re
df1['location'] = df1_copy['PropertySubName'].apply(
    lambda x: re.search(r'in (.+?)(?:,\s*Mumbai)?$', x, re.IGNORECASE).group(1).strip()
    if re.search(r'in (.+?)(?:,\s*Mumbai)?$', x, re.IGNORECASE) else None
)

In [ ]:
new_df = new_df.merge(df1[['propertyname','location']],on='propertyname', how='left')

In [ ]:
new_df['source'] = '99acres'

In [ ]:
new_df['bedrooms'] = new_df['propertysubname'].str.split(" ").str.get(0)

In [ ]:
new_df.head(2)

,propertyname,propertysubname,locationadvantages,link,pricedetails,topfacilities,location,source,bedrooms
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,1
1,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,2

In [ ]:
new_df.to_csv('cleaned_multiple_BHK_real_estate.csv', index=False)

## Mumbai_Flats.CSV Cleaning

In [ ]:
df2['source'] = 'kaggle'

In [ ]:
df2['location'] = df2['address'].str.split(', ').str.get(-2)

In [ ]:
df2.head(1)

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
0,3 BHK Flat,3.95 Cr,"Runwal Forest Tower 5 To 8, Kanjurmarg West, M...",1550 sq.ft,₹25.48 K/sq.ft,3 Year Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Runwal Forest Tower 5 To 8,4.0 LacsAccess Zero Brokerage Properties,1130 sq.ft,3,2,1,2 Covered Parking,Exclusive 3 bhk with 3 bathroom apartment ava...,kaggle,Kanjurmarg West

In [ ]:
def convert_price(text):

    text = str(text).strip()

    if "Cr" in text:
        return float(text.replace("Cr", "").strip())

    elif "L" in text:
        return round(
            float(text.replace("L", "").strip()) / 100,
            2
        )

    return float(text)

df2['price'] = df2['price'].apply(convert_price)

In [ ]:
df2['price'].isna().value_counts()

price
False    9954
True        1
Name: count, dtype: int64

In [ ]:
df2[df2['price'].isna()]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
8556,3.99 Cr - 10.15 Cr,NaN,"Western India Mills Compound, G D Ambekar Marg...","2, 3, 4, 5 BHK Apartments","Dec, 2025",Price on request,826 sq.ft. - 2104 sq.ft.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kaggle,Central Mumbai Suburbs

In [ ]:
df2.drop(index=8556, inplace=True)

In [ ]:
df2[~df2['buildup_area'].str.contains("sq.ft")]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
8076,3 BHK Independent House,8.20,"Hiranandani Maitri Park, Sahakar Nagar, Chembu...",2300 sq.yd,₹35.65 K/sq.yd,10 Year Old,Ready to move,South-West facingFacing,Fully Furnished,NaN,Hiranandani Maitri Park,8.2 Lacs(Negotiable)Access Zero Brokerage Prop...,2200 sq.yd,3,3,2,1 Covered and 1 Open Parking,Certainly! Here's an alternate description for...,kaggle,Chembur
9902,Agricultural Land,0.65,"Manori, Mumbai",500 sq.mt,₹13 K/sq.mt,5 Year Old,Immediate,North-West facingFacing,NaN,NaN,No ChargeAccess Zero Brokerage Properties,65.0 L,50 mt,5 mt,4,No,-,Agricultural Land for Sale in Manori - Malad/K...,kaggle,Manori

In [ ]:
df2[df2['buildup_area'].str.contains("5000")]

,flat_type,price,address,buildup_area,avg_price_sqft,age_of_property,possesion_status,which_floor,facing,furnicing,project_name,brokrage,carpet_area,bedrooms,bathrooms,balcony,parking,about_property,source,location
3654,4 BHK Flat,45.0,"Indiabulls Blu Tower B, BDD Chawls Worli, Worl...",5000 sq.ft,₹90 K/sq.ft,1 Years Old,Ready to move,Higherof 50 floors,Fully Furnished,NaN,Indiabulls Blu Tower B,30.0 LacsAccess Zero Brokerage Properties,3400 sq.ft,4,5,No Balcony,3 Covered Parking,A very lavish and spacious 4bhk for lease in a...,kaggle,Worli
3746,4 BHK Flat,45.0,"Bandra West, Mumbai",5000 sq.ft,₹90 K/sq.ft,5 Year Old,Ready to move,Middleof 17 floors,Unfurnished,NaN,45.0 Lacs(Negotiable)Access Zero Brokerage Pro...,45.0 Cr,4,4,3,3 days ago,2 Covered and 1 Open Parking,4 BHK Flat for sale in Mumbai. This property i...,kaggle,Bandra West
8325,3 BHK Villa,35.0,"Bandra West, Mumbai",5000 sq.ft,₹70 K/sq.ft,5 Year Old,Ready to move,Semi FurnishedFurnishing,NaN,NaN,35.0 LacsAccess Zero Brokerage Properties,35.0 Cr,3,3,No Balcony,18 days ago,2 Covered and 1 Open Parking,Available Residential cum commercial bungalow ...,kaggle,Bandra West
9500,10 BHK Independent House,30.0,"Swaraj Homes Chhaya Society, Chembur, Mumbai",15000 sq.ft,₹20 K/sq.ft,10 Year Old,Ready to move,North facingFacing,Unfurnished,NaN,Swaraj Homes Chhaya Society,30.0 LacsAccess Zero Brokerage Properties,14000 sq.ft,10,10,11,9 Open Parking,THIS IS A PRIVATE BUILDING WITH G+7 STOREY WEL...,kaggle,Chembur

In [ ]:
df2.iloc[8076,3] = "20700 sq.ft"
df2.loc[9902,'buildup_area'] = "5382 sq.ft"

In [ ]:
# 1. Filter the dataset to only include rows that contain 'BHK Flat'
df_flats = df2[df2['flat_type'].str.contains('BHK Flat', na=False)].copy()

# 2. Extract the leading digits, convert them to integer
df_flats['bhk_type'] = df_flats['flat_type'].str.extract(r'(\d+)').astype(int)

# 3. Ensure 'bedrooms' is numeric for a correct comparison
df_flats['bedrooms'] = pd.to_numeric(df_flats['bedrooms'], errors='coerce')

# 4. Find and print rows where flat_type number does not match bedrooms column
mismatch = df_flats[df_flats['bedrooms'] != df_flats['bhk_type']]

print(f"Total Mismatches found: {len(mismatch)}")
print(mismatch[['flat_type', 'bhk_type', 'bedrooms']].head(10))

Total Mismatches found: 1032
        flat_type  bhk_type  bedrooms
43   1.5 BHK Flat         1       2.0
50     1 BHK Flat         1       2.0
60     1 BHK Flat         1       2.0
70     1 BHK Flat         1       2.0
76     1 BHK Flat         1       2.0
85     3 BHK Flat         3       4.0
98     1 BHK Flat         1       2.0
109    3 BHK Flat         3       2.0
118    1 BHK Flat         1       2.0
141    1 BHK Flat         1       2.0

In [ ]:
print(df2['flat_type'].unique())

['3 BHK Flat' '1 BHK Flat' '2 BHK Flat' '4 BHK Flat' '7 BHK Flat'
 '1.5 BHK Flat' '3 BHK Independent Builder Floor'
 '1 BHK Independent House' '5 BHK Independent Builder Floor' '6 BHK Flat'
 '3 BHK Villa' '5 BHK Flat' '4 BHK Independent House' '4 BHK Villa'
 '1 RK Flat' '2 BHK Independent House' '3 BHK Independent House'
 '5+ BHK Flat' '1 BHK Independent Builder Floor'
 '4 BHK Independent Builder Floor' '5 BHK Villa' '6 BHK Villa'
 '10 BHK Independent House' 'Agricultural Land' '1 RK Independent House']

In [ ]:
df2 = df2[df2['flat_type'].str.contains('Flat', na=False)].reset_index(drop=True)

In [ ]:
def parse_sqft(val):
    if pd.isna(val):
        return np.nan

    val_str = str(val).replace('sq.ft', '').replace(',', '').strip()

    if '-' in val_str:
        parts = val_str.split('-')
        try:
            return (float(parts[0].strip()) + float(parts[1].strip())) / 2
        except ValueError:
            return np.nan

    try:
        val_float = float(val_str)
        return val_float if val_float >= 100 else np.nan
    except ValueError:
        return np.nan

df2['buildup_area_sqft'] = df2['buildup_area'].apply(parse_sqft)
df2['carpet_area_sqft']  = df2['carpet_area'].apply(parse_sqft)

In [ ]:
df2['furnishing'] = df2['facing'].apply(
    lambda x: x if pd.notna(x) and 'urnished' in str(x) else np.nan
)
df2['furnishing'] = df2['furnishing'].fillna('Unknown')

In [ ]:
df2['is_ready_to_move'] = df2['possesion_status'] == 'Ready to move'

In [ ]:
def parse_age(val):
    val = str(val).strip()
    if val == 'Ready to move':
        return 0
    # BHK values that got misplaced — treat as NaN
    if 'BHK' in val:
        return np.nan
    first = val.split(' ')[0]
    try:
        return int(first)
    except ValueError:
        return np.nan

df2['age_of_property'] = df2['age_of_property'].apply(parse_age)

In [ ]:
def parse_floor(val):
    if pd.isna(val): return np.nan
    val = str(val)
    if 'of' in val:
        position = val.split('of')[0].strip()
        if position in ('Higher', 'Middle', 'Lower'):
            return position
    return np.nan

df2['which_floor'] = df2['which_floor'].apply(parse_floor)

In [ ]:
def parkingCount(text):
    if pd.isna(text) or str(text).strip() == '-':
        return 0

    text = str(text)

    if 'Covered' in text and 'Open' in text:
        num1 = int(text.split(' ')[0])
        num2 = int(text.split(' ')[-3])
        return num1 + num2

    elif 'Covered' in text or 'Open' in text:
        return int(text.split(' ')[0])

    return 0

df2['parking'] = df2['parking'].apply(parkingCount)

In [ ]:
# fix bedrooms: drop misplaced values
df2['bedrooms'] = pd.to_numeric(df2['bedrooms'], errors='coerce')

In [ ]:
# drop columns no longer needed
df2.drop(columns=[
    'address', 'buildup_area', 'carpet_area',
    'avg_price_sqft', 'facing', 'furnicing', 'brokrage',
    'about_property'
], inplace=True)

In [ ]:
mask = df2['bathrooms'] == 'No Balcony'
df2.loc[mask, 'balcony'] = 'No Balcony'
df2.loc[mask, 'bathrooms'] = np.nan

In [ ]:
mask = ~df2['possesion_status'].str.contains("Ready to move", na=False)
df2.loc[mask,'possesion_status'] = np.nan

In [ ]:
df2['flat_type'] = df2['flat_type'].str.replace("1 RK Flat", "0.5 BHK Flat")

In [ ]:
df2 = df2[['flat_type', 'price', 'age_of_property', 'possesion_status', 'which_floor', 'project_name', 'bedrooms', 'bathrooms', 'balcony', 'parking', 'source', 'location', 'buildup_area_sqft', 'carpet_area_sqft', 'is_ready_to_move', 'furnishing']]

In [ ]:
df2.to_csv('cleaned_mumbai_flats_aftermath_final.csv', index=False)
df2.head(3)

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing
0,3 BHK Flat,3.95,3.0,Ready to move,Higher,Runwal Forest Tower 5 To 8,3.0,2,1,2,kaggle,Kanjurmarg West,1550.0,1130.0,True,Fully Furnished
1,1 BHK Flat,0.19,3.0,Ready to move,Middle,Ananta Vardhman Nagar,1.0,1,2,1,kaggle,Palghar,630.0,390.0,True,Unfurnished
2,1 BHK Flat,0.73,1.0,Ready to move,Lower,JP North Barcelona,1.0,2,2,0,kaggle,Mira Road East,580.0,475.0,True,Semi Furnished

In [ ]:
df2.shape

(9894, 16)

In [ ]:
list(df2.columns)

['flat_type',
 'price',
 'age_of_property',
 'possesion_status',
 'which_floor',
 'project_name',
 'bedrooms',
 'bathrooms',
 'balcony',
 'parking',
 'source',
 'location',
 'buildup_area_sqft',
 'carpet_area_sqft',
 'is_ready_to_move',
 'furnishing']

In [ ]:
df2['price_per_sqft'] = df2['price']*10000000/df2['buildup_area_sqft']

In [ ]:
df2['bathrooms'] = pd.to_numeric(df2['bathrooms'], errors='coerce')

df2['balcony'] = pd.to_numeric(df2['balcony'].replace('No Balcony', 0), errors='coerce').fillna(0)

print("Cleaned Bathrooms:", df2['bathrooms'].unique()[:10])
print("Cleaned Balcony:", df2['balcony'].unique()[:10])

Cleaned Bathrooms: [ 2.  1.  3.  5.  4. nan  6.  7.  8.]
Cleaned Balcony: [1. 2. 3. 0. 4. 5. 7. 6.]

In [ ]:
furnish_score = {'Fully Furnished': 3, 'Semi Furnished': 2, 'Unfurnished': 1, 'Unknown': 0}

# Now calculate the score safely
df2['property_score'] = (
    df2['furnishing'].map(furnish_score).fillna(0) +
    (df2['price_per_sqft'] > df2['price_per_sqft'].quantile(0.75)).astype(int) * 2 +
    (df2['bathrooms'] >= 3).astype(int) +
    (df2['balcony'] >= 2).astype(int)
)

display(df2[['project_name', 'furnishing', 'price_per_sqft', 'bathrooms', 'balcony', 'property_score']].head())

,project_name,furnishing,price_per_sqft,bathrooms,balcony,property_score
0,Runwal Forest Tower 5 To 8,Fully Furnished,25483.870968,2.0,1.0,3
1,Ananta Vardhman Nagar,Unfurnished,3015.873016,1.0,2.0,2
2,JP North Barcelona,Semi Furnished,12586.206897,2.0,2.0,3
3,Chandak Nischay,Semi Furnished,26829.268293,2.0,1.0,2
4,Neelam Solstice Phase I,Semi Furnished,21387.832700,2.0,3.0,3

In [ ]:
df2['bathrooms'].unique()

array([ 2.,  1.,  3.,  5.,  4., nan,  6.,  7.,  8.])

## Other work

In [ ]:
df1.columns

Index(['propertyname', 'propertysubname', 'locationadvantages', 'link',
       'pricedetails', 'topfacilities', 'bhk_list', 'min_price', 'max_price',
       'location'],
      dtype='object')

In [ ]:
df2.columns

Index(['flat_type', 'price', 'age_of_property', 'possesion_status',
       'which_floor', 'project_name', 'bedrooms', 'bathrooms', 'balcony',
       'parking', 'source', 'location', 'buildup_area_sqft',
       'carpet_area_sqft', 'is_ready_to_move', 'furnishing', 'price_per_sqft',
       'property_score'],
      dtype='object')

In [ ]:
new_df.rename({'propertyname':'project_name'}, axis=1, inplace=True)

In [ ]:
new_df.head()

,project_name,propertysubname,locationadvantages,link,pricedetails,topfacilities,location,source,bedrooms
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,1
1,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,2
2,ModiRealty Olive,3 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,https://www.99acres.com/modirealty-olive-kandi...,3.22,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,3
3,Romell Espalier,2 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,3.50,Spa | Pet Area | Swimming Pool,Vile Parle,99acres,2
4,Romell Espalier,3 BHK Flat,One of the tallest towers in Vile Parle East |...,https://www.99acres.com/romell-espalier-vile-p...,5.20,Spa | Pet Area | Swimming Pool,Vile Parle,99acres,3

### Step 1: Drop unnecessary columns from 99acres data

In [ ]:
new_df.drop(columns=['link'], inplace=True, errors='ignore')
# Map propertysubname to flat_type so it merges correctly with df2
new_df.rename(columns={'pricedetails': 'price', 'propertysubname': 'flat_type'}, inplace=True)
display(new_df.head(2))

,project_name,flat_type,locationadvantages,price,topfacilities,location,source,bedrooms
0,ModiRealty Olive,1 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,1.37,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,1
1,ModiRealty Olive,2 BHK Flat,5-minute walk to Valnai Metro and St. Anne Int...,2.30,Spa | Vaastu Compliant | Children's Play Area ...,Kandivali West,99acres,2

### Step 2: Merge the two datasets

In [ ]:
# Concatenate the two DataFrames
final_df = pd.concat([df2, new_df], ignore_index=True)

# Ensure bedrooms is numeric for the whole set
final_df['bedrooms'] = pd.to_numeric(final_df['bedrooms'], errors='coerce')

print(f"Final DataFrame Shape: {final_df.shape}")
display(final_df.sample(10))

Final DataFrame Shape: (11031, 20)

,flat_type,price,age_of_property,possesion_status,which_floor,project_name,bedrooms,bathrooms,balcony,parking,source,location,buildup_area_sqft,carpet_area_sqft,is_ready_to_move,furnishing,price_per_sqft,property_score,locationadvantages,topfacilities
25,1 BHK Flat,0.38,4.0,Ready to move,Middle,Sri Garden Avenue K,1.0,1.0,2.0,1.0,kaggle,Virar West,650.0,390.0,True,Unknown,5846.153846,1.0,NaN,NaN
1197,2 BHK Flat,3.30,1.0,Ready to move,Higher,Atharv Aaradhyam,2.0,2.0,0.0,1.0,kaggle,Andheri East,805.0,705.0,True,Unfurnished,40993.788820,3.0,NaN,NaN
3396,1 BHK Flat,1.00,15.0,Ready to move,Higher,1.0 LacAccess Zero Brokerage Properties,1.0,NaN,0.0,0.0,kaggle,Goregaon West,550.0,NaN,True,Unfurnished,18181.818182,1.0,NaN,NaN
7811,3 BHK Flat,2.85,7.0,Ready to move,Higher,Kohinoor City,3.0,2.0,4.0,2.0,kaggle,Kurla West,1600.0,1100.0,True,Semi Furnished,17812.500000,3.0,NaN,NaN
8917,3 BHK Flat,6.00,15.0,Ready to move,Middle,6.0 LacsAccess Zero Brokerage Properties,3.0,2.0,0.0,2.0,kaggle,Mahim,1350.0,NaN,True,Semi Furnished,44444.444444,4.0,NaN,NaN
10233,6 BHK Flat,84.65,NaN,NaN,NaN,Provenance Four Seasons Private Residences,6.0,NaN,NaN,NaN,99acres,Worli,NaN,NaN,NaN,NaN,NaN,NaN,"Acre of landscaped space including orchard, po...",Park / Garden | Yoga / Meditation | Spa | Gymn...
4828,1 BHK Flat,0.78,12.0,Ready to move,Higher,1.6 Lacs(Negotiable)Access Zero Brokerage Prop...,1.0,NaN,0.0,1.0,kaggle,Ghodbander,510.0,NaN,True,Unfurnished,15294.117647,1.0,NaN,NaN
10443,2 BHK Flat,2.73,NaN,NaN,NaN,Kalpataru Vienta,2.0,NaN,NaN,NaN,99acres,Kandivali East,NaN,NaN,NaN,NaN,NaN,NaN,"Well connected with 3 main roads via SV, Link,...",Pet Area | Park / Garden
8974,3 BHK Flat,2.30,9.0,Ready to move,Middle,K Raheja Interface Heights,3.0,2.0,3.0,0.0,kaggle,Malad West,1500.0,850.0,True,Unfurnished,15333.333333,2.0,NaN,NaN
10924,2 BHK Flat,1.79,NaN,NaN,NaN,Marigold Miraaya,2.0,NaN,NaN,NaN,99acres,"Asha Nagar, Mulund West",NaN,NaN,NaN,NaN,NaN,NaN,Rera approved project | EV Charging Available ...,Pet Area | EV Charging

In [ ]:
# Identify top 10 locations based on median price per sqft (Premium Areas)
top_premium_locs = df2.groupby('location')['price_per_sqft'].median().sort_values(ascending=False).head(20).index

# Create the validation pivot for these premium locations
premium_validation = df2[df2['location'].isin(top_premium_locs)].pivot_table(
    index=['location', 'flat_type'],
    values=['carpet_area_sqft', 'buildup_area_sqft'],
    aggfunc=['median', 'count']
)

# Accessing MultiIndex columns: ('median', 'column_name')
premium_validation['ratio'] = premium_validation[('median', 'buildup_area_sqft')] / premium_validation[('median', 'carpet_area_sqft')]

print("Validation for Top 10 Premium Locations (by Price):")

with pd.option_context('display.max_rows', None):
    display(premium_validation)

Validation for Top 10 Premium Locations (by Price):

                                      median                   \
                           buildup_area_sqft carpet_area_sqft
location        flat_type
Bandra West     1 BHK Flat             662.5            530.0
                2 BHK Flat            1000.0            780.0
                3 BHK Flat            1500.0           1160.0
                4 BHK Flat            2850.0           2000.0
                5 BHK Flat            5550.0           3500.0
                6 BHK Flat            4000.0              NaN
Churchgate      2 BHK Flat            1152.5           1030.0
                3 BHK Flat            2100.0              NaN
Colaba          1 BHK Flat             600.0            500.0
                2 BHK Flat            1000.0            963.0
                3 BHK Flat            1560.0           1450.0
                4 BHK Flat            2945.0           2997.0
Cuffe Parade    1 BHK Flat             555.0              NaN
                2 BHK Flat            1050.0            980.0
                3 BHK Flat            1500.0           1080.0
                4 BHK Flat            1800.0              NaN
                5 BHK Flat            3394.0              NaN
                6 BHK Flat            5400.0              NaN
Cumballa Hill   2 BHK Flat            1170.0              NaN
                3 BHK Flat            1800.0           2100.0
                4 BHK Flat            2700.0              NaN
                6 BHK Flat            4400.0           3962.0
Dadar East      1 BHK Flat             514.5            473.0
                2 BHK Flat             800.0            750.0
                3 BHK Flat            1350.0           1150.0
                4 BHK Flat            2164.0           1670.0
Fort            2 BHK Flat             971.0            739.0
                4 BHK Flat            2400.0              NaN
Gamdevi         2 BHK Flat            1050.0           1000.0
                3 BHK Flat            1150.0           1796.0
Jacob Circle    2 BHK Flat             930.0            690.0
                3 BHK Flat            1665.0           1400.0
Juhu            1 BHK Flat             632.0            664.0
                2 BHK Flat             918.0            778.0
                3 BHK Flat            1500.0           1242.0
                4 BHK Flat            2281.5           1396.5
                5 BHK Flat            3580.0           2425.0
                6 BHK Flat            2100.0           2000.0
Khar West       1 BHK Flat             585.0            500.0
                2 BHK Flat             950.0            750.0
                3 BHK Flat            1425.0           1125.0
                4 BHK Flat            2875.0           1962.0
                5 BHK Flat           10000.0              NaN
Mahalakshmi     1 BHK Flat             462.5              NaN
                2 BHK Flat             863.5            877.0
                3 BHK Flat            1600.0           1403.0
                4 BHK Flat            2422.0           2700.0
                6 BHK Flat            3500.0              NaN
Malabar Hill    1 BHK Flat             785.0              NaN
                2 BHK Flat            1350.0           1200.0
                3 BHK Flat            1707.5           1625.0
                4 BHK Flat            2400.0           2335.0
Marine Lines    2 BHK Flat             558.0              NaN
                3 BHK Flat            1290.0              NaN
Matunga West    1 BHK Flat             500.0            421.5
                2 BHK Flat            1025.0            755.0
                3 BHK Flat            1470.0           1221.5
Santacruz West  1 BHK Flat             500.0              NaN
                2 BHK Flat             971.0            733.5
                3 BHK Flat            1500.0           1190.0
                4 BHK Flat            2800.5           1640.0
                5 BHK Flat            3450.0              NaN
Tardeo          1 BHK Flat             442.5              NaN
                2 BHK Flat            1275.0            980.0
                3 BHK Flat            1500.0           1850.0
                4 BHK Flat            2400.0           2200.0
Trombay         1 BHK Flat             450.0            386.0
                3 BHK Flat             890.0            777.0
Vile Parle West 1 BHK Flat             600.0            500.0
                2 BHK Flat             840.0              NaN
                3 BHK Flat            1550.0           1300.0
                4 BHK Flat            1700.0           1440.0
                5 BHK Flat            2450.0              NaN
Worli           1 BHK Flat             700.0            524.0
                2 BHK Flat             900.0              NaN
                3 BHK Flat            1800.0           1525.0
                4 BHK Flat            2175.0           1813.0
                5 BHK Flat            4500.0           3868.0
                6 BHK Flat            9500.0           6500.0
                7 BHK Flat            3000.0           2900.0

                                       count                      ratio
                           buildup_area_sqft carpet_area_sqft
location        flat_type
Bandra West     1 BHK Flat                 8                3  1.250000
                2 BHK Flat                28                5  1.282051
                3 BHK Flat                62               17  1.293103
                4 BHK Flat                42               11  1.425000
                5 BHK Flat                 4                4  1.585714
                6 BHK Flat                 2                0       NaN
Churchgate      2 BHK Flat                 2                2  1.118932
                3 BHK Flat                 3                0       NaN
Colaba          1 BHK Flat                 1                1  1.200000
                2 BHK Flat                10                7  1.038422
                3 BHK Flat                 4                2  1.075862
                4 BHK Flat                 2                1  0.982649
Cuffe Parade    1 BHK Flat                 1                0       NaN
                2 BHK Flat                11                6  1.071429
                3 BHK Flat                 4                1  1.388889
                4 BHK Flat                 1                0       NaN
                5 BHK Flat                 1                0       NaN
                6 BHK Flat                 1                0       NaN
Cumballa Hill   2 BHK Flat                 1                0       NaN
                3 BHK Flat                10                2  0.857143
                4 BHK Flat                 5                0       NaN
                6 BHK Flat                 1                1  1.110550
Dadar East      1 BHK Flat                10                1  1.087738
                2 BHK Flat                14                4  1.066667
                3 BHK Flat                18                8  1.173913
                4 BHK Flat                12                4  1.295808
Fort            2 BHK Flat                 2                1  1.313938
                4 BHK Flat                 1                0       NaN
Gamdevi         2 BHK Flat                 1                1  1.050000
                3 BHK Flat                 3                1  0.640312
Jacob Circle    2 BHK Flat                 1                1  1.347826
                3 BHK Flat                 6                6  1.189286
Juhu            1 BHK Flat                 4                2  0.951807
                2 BHK Flat                29                5  1.179949
                3 BHK Flat                87               21  1.207729
                4 BHK Flat                68               10  1.633727
                5 BHK Flat                 6                1  1.476289
                6 BHK Flat                 1                1  1.050000
Khar West       1 BHK Flat                 2                1  1.170000
                2 BHK Flat                17                4  1.266667
                3 BHK Flat                36               10  1.266667
                4 BHK Flat                20                5  1.465341
                5 BHK Flat                 1                0       NaN
Mahalakshmi     1 BHK Flat                 2                0       NaN
                2 BHK Flat                 2                1  0.984607
                3 BHK Flat                 8                3  1.140413
                4 BHK Flat                 3                2  0.897037
                6 BHK Flat                 1                0       NaN
Malabar Hill    1 BHK Flat                 2                0       NaN
                2 BHK Flat                 2                1  1.125000
                3 BHK Flat                14                4  1.050769
                4 BHK Flat                 3                1  1.027837
Marine Lines    2 BHK Flat                 1                0       NaN
                3 BHK Flat                 2                0       NaN
Matunga West    1 BHK Flat                 7                2  1.186240
                2 BHK Flat                 2                2  1.357616
                3 BHK Flat                 5                4  1.203438
Santacruz West  1 BHK Flat                 7                0       NaN
                2 BHK Flat                13                4  1.323790
                3 BHK Flat                37                8  1.260504
                4 BHK Flat                22                5  1.707622
                5 BHK Flat                 4                0       NaN
Tardeo          1 BHK Flat                 2                0       NaN
                2 BHK Flat                 3                3  1.301020
                3 BHK Flat                 7                1  0.810811
                4 BHK Flat                 3                3  1.090909
Trombay         1 BHK Flat                 1                1  1.165803
                3 BHK Flat                 1                1  1.145431
Vile Parle West 1 BHK Flat                 4                1  1.200000
                2 BHK Flat                 5                0       NaN
                3 BHK Flat                14                3  1.192308
                4 BHK Flat                 9                2  1.180556
                5 BHK Flat                 2                0       NaN
Worli           1 BHK Flat                 4                4  1.335878
                2 BHK Flat                 6                0       NaN
                3 BHK Flat                31               18  1.180328
                4 BHK Flat                24               16  1.199669
                5 BHK Flat                 3                2  1.163392
                6 BHK Flat                 1                1  1.461538
                7 BHK Flat                 1                1  1.034483

## Handling Missing values after merging

In [ ]:
cols_to_impute = ['buildup_area_sqft', 'carpet_area_sqft', 'bathrooms', 'balcony', 'parking', 'age_of_property']

# Using 'flat_type' as the grouping key for BHK-type
for col in cols_to_impute:
    final_df[col] = final_df.groupby('flat_type')[col].transform(
        lambda x: x.fillna(x.median())
    )

In [ ]:
final_df['furnishing'] = final_df['furnishing'].fillna('Unknown')
final_df['which_floor'] = final_df['which_floor'].fillna('Unknown')
final_df['is_ready_to_move'] = final_df['is_ready_to_move'].fillna(True)  # assuming active 99acres listings are ready
final_df['possesion_status'] = final_df['possesion_status'].fillna('Ready to move')

In [ ]:
final_df['locationadvantages'] = final_df['locationadvantages'].fillna('')
final_df['topfacilities'] = final_df['topfacilities'].fillna('')

In [ ]:
final_df['price_per_sqft'] = (final_df['price'] * 10000000) / final_df['buildup_area_sqft']

print("Imputation and Feature derivation complete.")
display(final_df.isnull().sum())
display(final_df.sample(5))

In [ ]:
# Recalculate property_score for the entire unified dataset
furnish_score = {'Fully Furnished': 3, 'Semi Furnished': 2, 'Unfurnished': 1, 'Unknown': 0}

# Consistent scoring logic: furnishing + high price/sqft + bathrooms + balcony
final_df['property_score'] = (
    final_df['furnishing'].map(furnish_score).fillna(0) +
    (final_df['price_per_sqft'] > final_df['price_per_sqft'].quantile(0.75)).astype(int) * 2 +
    (final_df['bathrooms'] >= 3).astype(int) +
    (final_df['balcony'] >= 2).astype(int)
)

print("Preprocessing Phase Complete. Final Null Summary:")
display(final_df.isnull().sum())
display(final_df[final_df['source'] == '99acres'].head())

In [ ]:
final_df[final_df['bedrooms'].isna()]

In [ ]:
import re

# Extract numeric value from flat_type for rows where bedrooms is NaN
mask = final_df['bedrooms'].isna()
final_df.loc[mask, 'bedrooms'] = final_df.loc[mask, 'flat_type'].str.extract(r'(\d+)').astype(float)[0]

# Final check for bedrooms null count
print(f"Missing values in bedrooms: {final_df['bedrooms'].isna().sum()}")

### Final Export
Exporting the fully cleaned and merged dataset to a final CSV file.

In [ ]:
# Export the final unified dataframe
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
final_df.to_csv('final_cleaned_mumbai_real_estate_.csv', index=False)

print("Final dataset exported successfully as 'mumbai_real_estate_unified_cleaned.csv'")
print(f"Final record count: {len(final_df)}")

In [ ]:
final_df.isna().sum()