In [200]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [201]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/Projects/Real Estate Capstone Project/DataSets/residential_land_main.csv')
df_copy = df.copy()
df.head()

,property_name,link,society,price,areaWithType,address,floorNumAllowed,noOfOpenSides,possession,nearbyLocations,description,features,rating,property_id
0,"Residential land / Plot in Chembur West, Mumbai",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 4.5 Crore,2500 sqft (Plot Area) / 232.26 sq.m.,"Chembur West, Mumbai",3.0,NaN,New Construction / Immediate,Shankar Deol (Religious Place) | Kali -Bari Ma...,Looking for buyer to purchase our land availab...,NaN,O,V76443295
1,Residential land / Plot in Sri Mukteshwar Deva...,https://www.99acres.com/residential-land-plot-...,NaN,Rs. 36 Crore,9000 sqft (Plot Area) / 836.13 sq.m.,Sri Mukteshwar Devalaya Rd,NaN,NaN,New Construction / Immediate,NaN,The property is near to kailash society \nOpen...,NaN,A,C90499528
2,"Residential land / Plot in Vile Parle, Mumbai",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 150 Crore,27000 sqft (Plot Area) / 2508.38 sq.m.,"Vile Parle, Mumbai",NaN,NaN,New Construction / Immediate,Jayashree (Parking) | our lady of health churc...,"Spanning 27,000 sq.Ft., this residential land ...",NaN,A,A90468230
3,"Residential land / Plot in Kalina, Santacruz East",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 11 Crore,3838 sqft (Plot Area) / 356.56 sq.m.,"Kalina, Santacruz East",NaN,NaN,New Construction,Cross INRI (Religious Place) | Umar Masjid (Re...,"Freehold 3,838 sq.Ft plot (Cts 6170) kolekalya...",NaN,O,I90409302
4,"Residential land / Plot in Yadav Nagar, Chandi...",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 22 Lac,1200 sqft (Plot Area) / 111.48 sq.m.,"Yadav Nagar, Chandivali",NaN,NaN,New Construction,Saki naka metro station (Metro Station) | Asal...,Planning to purchase a plot in central mumbai?...,NaN,O,M90395190

In [202]:
df.shape

(1018, 14)

In [203]:
df.drop(columns='noOfOpenSides', inplace = True, axis=1)

# Columns Details

### property_name
- Some contains areas and some contains plot name

### society
- 50% values are null

### price
- price in Cr and lac. Also contains 'Available on Request'

### area with type
- contains sqft and sq.m. '(Plot Area)' in between

### address
- Address of the given plot

### floorNumAllowed
- 20% data is missing

### possession
- 10% missing data
- contains ['New Construction / Immediate', 'New Construction', nan] entries

### nearbylocation
- 42% of the data missing

### description

### feature
16% of the data missing


### **Missing Data**:
property_name: 0.0%  
link: 0.98%  
society: 50.98%  
price: 0.98%  
areaWithType: 0.98%  
address: 0.98%  
floorNumAllowed: 20.63%  
possession: 0.98%  
nearbyLocations: 42.24%  
description: 0.98%  
features: 16.9%  
rating: 0.98%  
property_id: 0.98%

In [204]:
def checkMissingData(df):

  print("Missing Data: \n")
  for i in df.columns:
    percent = round(df[i].isna().sum()/df.shape[0]*100,2)
    print(f"{i}: {percent}%\n")

checkMissingData(df)

Missing Data:

property_name: 0.0%

link: 0.98%

society: 50.98%

price: 0.98%

areaWithType: 0.98%

address: 0.98%

floorNumAllowed: 20.63%

possession: 0.98%

nearbyLocations: 42.24%

description: 0.98%

features: 16.9%

rating: 0.98%

property_id: 0.98%

In [205]:
df['possession'].unique()

array(['New Construction / Immediate', 'New Construction', nan],
      dtype=object)

In [206]:
df.head()

,property_name,link,society,price,areaWithType,address,floorNumAllowed,possession,nearbyLocations,description,features,rating,property_id
0,"Residential land / Plot in Chembur West, Mumbai",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 4.5 Crore,2500 sqft (Plot Area) / 232.26 sq.m.,"Chembur West, Mumbai",3.0,New Construction / Immediate,Shankar Deol (Religious Place) | Kali -Bari Ma...,Looking for buyer to purchase our land availab...,NaN,O,V76443295
1,Residential land / Plot in Sri Mukteshwar Deva...,https://www.99acres.com/residential-land-plot-...,NaN,Rs. 36 Crore,9000 sqft (Plot Area) / 836.13 sq.m.,Sri Mukteshwar Devalaya Rd,NaN,New Construction / Immediate,NaN,The property is near to kailash society \nOpen...,NaN,A,C90499528
2,"Residential land / Plot in Vile Parle, Mumbai",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 150 Crore,27000 sqft (Plot Area) / 2508.38 sq.m.,"Vile Parle, Mumbai",NaN,New Construction / Immediate,Jayashree (Parking) | our lady of health churc...,"Spanning 27,000 sq.Ft., this residential land ...",NaN,A,A90468230
3,"Residential land / Plot in Kalina, Santacruz East",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 11 Crore,3838 sqft (Plot Area) / 356.56 sq.m.,"Kalina, Santacruz East",NaN,New Construction,Cross INRI (Religious Place) | Umar Masjid (Re...,"Freehold 3,838 sq.Ft plot (Cts 6170) kolekalya...",NaN,O,I90409302
4,"Residential land / Plot in Yadav Nagar, Chandi...",https://www.99acres.com/residential-land-plot-...,NaN,Rs. 22 Lac,1200 sqft (Plot Area) / 111.48 sq.m.,"Yadav Nagar, Chandivali",NaN,New Construction,Saki naka metro station (Metro Station) | Asal...,Planning to purchase a plot in central mumbai?...,NaN,O,M90395190

In [207]:
df.drop(columns=['property_name','link','society', 'property_id'], inplace = True)

In [208]:
df.head(2)

,price,areaWithType,address,floorNumAllowed,possession,nearbyLocations,description,features,rating
0,Rs. 4.5 Crore,2500 sqft (Plot Area) / 232.26 sq.m.,"Chembur West, Mumbai",3.0,New Construction / Immediate,Shankar Deol (Religious Place) | Kali -Bari Ma...,Looking for buyer to purchase our land availab...,NaN,O
1,Rs. 36 Crore,9000 sqft (Plot Area) / 836.13 sq.m.,Sri Mukteshwar Devalaya Rd,NaN,New Construction / Immediate,NaN,The property is near to kailash society \nOpen...,NaN,A

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1018 entries, 0 to 1017
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   price            1008 non-null   object
 1   areaWithType     1008 non-null   object
 2   address          1008 non-null   object
 3   floorNumAllowed  808 non-null    float64
 4   possession       1008 non-null   object
 5   nearbyLocations  588 non-null    object
 6   description      1008 non-null   object
 7   features         846 non-null    object
 8   rating           1008 non-null   object
dtypes: float64(1), object(8)
memory usage: 71.7+ KB

In [210]:
df.describe()

       floorNumAllowed
count       808.000000
mean          8.834158
std           8.198723
min           0.000000
25%           2.000000
50%           4.000000
75%          18.000000
max          78.000000

## Price

In [211]:
(df['price'].str.contains('request', case=False, na=False)).sum()

np.int64(6)

In [212]:
df= df[~df['price'].str.contains('request', case=False, na=False)].reset_index(drop=True)

In [213]:
df.dropna(subset=['price'], inplace=True)

In [214]:
missing_unit = df[~df['price'].str.contains('Lac|Crore', case=False, na=False)]

if missing_unit.empty:
    print("All entries contain either 'Lac' or 'Crore'.")
else:
    print(f"Found {len(missing_unit)} entries without standard units:")
    display(missing_unit[['price']])

All entries contain either 'Lac' or 'Crore'.

In [215]:
def priceCleaning(text):

    text = text.replace("Rs. ", "").strip()

    if "Crore" in text:
        text = text.replace(" Crore", "").strip()
        return round(float(text),2)

    if "Lac" in text:
        text = text.replace(" Lac", "").strip()
        return round(float(text) / 100,2)


df['price'] = df['price'].apply(priceCleaning)

## area

In [216]:
df['areaWithType'] = df['areaWithType'].str.split("/").str.get(0).str.replace("(Plot Area)","",case=False).str.strip()

In [217]:
df['areaWithType'] = df['areaWithType'].str.replace("sqft","").str.strip().astype(float)

In [218]:
df.rename(columns={'areaWithType': 'area_sqft'}, inplace=True)
df.head()

,price,area_sqft,address,floorNumAllowed,possession,nearbyLocations,description,features,rating
0,4.50,2500.0,"Chembur West, Mumbai",3.0,New Construction / Immediate,Shankar Deol (Religious Place) | Kali -Bari Ma...,Looking for buyer to purchase our land availab...,NaN,O
1,36.00,9000.0,Sri Mukteshwar Devalaya Rd,NaN,New Construction / Immediate,NaN,The property is near to kailash society \nOpen...,NaN,A
2,150.00,27000.0,"Vile Parle, Mumbai",NaN,New Construction / Immediate,Jayashree (Parking) | our lady of health churc...,"Spanning 27,000 sq.Ft., this residential land ...",NaN,A
3,11.00,3838.0,"Kalina, Santacruz East",NaN,New Construction,Cross INRI (Religious Place) | Umar Masjid (Re...,"Freehold 3,838 sq.Ft plot (Cts 6170) kolekalya...",NaN,O
4,0.22,1200.0,"Yadav Nagar, Chandivali",NaN,New Construction,Saki naka metro station (Metro Station) | Asal...,Planning to purchase a plot in central mumbai?...,NaN,O

In [219]:
df['price_per_sqft'] = round(df['price'] * 10000000 / df['area_sqft'],2)

## address

In [220]:
df['address'].nunique()

236

In [221]:
# Merged different locations in one single location
import re

location_map = {

    'andheri': [
        'andheri',
        'mahakali caves',
        'versova'
    ],

    'malad': [
        'malad',
        'malvani',
        'somwari bazar',
        'ekta nagar',
        'kanchpada',
        'marve road'
    ],

    'kandivali': [
        'kandivali',
        'mahavir nagar',
        'sector 7 kandivali',
        'sector 7 kandivali west'
    ],

    'borivali': [
        'borivali',
        'daulat nagar'
    ],

    'chembur': [
        'chembur',
        'ghatla'
    ],

    'kurla': [
        'kurla',
        'sabale nagar',
        'takshashila nagar',
        'halav pool'
    ],

    'santacruz': [
        'santacruz',
        'kalina'
    ],

    'juhu': [
        'juhu',
        'jvpd scheme',
        'vithal nagar'
    ],

    'goregaon': [
        'goregaon',
        'best nagar'
    ],

    'bandra': [
        'bandra',
        'bkc',
        'bandra kurla complex'
    ],

    'powai': [
        'powai',
        'chandivali'
    ],

    'mulund': [
        'mulund'
    ],

    'dahisar': [
        'dahisar'
    ],

    'vile parle': [
        'vile parle'
    ],

    'matunga': [
        'matunga'
    ],

    'khar': [
        'khar'
    ],

    'worli': [
        'worli'
    ],

    'colaba': [
        'colaba',
        'apollo bandar'
    ],

    # Navi Mumbai
    'panvel': [
        'panvel',
        'new panvel',
        'old panvel',
        'palaspe phata',
        'palaspa',
        'khanda colony'
    ],

    'ulwe': [
        'ulwe',
        'pushpak nagar',
        'khar kopar'
    ],

    'kharghar': [
        'kharghar',
        'sector 10 kharghar',
        'sector 20 kharghar',
        'sector 21 kharghar',
        'sector 33 kharghar',
        'sector 35 kharghar'
    ],

    'kamothe': [
        'kamothe'
    ],

    'nerul': [
        'nerul',
        'darave village'
    ],

    'belapur': [
        'belapur'
    ],

    'kalamboli': [
        'kalamboli',
        'roadpali'
    ],

    'taloja': [
        'taloja'
    ],

    'kopar khairane': [
        'kopar khairane',
        'koperkhairane'
    ],

    'vashi': [
        'vashi'
    ],

    # Thane Region
    'thane': [
        'thane',
        'ghodbunder road'
    ],

    'kalyan': [
        'kalyan',
        'tisgao naka'
    ],

    'dombivli': [
        'dombivli'
    ],

    'badlapur': [
        'badlapur'
    ],

    'ulhasnagar': [
        'ulhasnagar'
    ],

    'bhiwandi': [
        'bhiwandi'
    ],

    'karjat': [
        'karjat'
    ],

    'murbad': [
        'murbad'
    ],

    'khopoli': [
        'khopoli'
    ]
}

def clean_location(loc):

    if pd.isna(loc):
        return np.nan


    loc = loc.lower().strip()

    loc = re.sub(
        r'\b(east|west|north|south)\b',
        '',
        loc
    )

    loc = " ".join(loc.split())

    for main_area, keywords in location_map.items():

        for word in keywords:

            if word in loc:
                return main_area.title()

    return loc.split(',')[0].title()


df['address'] = df['address'].apply(clean_location)

## floorNumAllowed

In [222]:
df['floorNumAllowed'].unique()

array([ 3., nan, 20.,  9., 14.,  4.,  2., 22.,  0., 50.,  1., 10.,  5.,
        7., 11.,  8.,  6., 15., 18., 13., 12., 78., 25., 30., 17., 16.,
       24., 28., 35.])

In [223]:
df['floorNumAllowed'] = (
    df['floorNumAllowed']
    .fillna(df['floorNumAllowed'].median())
    .round()
    .astype(int)
)

In [224]:
df.head()

,price,area_sqft,address,floorNumAllowed,possession,nearbyLocations,description,features,rating,price_per_sqft
0,4.50,2500.0,Chembur,3,New Construction / Immediate,Shankar Deol (Religious Place) | Kali -Bari Ma...,Looking for buyer to purchase our land availab...,NaN,O,18000.00
1,36.00,9000.0,Sri Mukteshwar Devalaya Rd,4,New Construction / Immediate,NaN,The property is near to kailash society \nOpen...,NaN,A,40000.00
2,150.00,27000.0,Vile Parle,4,New Construction / Immediate,Jayashree (Parking) | our lady of health churc...,"Spanning 27,000 sq.Ft., this residential land ...",NaN,A,55555.56
3,11.00,3838.0,Santacruz,4,New Construction,Cross INRI (Religious Place) | Umar Masjid (Re...,"Freehold 3,838 sq.Ft plot (Cts 6170) kolekalya...",NaN,O,28660.76
4,0.22,1200.0,Powai,4,New Construction,Saki naka metro station (Metro Station) | Asal...,Planning to purchase a plot in central mumbai?...,NaN,O,1833.33

In [225]:
df.drop(columns='possession', inplace=True)

In [226]:
df.head()

,price,area_sqft,address,floorNumAllowed,nearbyLocations,description,features,rating,price_per_sqft
0,4.50,2500.0,Chembur,3,Shankar Deol (Religious Place) | Kali -Bari Ma...,Looking for buyer to purchase our land availab...,NaN,O,18000.00
1,36.00,9000.0,Sri Mukteshwar Devalaya Rd,4,NaN,The property is near to kailash society \nOpen...,NaN,A,40000.00
2,150.00,27000.0,Vile Parle,4,Jayashree (Parking) | our lady of health churc...,"Spanning 27,000 sq.Ft., this residential land ...",NaN,A,55555.56
3,11.00,3838.0,Santacruz,4,Cross INRI (Religious Place) | Umar Masjid (Re...,"Freehold 3,838 sq.Ft plot (Cts 6170) kolekalya...",NaN,O,28660.76
4,0.22,1200.0,Powai,4,Saki naka metro station (Metro Station) | Asal...,Planning to purchase a plot in central mumbai?...,NaN,O,1833.33

## features

In [233]:
df['features'].value_counts()

features
Solar Panels | Piped Gas | Club House | Intercom                                                                                                               407
Solar Panels                                                                                                                                                   107
Intercom                                                                                                                                                        70
Solar Panels | Piped Gas                                                                                                                                        34
Piped Gas | Club House | Intercom                                                                                                                               32
Solar Panels | Piped Gas | Intercom                                                                                                                             30
Solar Panels | Intercom                                                                                                                                         21
Piped Gas | Intercom                                                                                                                                            18
Club House | Intercom                                                                                                                                           17
Solar Panels | Piped Gas | Club House                                                                                                                           16
Piped Gas | Club House                                                                                                                                          13
Piped Gas                                                                                                                                                       12
Club House                                                                                                                                                       8
Solar Panels | Club House | Intercom                                                                                                                             5
East Facing | Corner Property | Overlooking Main Road                                                                                                            5
Solar Panels | Club House                                                                                                                                        4
Corner Property | Overlooking Main Road                                                                                                                          4
East Facing                                                                                                                                                      4
Close to Market | Overlooking Main Road                                                                                                                          3
Close to School | Close to Hospital | Close to Market                                                                                                            3
Corner Property                                                                                                                                                  2
East Facing | Close to Market | Overlooking Main Road                                                                                                            2
East Facing | Overlooking Main Road                                                                                                                              2
Close to Metro Station | Close to Hospital | Close to Market                                                                                                     1
Close to Metro Station | Close to Hospital                                                                                                                       1
Close to School                                                                                                                                                  1
Lift | Community Hall | Shopping Centre | Waste Disposal | Security Guard | Maintenance Staff | Rain Water Harvesting | Solar Panels | Creche                    1
North-East Facing | Close to Hospital | Overlooking Main Road                                                                                                    1
Multipurpose Room | Tennis Court | Community Hall | Amphitheatre | Reserved Parking | Security | Squash Court | Children's Play Area | ATM | Security Guard      1
North Facing | Close to Metro Station | Close to School | Close to Airport                                                                                       1
North Facing                                                                                                                                                     1
North Facing | Close to Metro Station                                                                                                                            1
Close to Market | Corner Property | Overlooking Main Road                                                                                                        1
East Facing | Close to School | Close to Hospital | Close to Market                                                                                              1
Close to Airport                                                                                                                                                 1
Close to School | Close to Hospital | Close to Market | Overlooking Main Road                                                                                    1
East Facing | school within 500m | hospital  within 500m | market within 500m                                                                                    1
East Facing | school  within 500m | hospital within 500m | market within 500m                                                                                    1
East Facing | Navi Mumbai international  Nearby                                                                                                                  1
East Facing | St Wilfred School  Nearby | D mart Nearby                                                                                                          1
Overlooking Park                                                                                                                                                 1
North Facing | Amandut metro station within 500m | Nmims college within 500m | Tata hospital within 1km                                                          1
East Facing | Chatrapati Shivaji Vidyalaya within 2.5km | Anuragh Multispeciality within 3km                                                                     1
East Facing | Jupiter hospital within 250m                                                                                                                       1
Navi Mumbai Airport within 3km | Atal Setu Junction within 1km | East Facing | Overlooking Main Road                                                             1
East Facing | Kendriya vihar metro station within 500m | Apeeje school within 500m | Tata hospital within 500m                                                   1
Name: count, dtype: int64

In [228]:
def clean_features(text):
    if pd.isna(text):
        return text
    parts = [p.strip() for p in text.split('|')]
    parts = [p for p in parts if not p.startswith('#')]
    return ' | '.join(parts)

df['features'] = df['features'].apply(clean_features)

In [234]:
df['feature_count'] = df['features'].apply(
    lambda x: len(str(x).split('|')) if pd.notna(x) and x != '' else 0
)

In [235]:
df.drop(columns='features', inplace=True)

In [237]:
df.head()

,price,area_sqft,address,floorNumAllowed,nearbyLocations,description,rating,price_per_sqft,feature_count
0,4.50,2500.0,Chembur,3,Shankar Deol (Religious Place) | Kali -Bari Ma...,Looking for buyer to purchase our land availab...,O,18000.00,0
1,36.00,9000.0,Sri Mukteshwar Devalaya Rd,4,NaN,The property is near to kailash society \nOpen...,A,40000.00,0
2,150.00,27000.0,Vile Parle,4,Jayashree (Parking) | our lady of health churc...,"Spanning 27,000 sq.Ft., this residential land ...",A,55555.56,0
3,11.00,3838.0,Santacruz,4,Cross INRI (Religious Place) | Umar Masjid (Re...,"Freehold 3,838 sq.Ft plot (Cts 6170) kolekalya...",O,28660.76,0
4,0.22,1200.0,Powai,4,Saki naka metro station (Metro Station) | Asal...,Planning to purchase a plot in central mumbai?...,O,1833.33,0